// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	SysApplication   *sysApplication
	SysConfig        *sysConfig
	SysDept          *sysDept
	SysDictDatum     *sysDictDatum
	SysDictType      *sysDictType
	SysLoginLog      *sysLoginLog
	SysOauthProvider *sysOauthProvider
	SysOauthUser     *sysOauthUser
	SysOperationLog  *sysOperationLog
	SysResource      *sysResource
	SysRole          *sysRole
	SysRoleResource  *sysRoleResource
	SysUser          *sysUser
	SysUserApp       *sysUserApp
	SysUserRole      *sysUserRole
	SysUserToken     *sysUserToken
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SysApplication = &Q.SysApplication
	SysConfig = &Q.SysConfig
	SysDept = &Q.SysDept
	SysDictDatum = &Q.SysDictDatum
	SysDictType = &Q.SysDictType
	SysLoginLog = &Q.SysLoginLog
	SysOauthProvider = &Q.SysOauthProvider
	SysOauthUser = &Q.SysOauthUser
	SysOperationLog = &Q.SysOperationLog
	SysResource = &Q.SysResource
	SysRole = &Q.SysRole
	SysRoleResource = &Q.SysRoleResource
	SysUser = &Q.SysUser
	SysUserApp = &Q.SysUserApp
	SysUserRole = &Q.SysUserRole
	SysUserToken = &Q.SysUserToken
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		SysApplication:   newSysApplication(db, opts...),
		SysConfig:        newSysConfig(db, opts...),
		SysDept:          newSysDept(db, opts...),
		SysDictDatum:     newSysDictDatum(db, opts...),
		SysDictType:      newSysDictType(db, opts...),
		SysLoginLog:      newSysLoginLog(db, opts...),
		SysOauthProvider: newSysOauthProvider(db, opts...),
		SysOauthUser:     newSysOauthUser(db, opts...),
		SysOperationLog:  newSysOperationLog(db, opts...),
		SysResource:      newSysResource(db, opts...),
		SysRole:          newSysRole(db, opts...),
		SysRoleResource:  newSysRoleResource(db, opts...),
		SysUser:          newSysUser(db, opts...),
		SysUserApp:       newSysUserApp(db, opts...),
		SysUserRole:      newSysUserRole(db, opts...),
		SysUserToken:     newSysUserToken(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SysApplication   sysApplication
	SysConfig        sysConfig
	SysDept          sysDept
	SysDictDatum     sysDictDatum
	SysDictType      sysDictType
	SysLoginLog      sysLoginLog
	SysOauthProvider sysOauthProvider
	SysOauthUser     sysOauthUser
	SysOperationLog  sysOperationLog
	SysResource      sysResource
	SysRole          sysRole
	SysRoleResource  sysRoleResource
	SysUser          sysUser
	SysUserApp       sysUserApp
	SysUserRole      sysUserRole
	SysUserToken     sysUserToken
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		SysApplication:   q.SysApplication.clone(db),
		SysConfig:        q.SysConfig.clone(db),
		SysDept:          q.SysDept.clone(db),
		SysDictDatum:     q.SysDictDatum.clone(db),
		SysDictType:      q.SysDictType.clone(db),
		SysLoginLog:      q.SysLoginLog.clone(db),
		SysOauthProvider: q.SysOauthProvider.clone(db),
		SysOauthUser:     q.SysOauthUser.clone(db),
		SysOperationLog:  q.SysOperationLog.clone(db),
		SysResource:      q.SysResource.clone(db),
		SysRole:          q.SysRole.clone(db),
		SysRoleResource:  q.SysRoleResource.clone(db),
		SysUser:          q.SysUser.clone(db),
		SysUserApp:       q.SysUserApp.clone(db),
		SysUserRole:      q.SysUserRole.clone(db),
		SysUserToken:     q.SysUserToken.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		SysApplication:   q.SysApplication.replaceDB(db),
		SysConfig:        q.SysConfig.replaceDB(db),
		SysDept:          q.SysDept.replaceDB(db),
		SysDictDatum:     q.SysDictDatum.replaceDB(db),
		SysDictType:      q.SysDictType.replaceDB(db),
		SysLoginLog:      q.SysLoginLog.replaceDB(db),
		SysOauthProvider: q.SysOauthProvider.replaceDB(db),
		SysOauthUser:     q.SysOauthUser.replaceDB(db),
		SysOperationLog:  q.SysOperationLog.replaceDB(db),
		SysResource:      q.SysResource.replaceDB(db),
		SysRole:          q.SysRole.replaceDB(db),
		SysRoleResource:  q.SysRoleResource.replaceDB(db),
		SysUser:          q.SysUser.replaceDB(db),
		SysUserApp:       q.SysUserApp.replaceDB(db),
		SysUserRole:      q.SysUserRole.replaceDB(db),
		SysUserToken:     q.SysUserToken.replaceDB(db),
	}
}

type queryCtx struct {
	SysApplication   ISysApplicationDo
	SysConfig        ISysConfigDo
	SysDept          ISysDeptDo
	SysDictDatum     ISysDictDatumDo
	SysDictType      ISysDictTypeDo
	SysLoginLog      ISysLoginLogDo
	SysOauthProvider ISysOauthProviderDo
	SysOauthUser     ISysOauthUserDo
	SysOperationLog  ISysOperationLogDo
	SysResource      ISysResourceDo
	SysRole          ISysRoleDo
	SysRoleResource  ISysRoleResourceDo
	SysUser          ISysUserDo
	SysUserApp       ISysUserAppDo
	SysUserRole      ISysUserRoleDo
	SysUserToken     ISysUserTokenDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SysApplication:   q.SysApplication.WithContext(ctx),
		SysConfig:        q.SysConfig.WithContext(ctx),
		SysDept:          q.SysDept.WithContext(ctx),
		SysDictDatum:     q.SysDictDatum.WithContext(ctx),
		SysDictType:      q.SysDictType.WithContext(ctx),
		SysLoginLog:      q.SysLoginLog.WithContext(ctx),
		SysOauthProvider: q.SysOauthProvider.WithContext(ctx),
		SysOauthUser:     q.SysOauthUser.WithContext(ctx),
		SysOperationLog:  q.SysOperationLog.WithContext(ctx),
		SysResource:      q.SysResource.WithContext(ctx),
		SysRole:          q.SysRole.WithContext(ctx),
		SysRoleResource:  q.SysRoleResource.WithContext(ctx),
		SysUser:          q.SysUser.WithContext(ctx),
		SysUserApp:       q.SysUserApp.WithContext(ctx),
		SysUserRole:      q.SysUserRole.WithContext(ctx),
		SysUserToken:     q.SysUserToken.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
