// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/admin/internal/model"
)

func newSysUserApp(db *gorm.DB, opts ...gen.DOOption) sysUserApp {
	_sysUserApp := sysUserApp{}

	_sysUserApp.sysUserAppDo.UseDB(db, opts...)
	_sysUserApp.sysUserAppDo.UseModel(&model.SysUserApp{})

	tableName := _sysUserApp.sysUserAppDo.TableName()
	_sysUserApp.ALL = field.NewAsterisk(tableName)
	_sysUserApp.ID = field.NewInt64(tableName, "id")
	_sysUserApp.CreatedAt = field.NewTime(tableName, "created_at")
	_sysUserApp.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysUserApp.IsDelete = field.NewBool(tableName, "is_delete")
	_sysUserApp.UserID = field.NewInt64(tableName, "user_id")
	_sysUserApp.AppID = field.NewInt64(tableName, "app_id")
	_sysUserApp.Source = field.NewString(tableName, "source")
	_sysUserApp.FirstLoginAt = field.NewTime(tableName, "first_login_at")
	_sysUserApp.LastLoginAt = field.NewTime(tableName, "last_login_at")
	_sysUserApp.LoginCount = field.NewInt32(tableName, "login_count")
	_sysUserApp.Status = field.NewInt32(tableName, "status")
	_sysUserApp.Remark = field.NewString(tableName, "remark")

	_sysUserApp.fillFieldMap()

	return _sysUserApp
}

// sysUserApp 用户-应用关联表
type sysUserApp struct {
	sysUserAppDo sysUserAppDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	IsDelete     field.Bool
	UserID       field.Int64  // 用户ID
	AppID        field.Int64  // 应用ID
	Source       field.String // 注册来源: system-系统创建, oauth-第三方登录, register-自主注册, invite-邀请注册
	FirstLoginAt field.Time   // 首次登录时间
	LastLoginAt  field.Time   // 最后登录时间
	LoginCount   field.Int32  // 登录次数
	Status       field.Int32  // 状态: 1-正常, 0-禁用
	Remark       field.String // 备注

	fieldMap map[string]field.Expr
}

func (s sysUserApp) Table(newTableName string) *sysUserApp {
	s.sysUserAppDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserApp) As(alias string) *sysUserApp {
	s.sysUserAppDo.DO = *(s.sysUserAppDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserApp) updateTableName(table string) *sysUserApp {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.IsDelete = field.NewBool(table, "is_delete")
	s.UserID = field.NewInt64(table, "user_id")
	s.AppID = field.NewInt64(table, "app_id")
	s.Source = field.NewString(table, "source")
	s.FirstLoginAt = field.NewTime(table, "first_login_at")
	s.LastLoginAt = field.NewTime(table, "last_login_at")
	s.LoginCount = field.NewInt32(table, "login_count")
	s.Status = field.NewInt32(table, "status")
	s.Remark = field.NewString(table, "remark")

	s.fillFieldMap()

	return s
}

func (s *sysUserApp) WithContext(ctx context.Context) ISysUserAppDo {
	return s.sysUserAppDo.WithContext(ctx)
}

func (s sysUserApp) TableName() string { return s.sysUserAppDo.TableName() }

func (s sysUserApp) Alias() string { return s.sysUserAppDo.Alias() }

func (s sysUserApp) Columns(cols ...field.Expr) gen.Columns { return s.sysUserAppDo.Columns(cols...) }

func (s *sysUserApp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserApp) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["is_delete"] = s.IsDelete
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["app_id"] = s.AppID
	s.fieldMap["source"] = s.Source
	s.fieldMap["first_login_at"] = s.FirstLoginAt
	s.fieldMap["last_login_at"] = s.LastLoginAt
	s.fieldMap["login_count"] = s.LoginCount
	s.fieldMap["status"] = s.Status
	s.fieldMap["remark"] = s.Remark
}

func (s sysUserApp) clone(db *gorm.DB) sysUserApp {
	s.sysUserAppDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserApp) replaceDB(db *gorm.DB) sysUserApp {
	s.sysUserAppDo.ReplaceDB(db)
	return s
}

type sysUserAppDo struct{ gen.DO }

type ISysUserAppDo interface {
	gen.SubQuery
	Debug() ISysUserAppDo
	WithContext(ctx context.Context) ISysUserAppDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserAppDo
	WriteDB() ISysUserAppDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserAppDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserAppDo
	Not(conds ...gen.Condition) ISysUserAppDo
	Or(conds ...gen.Condition) ISysUserAppDo
	Select(conds ...field.Expr) ISysUserAppDo
	Where(conds ...gen.Condition) ISysUserAppDo
	Order(conds ...field.Expr) ISysUserAppDo
	Distinct(cols ...field.Expr) ISysUserAppDo
	Omit(cols ...field.Expr) ISysUserAppDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserAppDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserAppDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserAppDo
	Group(cols ...field.Expr) ISysUserAppDo
	Having(conds ...gen.Condition) ISysUserAppDo
	Limit(limit int) ISysUserAppDo
	Offset(offset int) ISysUserAppDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserAppDo
	Unscoped() ISysUserAppDo
	Create(values ...*model.SysUserApp) error
	CreateInBatches(values []*model.SysUserApp, batchSize int) error
	Save(values ...*model.SysUserApp) error
	First() (*model.SysUserApp, error)
	Take() (*model.SysUserApp, error)
	Last() (*model.SysUserApp, error)
	Find() ([]*model.SysUserApp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserApp, err error)
	FindInBatches(result *[]*model.SysUserApp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysUserApp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserAppDo
	Assign(attrs ...field.AssignExpr) ISysUserAppDo
	Joins(fields ...field.RelationField) ISysUserAppDo
	Preload(fields ...field.RelationField) ISysUserAppDo
	FirstOrInit() (*model.SysUserApp, error)
	FirstOrCreate() (*model.SysUserApp, error)
	FindByPage(offset int, limit int) (result []*model.SysUserApp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserAppDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserAppDo) Debug() ISysUserAppDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserAppDo) WithContext(ctx context.Context) ISysUserAppDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserAppDo) ReadDB() ISysUserAppDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserAppDo) WriteDB() ISysUserAppDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserAppDo) Session(config *gorm.Session) ISysUserAppDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserAppDo) Clauses(conds ...clause.Expression) ISysUserAppDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserAppDo) Returning(value interface{}, columns ...string) ISysUserAppDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserAppDo) Not(conds ...gen.Condition) ISysUserAppDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserAppDo) Or(conds ...gen.Condition) ISysUserAppDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserAppDo) Select(conds ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserAppDo) Where(conds ...gen.Condition) ISysUserAppDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserAppDo) Order(conds ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserAppDo) Distinct(cols ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserAppDo) Omit(cols ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserAppDo) Join(table schema.Tabler, on ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserAppDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserAppDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserAppDo) Group(cols ...field.Expr) ISysUserAppDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserAppDo) Having(conds ...gen.Condition) ISysUserAppDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserAppDo) Limit(limit int) ISysUserAppDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserAppDo) Offset(offset int) ISysUserAppDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserAppDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserAppDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserAppDo) Unscoped() ISysUserAppDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserAppDo) Create(values ...*model.SysUserApp) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserAppDo) CreateInBatches(values []*model.SysUserApp, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserAppDo) Save(values ...*model.SysUserApp) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserAppDo) First() (*model.SysUserApp, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserApp), nil
	}
}

func (s sysUserAppDo) Take() (*model.SysUserApp, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserApp), nil
	}
}

func (s sysUserAppDo) Last() (*model.SysUserApp, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserApp), nil
	}
}

func (s sysUserAppDo) Find() ([]*model.SysUserApp, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserApp), err
}

func (s sysUserAppDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserApp, err error) {
	buf := make([]*model.SysUserApp, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserAppDo) FindInBatches(result *[]*model.SysUserApp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserAppDo) Attrs(attrs ...field.AssignExpr) ISysUserAppDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserAppDo) Assign(attrs ...field.AssignExpr) ISysUserAppDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserAppDo) Joins(fields ...field.RelationField) ISysUserAppDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserAppDo) Preload(fields ...field.RelationField) ISysUserAppDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserAppDo) FirstOrInit() (*model.SysUserApp, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserApp), nil
	}
}

func (s sysUserAppDo) FirstOrCreate() (*model.SysUserApp, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserApp), nil
	}
}

func (s sysUserAppDo) FindByPage(offset int, limit int) (result []*model.SysUserApp, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserAppDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserAppDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserAppDo) Delete(models ...*model.SysUserApp) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserAppDo) withDO(do gen.Dao) *sysUserAppDo {
	s.DO = *do.(*gen.DO)
	return s
}
