// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/admin/internal/model"
)

func newSysOauthProvider(db *gorm.DB, opts ...gen.DOOption) sysOauthProvider {
	_sysOauthProvider := sysOauthProvider{}

	_sysOauthProvider.sysOauthProviderDo.UseDB(db, opts...)
	_sysOauthProvider.sysOauthProviderDo.UseModel(&model.SysOauthProvider{})

	tableName := _sysOauthProvider.sysOauthProviderDo.TableName()
	_sysOauthProvider.ALL = field.NewAsterisk(tableName)
	_sysOauthProvider.ID = field.NewInt64(tableName, "id")
	_sysOauthProvider.CreatedAt = field.NewTime(tableName, "created_at")
	_sysOauthProvider.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysOauthProvider.IsDelete = field.NewBool(tableName, "is_delete")
	_sysOauthProvider.Name = field.NewString(tableName, "name")
	_sysOauthProvider.Code = field.NewString(tableName, "code")
	_sysOauthProvider.ClientID = field.NewString(tableName, "client_id")
	_sysOauthProvider.ClientSecret = field.NewString(tableName, "client_secret")
	_sysOauthProvider.RedirectURI = field.NewString(tableName, "redirect_uri")
	_sysOauthProvider.AuthURL = field.NewString(tableName, "auth_url")
	_sysOauthProvider.TokenURL = field.NewString(tableName, "token_url")
	_sysOauthProvider.UserInfoURL = field.NewString(tableName, "user_info_url")
	_sysOauthProvider.Scope = field.NewString(tableName, "scope")
	_sysOauthProvider.Status = field.NewInt32(tableName, "status")
	_sysOauthProvider.Sort = field.NewInt64(tableName, "sort")
	_sysOauthProvider.Icon = field.NewString(tableName, "icon")
	_sysOauthProvider.Remark = field.NewString(tableName, "remark")

	_sysOauthProvider.fillFieldMap()

	return _sysOauthProvider
}

type sysOauthProvider struct {
	sysOauthProviderDo sysOauthProviderDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	IsDelete     field.Bool
	Name         field.String
	Code         field.String
	ClientID     field.String
	ClientSecret field.String
	RedirectURI  field.String
	AuthURL      field.String
	TokenURL     field.String
	UserInfoURL  field.String
	Scope        field.String
	Status       field.Int32
	Sort         field.Int64
	Icon         field.String
	Remark       field.String

	fieldMap map[string]field.Expr
}

func (s sysOauthProvider) Table(newTableName string) *sysOauthProvider {
	s.sysOauthProviderDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOauthProvider) As(alias string) *sysOauthProvider {
	s.sysOauthProviderDo.DO = *(s.sysOauthProviderDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOauthProvider) updateTableName(table string) *sysOauthProvider {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.IsDelete = field.NewBool(table, "is_delete")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.ClientID = field.NewString(table, "client_id")
	s.ClientSecret = field.NewString(table, "client_secret")
	s.RedirectURI = field.NewString(table, "redirect_uri")
	s.AuthURL = field.NewString(table, "auth_url")
	s.TokenURL = field.NewString(table, "token_url")
	s.UserInfoURL = field.NewString(table, "user_info_url")
	s.Scope = field.NewString(table, "scope")
	s.Status = field.NewInt32(table, "status")
	s.Sort = field.NewInt64(table, "sort")
	s.Icon = field.NewString(table, "icon")
	s.Remark = field.NewString(table, "remark")

	s.fillFieldMap()

	return s
}

func (s *sysOauthProvider) WithContext(ctx context.Context) ISysOauthProviderDo {
	return s.sysOauthProviderDo.WithContext(ctx)
}

func (s sysOauthProvider) TableName() string { return s.sysOauthProviderDo.TableName() }

func (s sysOauthProvider) Alias() string { return s.sysOauthProviderDo.Alias() }

func (s sysOauthProvider) Columns(cols ...field.Expr) gen.Columns {
	return s.sysOauthProviderDo.Columns(cols...)
}

func (s *sysOauthProvider) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOauthProvider) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["is_delete"] = s.IsDelete
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["client_secret"] = s.ClientSecret
	s.fieldMap["redirect_uri"] = s.RedirectURI
	s.fieldMap["auth_url"] = s.AuthURL
	s.fieldMap["token_url"] = s.TokenURL
	s.fieldMap["user_info_url"] = s.UserInfoURL
	s.fieldMap["scope"] = s.Scope
	s.fieldMap["status"] = s.Status
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["remark"] = s.Remark
}

func (s sysOauthProvider) clone(db *gorm.DB) sysOauthProvider {
	s.sysOauthProviderDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOauthProvider) replaceDB(db *gorm.DB) sysOauthProvider {
	s.sysOauthProviderDo.ReplaceDB(db)
	return s
}

type sysOauthProviderDo struct{ gen.DO }

type ISysOauthProviderDo interface {
	gen.SubQuery
	Debug() ISysOauthProviderDo
	WithContext(ctx context.Context) ISysOauthProviderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysOauthProviderDo
	WriteDB() ISysOauthProviderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysOauthProviderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysOauthProviderDo
	Not(conds ...gen.Condition) ISysOauthProviderDo
	Or(conds ...gen.Condition) ISysOauthProviderDo
	Select(conds ...field.Expr) ISysOauthProviderDo
	Where(conds ...gen.Condition) ISysOauthProviderDo
	Order(conds ...field.Expr) ISysOauthProviderDo
	Distinct(cols ...field.Expr) ISysOauthProviderDo
	Omit(cols ...field.Expr) ISysOauthProviderDo
	Join(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo
	Group(cols ...field.Expr) ISysOauthProviderDo
	Having(conds ...gen.Condition) ISysOauthProviderDo
	Limit(limit int) ISysOauthProviderDo
	Offset(offset int) ISysOauthProviderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauthProviderDo
	Unscoped() ISysOauthProviderDo
	Create(values ...*model.SysOauthProvider) error
	CreateInBatches(values []*model.SysOauthProvider, batchSize int) error
	Save(values ...*model.SysOauthProvider) error
	First() (*model.SysOauthProvider, error)
	Take() (*model.SysOauthProvider, error)
	Last() (*model.SysOauthProvider, error)
	Find() ([]*model.SysOauthProvider, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauthProvider, err error)
	FindInBatches(result *[]*model.SysOauthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysOauthProvider) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysOauthProviderDo
	Assign(attrs ...field.AssignExpr) ISysOauthProviderDo
	Joins(fields ...field.RelationField) ISysOauthProviderDo
	Preload(fields ...field.RelationField) ISysOauthProviderDo
	FirstOrInit() (*model.SysOauthProvider, error)
	FirstOrCreate() (*model.SysOauthProvider, error)
	FindByPage(offset int, limit int) (result []*model.SysOauthProvider, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysOauthProviderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysOauthProviderDo) Debug() ISysOauthProviderDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOauthProviderDo) WithContext(ctx context.Context) ISysOauthProviderDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOauthProviderDo) ReadDB() ISysOauthProviderDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOauthProviderDo) WriteDB() ISysOauthProviderDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOauthProviderDo) Session(config *gorm.Session) ISysOauthProviderDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOauthProviderDo) Clauses(conds ...clause.Expression) ISysOauthProviderDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOauthProviderDo) Returning(value interface{}, columns ...string) ISysOauthProviderDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOauthProviderDo) Not(conds ...gen.Condition) ISysOauthProviderDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOauthProviderDo) Or(conds ...gen.Condition) ISysOauthProviderDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOauthProviderDo) Select(conds ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOauthProviderDo) Where(conds ...gen.Condition) ISysOauthProviderDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOauthProviderDo) Order(conds ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOauthProviderDo) Distinct(cols ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOauthProviderDo) Omit(cols ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOauthProviderDo) Join(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOauthProviderDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOauthProviderDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOauthProviderDo) Group(cols ...field.Expr) ISysOauthProviderDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOauthProviderDo) Having(conds ...gen.Condition) ISysOauthProviderDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOauthProviderDo) Limit(limit int) ISysOauthProviderDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOauthProviderDo) Offset(offset int) ISysOauthProviderDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOauthProviderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauthProviderDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOauthProviderDo) Unscoped() ISysOauthProviderDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOauthProviderDo) Create(values ...*model.SysOauthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOauthProviderDo) CreateInBatches(values []*model.SysOauthProvider, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOauthProviderDo) Save(values ...*model.SysOauthProvider) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOauthProviderDo) First() (*model.SysOauthProvider, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthProvider), nil
	}
}

func (s sysOauthProviderDo) Take() (*model.SysOauthProvider, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthProvider), nil
	}
}

func (s sysOauthProviderDo) Last() (*model.SysOauthProvider, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthProvider), nil
	}
}

func (s sysOauthProviderDo) Find() ([]*model.SysOauthProvider, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysOauthProvider), err
}

func (s sysOauthProviderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauthProvider, err error) {
	buf := make([]*model.SysOauthProvider, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOauthProviderDo) FindInBatches(result *[]*model.SysOauthProvider, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOauthProviderDo) Attrs(attrs ...field.AssignExpr) ISysOauthProviderDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOauthProviderDo) Assign(attrs ...field.AssignExpr) ISysOauthProviderDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOauthProviderDo) Joins(fields ...field.RelationField) ISysOauthProviderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOauthProviderDo) Preload(fields ...field.RelationField) ISysOauthProviderDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOauthProviderDo) FirstOrInit() (*model.SysOauthProvider, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthProvider), nil
	}
}

func (s sysOauthProviderDo) FirstOrCreate() (*model.SysOauthProvider, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthProvider), nil
	}
}

func (s sysOauthProviderDo) FindByPage(offset int, limit int) (result []*model.SysOauthProvider, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOauthProviderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOauthProviderDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOauthProviderDo) Delete(models ...*model.SysOauthProvider) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOauthProviderDo) withDO(do gen.Dao) *sysOauthProviderDo {
	s.DO = *do.(*gen.DO)
	return s
}
