// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/admin/internal/model"
)

func newSysOauthUser(db *gorm.DB, opts ...gen.DOOption) sysOauthUser {
	_sysOauthUser := sysOauthUser{}

	_sysOauthUser.sysOauthUserDo.UseDB(db, opts...)
	_sysOauthUser.sysOauthUserDo.UseModel(&model.SysOauthUser{})

	tableName := _sysOauthUser.sysOauthUserDo.TableName()
	_sysOauthUser.ALL = field.NewAsterisk(tableName)
	_sysOauthUser.ID = field.NewInt64(tableName, "id")
	_sysOauthUser.CreatedAt = field.NewTime(tableName, "created_at")
	_sysOauthUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysOauthUser.IsDelete = field.NewBool(tableName, "is_delete")
	_sysOauthUser.UserID = field.NewInt64(tableName, "user_id")
	_sysOauthUser.ProviderCode = field.NewString(tableName, "provider_code")
	_sysOauthUser.OpenID = field.NewString(tableName, "open_id")
	_sysOauthUser.UnionID = field.NewString(tableName, "union_id")
	_sysOauthUser.Nickname = field.NewString(tableName, "nickname")
	_sysOauthUser.Avatar = field.NewString(tableName, "avatar")
	_sysOauthUser.AccessToken = field.NewString(tableName, "access_token")
	_sysOauthUser.RefreshToken = field.NewString(tableName, "refresh_token")
	_sysOauthUser.ExpiresAt = field.NewInt64(tableName, "expires_at")
	_sysOauthUser.RawData = field.NewString(tableName, "raw_data")

	_sysOauthUser.fillFieldMap()

	return _sysOauthUser
}

type sysOauthUser struct {
	sysOauthUserDo sysOauthUserDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Time
	UpdatedAt    field.Time
	IsDelete     field.Bool
	UserID       field.Int64
	ProviderCode field.String
	OpenID       field.String
	UnionID      field.String
	Nickname     field.String
	Avatar       field.String
	AccessToken  field.String
	RefreshToken field.String
	ExpiresAt    field.Int64
	RawData      field.String

	fieldMap map[string]field.Expr
}

func (s sysOauthUser) Table(newTableName string) *sysOauthUser {
	s.sysOauthUserDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOauthUser) As(alias string) *sysOauthUser {
	s.sysOauthUserDo.DO = *(s.sysOauthUserDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOauthUser) updateTableName(table string) *sysOauthUser {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.IsDelete = field.NewBool(table, "is_delete")
	s.UserID = field.NewInt64(table, "user_id")
	s.ProviderCode = field.NewString(table, "provider_code")
	s.OpenID = field.NewString(table, "open_id")
	s.UnionID = field.NewString(table, "union_id")
	s.Nickname = field.NewString(table, "nickname")
	s.Avatar = field.NewString(table, "avatar")
	s.AccessToken = field.NewString(table, "access_token")
	s.RefreshToken = field.NewString(table, "refresh_token")
	s.ExpiresAt = field.NewInt64(table, "expires_at")
	s.RawData = field.NewString(table, "raw_data")

	s.fillFieldMap()

	return s
}

func (s *sysOauthUser) WithContext(ctx context.Context) ISysOauthUserDo {
	return s.sysOauthUserDo.WithContext(ctx)
}

func (s sysOauthUser) TableName() string { return s.sysOauthUserDo.TableName() }

func (s sysOauthUser) Alias() string { return s.sysOauthUserDo.Alias() }

func (s sysOauthUser) Columns(cols ...field.Expr) gen.Columns {
	return s.sysOauthUserDo.Columns(cols...)
}

func (s *sysOauthUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOauthUser) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["is_delete"] = s.IsDelete
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["provider_code"] = s.ProviderCode
	s.fieldMap["open_id"] = s.OpenID
	s.fieldMap["union_id"] = s.UnionID
	s.fieldMap["nickname"] = s.Nickname
	s.fieldMap["avatar"] = s.Avatar
	s.fieldMap["access_token"] = s.AccessToken
	s.fieldMap["refresh_token"] = s.RefreshToken
	s.fieldMap["expires_at"] = s.ExpiresAt
	s.fieldMap["raw_data"] = s.RawData
}

func (s sysOauthUser) clone(db *gorm.DB) sysOauthUser {
	s.sysOauthUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOauthUser) replaceDB(db *gorm.DB) sysOauthUser {
	s.sysOauthUserDo.ReplaceDB(db)
	return s
}

type sysOauthUserDo struct{ gen.DO }

type ISysOauthUserDo interface {
	gen.SubQuery
	Debug() ISysOauthUserDo
	WithContext(ctx context.Context) ISysOauthUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysOauthUserDo
	WriteDB() ISysOauthUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysOauthUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysOauthUserDo
	Not(conds ...gen.Condition) ISysOauthUserDo
	Or(conds ...gen.Condition) ISysOauthUserDo
	Select(conds ...field.Expr) ISysOauthUserDo
	Where(conds ...gen.Condition) ISysOauthUserDo
	Order(conds ...field.Expr) ISysOauthUserDo
	Distinct(cols ...field.Expr) ISysOauthUserDo
	Omit(cols ...field.Expr) ISysOauthUserDo
	Join(table schema.Tabler, on ...field.Expr) ISysOauthUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauthUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysOauthUserDo
	Group(cols ...field.Expr) ISysOauthUserDo
	Having(conds ...gen.Condition) ISysOauthUserDo
	Limit(limit int) ISysOauthUserDo
	Offset(offset int) ISysOauthUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauthUserDo
	Unscoped() ISysOauthUserDo
	Create(values ...*model.SysOauthUser) error
	CreateInBatches(values []*model.SysOauthUser, batchSize int) error
	Save(values ...*model.SysOauthUser) error
	First() (*model.SysOauthUser, error)
	Take() (*model.SysOauthUser, error)
	Last() (*model.SysOauthUser, error)
	Find() ([]*model.SysOauthUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauthUser, err error)
	FindInBatches(result *[]*model.SysOauthUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysOauthUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysOauthUserDo
	Assign(attrs ...field.AssignExpr) ISysOauthUserDo
	Joins(fields ...field.RelationField) ISysOauthUserDo
	Preload(fields ...field.RelationField) ISysOauthUserDo
	FirstOrInit() (*model.SysOauthUser, error)
	FirstOrCreate() (*model.SysOauthUser, error)
	FindByPage(offset int, limit int) (result []*model.SysOauthUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysOauthUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysOauthUserDo) Debug() ISysOauthUserDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOauthUserDo) WithContext(ctx context.Context) ISysOauthUserDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOauthUserDo) ReadDB() ISysOauthUserDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOauthUserDo) WriteDB() ISysOauthUserDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOauthUserDo) Session(config *gorm.Session) ISysOauthUserDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOauthUserDo) Clauses(conds ...clause.Expression) ISysOauthUserDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOauthUserDo) Returning(value interface{}, columns ...string) ISysOauthUserDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOauthUserDo) Not(conds ...gen.Condition) ISysOauthUserDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOauthUserDo) Or(conds ...gen.Condition) ISysOauthUserDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOauthUserDo) Select(conds ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOauthUserDo) Where(conds ...gen.Condition) ISysOauthUserDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOauthUserDo) Order(conds ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOauthUserDo) Distinct(cols ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOauthUserDo) Omit(cols ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOauthUserDo) Join(table schema.Tabler, on ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOauthUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOauthUserDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOauthUserDo) Group(cols ...field.Expr) ISysOauthUserDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOauthUserDo) Having(conds ...gen.Condition) ISysOauthUserDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOauthUserDo) Limit(limit int) ISysOauthUserDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOauthUserDo) Offset(offset int) ISysOauthUserDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOauthUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauthUserDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOauthUserDo) Unscoped() ISysOauthUserDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOauthUserDo) Create(values ...*model.SysOauthUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOauthUserDo) CreateInBatches(values []*model.SysOauthUser, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOauthUserDo) Save(values ...*model.SysOauthUser) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOauthUserDo) First() (*model.SysOauthUser, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthUser), nil
	}
}

func (s sysOauthUserDo) Take() (*model.SysOauthUser, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthUser), nil
	}
}

func (s sysOauthUserDo) Last() (*model.SysOauthUser, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthUser), nil
	}
}

func (s sysOauthUserDo) Find() ([]*model.SysOauthUser, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysOauthUser), err
}

func (s sysOauthUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauthUser, err error) {
	buf := make([]*model.SysOauthUser, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOauthUserDo) FindInBatches(result *[]*model.SysOauthUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOauthUserDo) Attrs(attrs ...field.AssignExpr) ISysOauthUserDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOauthUserDo) Assign(attrs ...field.AssignExpr) ISysOauthUserDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOauthUserDo) Joins(fields ...field.RelationField) ISysOauthUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOauthUserDo) Preload(fields ...field.RelationField) ISysOauthUserDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOauthUserDo) FirstOrInit() (*model.SysOauthUser, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthUser), nil
	}
}

func (s sysOauthUserDo) FirstOrCreate() (*model.SysOauthUser, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauthUser), nil
	}
}

func (s sysOauthUserDo) FindByPage(offset int, limit int) (result []*model.SysOauthUser, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOauthUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOauthUserDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOauthUserDo) Delete(models ...*model.SysOauthUser) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOauthUserDo) withDO(do gen.Dao) *sysOauthUserDo {
	s.DO = *do.(*gen.DO)
	return s
}
