// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/admin/internal/model"
)

func newSysApplication(db *gorm.DB, opts ...gen.DOOption) sysApplication {
	_sysApplication := sysApplication{}

	_sysApplication.sysApplicationDo.UseDB(db, opts...)
	_sysApplication.sysApplicationDo.UseModel(&model.SysApplication{})

	tableName := _sysApplication.sysApplicationDo.TableName()
	_sysApplication.ALL = field.NewAsterisk(tableName)
	_sysApplication.ID = field.NewInt64(tableName, "id")
	_sysApplication.CreatedAt = field.NewTime(tableName, "created_at")
	_sysApplication.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysApplication.IsDelete = field.NewBool(tableName, "is_delete")
	_sysApplication.Name = field.NewString(tableName, "name")
	_sysApplication.Code = field.NewString(tableName, "code")
	_sysApplication.Description = field.NewString(tableName, "description")
	_sysApplication.Icon = field.NewString(tableName, "icon")
	_sysApplication.Sort = field.NewInt64(tableName, "sort")
	_sysApplication.Status = field.NewInt32(tableName, "status")

	_sysApplication.fillFieldMap()

	return _sysApplication
}

type sysApplication struct {
	sysApplicationDo sysApplicationDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	Name        field.String
	Code        field.String
	Description field.String
	Icon        field.String
	Sort        field.Int64
	Status      field.Int32

	fieldMap map[string]field.Expr
}

func (s sysApplication) Table(newTableName string) *sysApplication {
	s.sysApplicationDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysApplication) As(alias string) *sysApplication {
	s.sysApplicationDo.DO = *(s.sysApplicationDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysApplication) updateTableName(table string) *sysApplication {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.IsDelete = field.NewBool(table, "is_delete")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Description = field.NewString(table, "description")
	s.Icon = field.NewString(table, "icon")
	s.Sort = field.NewInt64(table, "sort")
	s.Status = field.NewInt32(table, "status")

	s.fillFieldMap()

	return s
}

func (s *sysApplication) WithContext(ctx context.Context) ISysApplicationDo {
	return s.sysApplicationDo.WithContext(ctx)
}

func (s sysApplication) TableName() string { return s.sysApplicationDo.TableName() }

func (s sysApplication) Alias() string { return s.sysApplicationDo.Alias() }

func (s sysApplication) Columns(cols ...field.Expr) gen.Columns {
	return s.sysApplicationDo.Columns(cols...)
}

func (s *sysApplication) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysApplication) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["is_delete"] = s.IsDelete
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["description"] = s.Description
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
}

func (s sysApplication) clone(db *gorm.DB) sysApplication {
	s.sysApplicationDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysApplication) replaceDB(db *gorm.DB) sysApplication {
	s.sysApplicationDo.ReplaceDB(db)
	return s
}

type sysApplicationDo struct{ gen.DO }

type ISysApplicationDo interface {
	gen.SubQuery
	Debug() ISysApplicationDo
	WithContext(ctx context.Context) ISysApplicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysApplicationDo
	WriteDB() ISysApplicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysApplicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysApplicationDo
	Not(conds ...gen.Condition) ISysApplicationDo
	Or(conds ...gen.Condition) ISysApplicationDo
	Select(conds ...field.Expr) ISysApplicationDo
	Where(conds ...gen.Condition) ISysApplicationDo
	Order(conds ...field.Expr) ISysApplicationDo
	Distinct(cols ...field.Expr) ISysApplicationDo
	Omit(cols ...field.Expr) ISysApplicationDo
	Join(table schema.Tabler, on ...field.Expr) ISysApplicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysApplicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysApplicationDo
	Group(cols ...field.Expr) ISysApplicationDo
	Having(conds ...gen.Condition) ISysApplicationDo
	Limit(limit int) ISysApplicationDo
	Offset(offset int) ISysApplicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysApplicationDo
	Unscoped() ISysApplicationDo
	Create(values ...*model.SysApplication) error
	CreateInBatches(values []*model.SysApplication, batchSize int) error
	Save(values ...*model.SysApplication) error
	First() (*model.SysApplication, error)
	Take() (*model.SysApplication, error)
	Last() (*model.SysApplication, error)
	Find() ([]*model.SysApplication, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysApplication, err error)
	FindInBatches(result *[]*model.SysApplication, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysApplication) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysApplicationDo
	Assign(attrs ...field.AssignExpr) ISysApplicationDo
	Joins(fields ...field.RelationField) ISysApplicationDo
	Preload(fields ...field.RelationField) ISysApplicationDo
	FirstOrInit() (*model.SysApplication, error)
	FirstOrCreate() (*model.SysApplication, error)
	FindByPage(offset int, limit int) (result []*model.SysApplication, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysApplicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysApplicationDo) Debug() ISysApplicationDo {
	return s.withDO(s.DO.Debug())
}

func (s sysApplicationDo) WithContext(ctx context.Context) ISysApplicationDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysApplicationDo) ReadDB() ISysApplicationDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysApplicationDo) WriteDB() ISysApplicationDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysApplicationDo) Session(config *gorm.Session) ISysApplicationDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysApplicationDo) Clauses(conds ...clause.Expression) ISysApplicationDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysApplicationDo) Returning(value interface{}, columns ...string) ISysApplicationDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysApplicationDo) Not(conds ...gen.Condition) ISysApplicationDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysApplicationDo) Or(conds ...gen.Condition) ISysApplicationDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysApplicationDo) Select(conds ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysApplicationDo) Where(conds ...gen.Condition) ISysApplicationDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysApplicationDo) Order(conds ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysApplicationDo) Distinct(cols ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysApplicationDo) Omit(cols ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysApplicationDo) Join(table schema.Tabler, on ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysApplicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysApplicationDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysApplicationDo) Group(cols ...field.Expr) ISysApplicationDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysApplicationDo) Having(conds ...gen.Condition) ISysApplicationDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysApplicationDo) Limit(limit int) ISysApplicationDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysApplicationDo) Offset(offset int) ISysApplicationDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysApplicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysApplicationDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysApplicationDo) Unscoped() ISysApplicationDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysApplicationDo) Create(values ...*model.SysApplication) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysApplicationDo) CreateInBatches(values []*model.SysApplication, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysApplicationDo) Save(values ...*model.SysApplication) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysApplicationDo) First() (*model.SysApplication, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysApplication), nil
	}
}

func (s sysApplicationDo) Take() (*model.SysApplication, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysApplication), nil
	}
}

func (s sysApplicationDo) Last() (*model.SysApplication, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysApplication), nil
	}
}

func (s sysApplicationDo) Find() ([]*model.SysApplication, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysApplication), err
}

func (s sysApplicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysApplication, err error) {
	buf := make([]*model.SysApplication, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysApplicationDo) FindInBatches(result *[]*model.SysApplication, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysApplicationDo) Attrs(attrs ...field.AssignExpr) ISysApplicationDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysApplicationDo) Assign(attrs ...field.AssignExpr) ISysApplicationDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysApplicationDo) Joins(fields ...field.RelationField) ISysApplicationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysApplicationDo) Preload(fields ...field.RelationField) ISysApplicationDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysApplicationDo) FirstOrInit() (*model.SysApplication, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysApplication), nil
	}
}

func (s sysApplicationDo) FirstOrCreate() (*model.SysApplication, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysApplication), nil
	}
}

func (s sysApplicationDo) FindByPage(offset int, limit int) (result []*model.SysApplication, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysApplicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysApplicationDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysApplicationDo) Delete(models ...*model.SysApplication) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysApplicationDo) withDO(do gen.Dao) *sysApplicationDo {
	s.DO = *do.(*gen.DO)
	return s
}
