// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	TAiModel           *tAiModel
	TCategoryWorkflow  *tCategoryWorkflow
	TConfig            *tConfig
	TConfigDefinition  *tConfigDefinition
	TEnv               *tEnv
	TExecution         *tExecution
	TExecutor          *tExecutor
	TProject           *tProject
	TProjectMember     *tProjectMember
	TProjectPermission *tProjectPermission
	TTeam              *tTeam
	TTeamMember        *tTeamMember
	TWorkflow          *tWorkflow
	TMcpServer         *tMcpServer
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TAiModel = &Q.TAiModel
	TCategoryWorkflow = &Q.TCategoryWorkflow
	TConfig = &Q.TConfig
	TConfigDefinition = &Q.TConfigDefinition
	TEnv = &Q.TEnv
	TExecution = &Q.TExecution
	TExecutor = &Q.TExecutor
	TProject = &Q.TProject
	TProjectMember = &Q.TProjectMember
	TProjectPermission = &Q.TProjectPermission
	TTeam = &Q.TTeam
	TTeamMember = &Q.TTeamMember
	TWorkflow = &Q.TWorkflow
	TMcpServer = &Q.TMcpServer
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		TAiModel:           newTAiModel(db, opts...),
		TCategoryWorkflow:  newTCategoryWorkflow(db, opts...),
		TConfig:            newTConfig(db, opts...),
		TConfigDefinition:  newTConfigDefinition(db, opts...),
		TEnv:               newTEnv(db, opts...),
		TExecution:         newTExecution(db, opts...),
		TExecutor:          newTExecutor(db, opts...),
		TProject:           newTProject(db, opts...),
		TProjectMember:     newTProjectMember(db, opts...),
		TProjectPermission: newTProjectPermission(db, opts...),
		TTeam:              newTTeam(db, opts...),
		TTeamMember:        newTTeamMember(db, opts...),
		TWorkflow:          newTWorkflow(db, opts...),
		TMcpServer:         newTMcpServer(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TAiModel           tAiModel
	TCategoryWorkflow  tCategoryWorkflow
	TConfig            tConfig
	TConfigDefinition  tConfigDefinition
	TEnv               tEnv
	TExecution         tExecution
	TExecutor          tExecutor
	TProject           tProject
	TProjectMember     tProjectMember
	TProjectPermission tProjectPermission
	TTeam              tTeam
	TTeamMember        tTeamMember
	TWorkflow          tWorkflow
	TMcpServer         tMcpServer
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		TAiModel:           q.TAiModel.clone(db),
		TCategoryWorkflow:  q.TCategoryWorkflow.clone(db),
		TConfig:            q.TConfig.clone(db),
		TConfigDefinition:  q.TConfigDefinition.clone(db),
		TEnv:               q.TEnv.clone(db),
		TExecution:         q.TExecution.clone(db),
		TExecutor:          q.TExecutor.clone(db),
		TProject:           q.TProject.clone(db),
		TProjectMember:     q.TProjectMember.clone(db),
		TProjectPermission: q.TProjectPermission.clone(db),
		TTeam:              q.TTeam.clone(db),
		TTeamMember:        q.TTeamMember.clone(db),
		TWorkflow:          q.TWorkflow.clone(db),
		TMcpServer:         q.TMcpServer.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		TAiModel:           q.TAiModel.replaceDB(db),
		TCategoryWorkflow:  q.TCategoryWorkflow.replaceDB(db),
		TConfig:            q.TConfig.replaceDB(db),
		TConfigDefinition:  q.TConfigDefinition.replaceDB(db),
		TEnv:               q.TEnv.replaceDB(db),
		TExecution:         q.TExecution.replaceDB(db),
		TExecutor:          q.TExecutor.replaceDB(db),
		TProject:           q.TProject.replaceDB(db),
		TProjectMember:     q.TProjectMember.replaceDB(db),
		TProjectPermission: q.TProjectPermission.replaceDB(db),
		TTeam:              q.TTeam.replaceDB(db),
		TTeamMember:        q.TTeamMember.replaceDB(db),
		TWorkflow:          q.TWorkflow.replaceDB(db),
		TMcpServer:         q.TMcpServer.replaceDB(db),
	}
}

type queryCtx struct {
	TAiModel           ITAiModelDo
	TCategoryWorkflow  ITCategoryWorkflowDo
	TConfig            ITConfigDo
	TConfigDefinition  ITConfigDefinitionDo
	TEnv               ITEnvDo
	TExecution         ITExecutionDo
	TExecutor          ITExecutorDo
	TProject           ITProjectDo
	TProjectMember     ITProjectMemberDo
	TProjectPermission ITProjectPermissionDo
	TTeam              ITTeamDo
	TTeamMember        ITTeamMemberDo
	TWorkflow          ITWorkflowDo
	TMcpServer         ITMcpServerDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TAiModel:           q.TAiModel.WithContext(ctx),
		TCategoryWorkflow:  q.TCategoryWorkflow.WithContext(ctx),
		TConfig:            q.TConfig.WithContext(ctx),
		TConfigDefinition:  q.TConfigDefinition.WithContext(ctx),
		TEnv:               q.TEnv.WithContext(ctx),
		TExecution:         q.TExecution.WithContext(ctx),
		TExecutor:          q.TExecutor.WithContext(ctx),
		TProject:           q.TProject.WithContext(ctx),
		TProjectMember:     q.TProjectMember.WithContext(ctx),
		TProjectPermission: q.TProjectPermission.WithContext(ctx),
		TTeam:              q.TTeam.WithContext(ctx),
		TTeamMember:        q.TTeamMember.WithContext(ctx),
		TWorkflow:          q.TWorkflow.WithContext(ctx),
		TMcpServer:         q.TMcpServer.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
