// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	TCategoryWorkflow  *tCategoryWorkflow
	TDatabaseConfig    *tDatabaseConfig
	TEnv               *tEnv
	TExecution         *tExecution
	TExecutor          *tExecutor
	TMqConfig          *tMqConfig
	TProject           *tProject
	TProjectMember     *tProjectMember
	TProjectPermission *tProjectPermission
	TTeam              *tTeam
	TTeamMember        *tTeamMember
	TWorkflow          *tWorkflow
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TCategoryWorkflow = &Q.TCategoryWorkflow
	TDatabaseConfig = &Q.TDatabaseConfig
	TEnv = &Q.TEnv
	TExecution = &Q.TExecution
	TExecutor = &Q.TExecutor
	TMqConfig = &Q.TMqConfig
	TProject = &Q.TProject
	TProjectMember = &Q.TProjectMember
	TProjectPermission = &Q.TProjectPermission
	TTeam = &Q.TTeam
	TTeamMember = &Q.TTeamMember
	TWorkflow = &Q.TWorkflow
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		TCategoryWorkflow:  newTCategoryWorkflow(db, opts...),
		TDatabaseConfig:    newTDatabaseConfig(db, opts...),
		TEnv:               newTEnv(db, opts...),
		TExecution:         newTExecution(db, opts...),
		TExecutor:          newTExecutor(db, opts...),
		TMqConfig:          newTMqConfig(db, opts...),
		TProject:           newTProject(db, opts...),
		TProjectMember:     newTProjectMember(db, opts...),
		TProjectPermission: newTProjectPermission(db, opts...),
		TTeam:              newTTeam(db, opts...),
		TTeamMember:        newTTeamMember(db, opts...),
		TWorkflow:          newTWorkflow(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TCategoryWorkflow  tCategoryWorkflow
	TDatabaseConfig    tDatabaseConfig
	TEnv               tEnv
	TExecution         tExecution
	TExecutor          tExecutor
	TMqConfig          tMqConfig
	TProject           tProject
	TProjectMember     tProjectMember
	TProjectPermission tProjectPermission
	TTeam              tTeam
	TTeamMember        tTeamMember
	TWorkflow          tWorkflow
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		TCategoryWorkflow:  q.TCategoryWorkflow.clone(db),
		TDatabaseConfig:    q.TDatabaseConfig.clone(db),
		TEnv:               q.TEnv.clone(db),
		TExecution:         q.TExecution.clone(db),
		TExecutor:          q.TExecutor.clone(db),
		TMqConfig:          q.TMqConfig.clone(db),
		TProject:           q.TProject.clone(db),
		TProjectMember:     q.TProjectMember.clone(db),
		TProjectPermission: q.TProjectPermission.clone(db),
		TTeam:              q.TTeam.clone(db),
		TTeamMember:        q.TTeamMember.clone(db),
		TWorkflow:          q.TWorkflow.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		TCategoryWorkflow:  q.TCategoryWorkflow.replaceDB(db),
		TDatabaseConfig:    q.TDatabaseConfig.replaceDB(db),
		TEnv:               q.TEnv.replaceDB(db),
		TExecution:         q.TExecution.replaceDB(db),
		TExecutor:          q.TExecutor.replaceDB(db),
		TMqConfig:          q.TMqConfig.replaceDB(db),
		TProject:           q.TProject.replaceDB(db),
		TProjectMember:     q.TProjectMember.replaceDB(db),
		TProjectPermission: q.TProjectPermission.replaceDB(db),
		TTeam:              q.TTeam.replaceDB(db),
		TTeamMember:        q.TTeamMember.replaceDB(db),
		TWorkflow:          q.TWorkflow.replaceDB(db),
	}
}

type queryCtx struct {
	TCategoryWorkflow  ITCategoryWorkflowDo
	TDatabaseConfig    ITDatabaseConfigDo
	TEnv               ITEnvDo
	TExecution         ITExecutionDo
	TExecutor          ITExecutorDo
	TMqConfig          ITMqConfigDo
	TProject           ITProjectDo
	TProjectMember     ITProjectMemberDo
	TProjectPermission ITProjectPermissionDo
	TTeam              ITTeamDo
	TTeamMember        ITTeamMemberDo
	TWorkflow          ITWorkflowDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TCategoryWorkflow:  q.TCategoryWorkflow.WithContext(ctx),
		TDatabaseConfig:    q.TDatabaseConfig.WithContext(ctx),
		TEnv:               q.TEnv.WithContext(ctx),
		TExecution:         q.TExecution.WithContext(ctx),
		TExecutor:          q.TExecutor.WithContext(ctx),
		TMqConfig:          q.TMqConfig.WithContext(ctx),
		TProject:           q.TProject.WithContext(ctx),
		TProjectMember:     q.TProjectMember.WithContext(ctx),
		TProjectPermission: q.TProjectPermission.WithContext(ctx),
		TTeam:              q.TTeam.WithContext(ctx),
		TTeamMember:        q.TTeamMember.WithContext(ctx),
		TWorkflow:          q.TWorkflow.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
