// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTAiConversation(db *gorm.DB, opts ...gen.DOOption) tAiConversation {
	_tAiConversation := tAiConversation{}

	_tAiConversation.tAiConversationDo.UseDB(db, opts...)
	_tAiConversation.tAiConversationDo.UseModel(&model.TAiConversation{})

	tableName := _tAiConversation.tAiConversationDo.TableName()
	_tAiConversation.ALL = field.NewAsterisk(tableName)
	_tAiConversation.ID = field.NewInt64(tableName, "id")
	_tAiConversation.WorkflowID = field.NewInt64(tableName, "workflow_id")
	_tAiConversation.Title = field.NewString(tableName, "title")
	_tAiConversation.Variables = field.NewString(tableName, "variables")
	_tAiConversation.CreatedAt = field.NewTime(tableName, "created_at")
	_tAiConversation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tAiConversation.CreatedBy = field.NewInt64(tableName, "created_by")

	_tAiConversation.fillFieldMap()

	return _tAiConversation
}

type tAiConversation struct {
	tAiConversationDo tAiConversationDo

	ALL        field.Asterisk
	ID         field.Int64
	WorkflowID field.Int64  // 关联的工作流ID
	Title      field.String // 会话标题
	Variables  field.String // 会话级变量
	CreatedAt  field.Time
	UpdatedAt  field.Time
	CreatedBy  field.Int64 // 创建人ID

	fieldMap map[string]field.Expr
}

func (t tAiConversation) Table(newTableName string) *tAiConversation {
	t.tAiConversationDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tAiConversation) As(alias string) *tAiConversation {
	t.tAiConversationDo.DO = *(t.tAiConversationDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tAiConversation) updateTableName(table string) *tAiConversation {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.WorkflowID = field.NewInt64(table, "workflow_id")
	t.Title = field.NewString(table, "title")
	t.Variables = field.NewString(table, "variables")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.CreatedBy = field.NewInt64(table, "created_by")

	t.fillFieldMap()

	return t
}

func (t *tAiConversation) WithContext(ctx context.Context) ITAiConversationDo {
	return t.tAiConversationDo.WithContext(ctx)
}

func (t tAiConversation) TableName() string { return t.tAiConversationDo.TableName() }

func (t tAiConversation) Alias() string { return t.tAiConversationDo.Alias() }

func (t tAiConversation) Columns(cols ...field.Expr) gen.Columns {
	return t.tAiConversationDo.Columns(cols...)
}

func (t *tAiConversation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tAiConversation) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["id"] = t.ID
	t.fieldMap["workflow_id"] = t.WorkflowID
	t.fieldMap["title"] = t.Title
	t.fieldMap["variables"] = t.Variables
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["created_by"] = t.CreatedBy
}

func (t tAiConversation) clone(db *gorm.DB) tAiConversation {
	t.tAiConversationDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tAiConversation) replaceDB(db *gorm.DB) tAiConversation {
	t.tAiConversationDo.ReplaceDB(db)
	return t
}

type tAiConversationDo struct{ gen.DO }

type ITAiConversationDo interface {
	gen.SubQuery
	Debug() ITAiConversationDo
	WithContext(ctx context.Context) ITAiConversationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITAiConversationDo
	WriteDB() ITAiConversationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITAiConversationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITAiConversationDo
	Not(conds ...gen.Condition) ITAiConversationDo
	Or(conds ...gen.Condition) ITAiConversationDo
	Select(conds ...field.Expr) ITAiConversationDo
	Where(conds ...gen.Condition) ITAiConversationDo
	Order(conds ...field.Expr) ITAiConversationDo
	Distinct(cols ...field.Expr) ITAiConversationDo
	Omit(cols ...field.Expr) ITAiConversationDo
	Join(table schema.Tabler, on ...field.Expr) ITAiConversationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITAiConversationDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITAiConversationDo
	Group(cols ...field.Expr) ITAiConversationDo
	Having(conds ...gen.Condition) ITAiConversationDo
	Limit(limit int) ITAiConversationDo
	Offset(offset int) ITAiConversationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITAiConversationDo
	Unscoped() ITAiConversationDo
	Create(values ...*model.TAiConversation) error
	CreateInBatches(values []*model.TAiConversation, batchSize int) error
	Save(values ...*model.TAiConversation) error
	First() (*model.TAiConversation, error)
	Take() (*model.TAiConversation, error)
	Last() (*model.TAiConversation, error)
	Find() ([]*model.TAiConversation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TAiConversation, err error)
	FindInBatches(result *[]*model.TAiConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TAiConversation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITAiConversationDo
	Assign(attrs ...field.AssignExpr) ITAiConversationDo
	Joins(fields ...field.RelationField) ITAiConversationDo
	Preload(fields ...field.RelationField) ITAiConversationDo
	FirstOrInit() (*model.TAiConversation, error)
	FirstOrCreate() (*model.TAiConversation, error)
	FindByPage(offset int, limit int) (result []*model.TAiConversation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITAiConversationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tAiConversationDo) Debug() ITAiConversationDo {
	return t.withDO(t.DO.Debug())
}

func (t tAiConversationDo) WithContext(ctx context.Context) ITAiConversationDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tAiConversationDo) ReadDB() ITAiConversationDo {
	return t.Clauses(dbresolver.Read)
}

func (t tAiConversationDo) WriteDB() ITAiConversationDo {
	return t.Clauses(dbresolver.Write)
}

func (t tAiConversationDo) Session(config *gorm.Session) ITAiConversationDo {
	return t.withDO(t.DO.Session(config))
}

func (t tAiConversationDo) Clauses(conds ...clause.Expression) ITAiConversationDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tAiConversationDo) Returning(value interface{}, columns ...string) ITAiConversationDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tAiConversationDo) Not(conds ...gen.Condition) ITAiConversationDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tAiConversationDo) Or(conds ...gen.Condition) ITAiConversationDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tAiConversationDo) Select(conds ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tAiConversationDo) Where(conds ...gen.Condition) ITAiConversationDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tAiConversationDo) Order(conds ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tAiConversationDo) Distinct(cols ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tAiConversationDo) Omit(cols ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tAiConversationDo) Join(table schema.Tabler, on ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tAiConversationDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tAiConversationDo) RightJoin(table schema.Tabler, on ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tAiConversationDo) Group(cols ...field.Expr) ITAiConversationDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tAiConversationDo) Having(conds ...gen.Condition) ITAiConversationDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tAiConversationDo) Limit(limit int) ITAiConversationDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tAiConversationDo) Offset(offset int) ITAiConversationDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tAiConversationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITAiConversationDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tAiConversationDo) Unscoped() ITAiConversationDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tAiConversationDo) Create(values ...*model.TAiConversation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tAiConversationDo) CreateInBatches(values []*model.TAiConversation, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

func (t tAiConversationDo) Save(values ...*model.TAiConversation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tAiConversationDo) First() (*model.TAiConversation, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TAiConversation), nil
	}
}

func (t tAiConversationDo) Take() (*model.TAiConversation, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TAiConversation), nil
	}
}

func (t tAiConversationDo) Last() (*model.TAiConversation, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TAiConversation), nil
	}
}

func (t tAiConversationDo) Find() ([]*model.TAiConversation, error) {
	result, err := t.DO.Find()
	return result.([]*model.TAiConversation), err
}

func (t tAiConversationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TAiConversation, err error) {
	buf := make([]*model.TAiConversation, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tAiConversationDo) FindInBatches(result *[]*model.TAiConversation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tAiConversationDo) Attrs(attrs ...field.AssignExpr) ITAiConversationDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tAiConversationDo) Assign(attrs ...field.AssignExpr) ITAiConversationDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tAiConversationDo) Joins(fields ...field.RelationField) ITAiConversationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tAiConversationDo) Preload(fields ...field.RelationField) ITAiConversationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tAiConversationDo) FirstOrInit() (*model.TAiConversation, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TAiConversation), nil
	}
}

func (t tAiConversationDo) FirstOrCreate() (*model.TAiConversation, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TAiConversation), nil
	}
}

func (t tAiConversationDo) FindByPage(offset int, limit int) (result []*model.TAiConversation, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tAiConversationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tAiConversationDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tAiConversationDo) Delete(models ...*model.TAiConversation) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tAiConversationDo) withDO(do gen.Dao) *tAiConversationDo {
	t.DO = *do.(*gen.DO)
	return t
}
