// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTCategoryWorkflow(db *gorm.DB, opts ...gen.DOOption) tCategoryWorkflow {
	_tCategoryWorkflow := tCategoryWorkflow{}

	_tCategoryWorkflow.tCategoryWorkflowDo.UseDB(db, opts...)
	_tCategoryWorkflow.tCategoryWorkflowDo.UseModel(&model.TCategoryWorkflow{})

	tableName := _tCategoryWorkflow.tCategoryWorkflowDo.TableName()
	_tCategoryWorkflow.ALL = field.NewAsterisk(tableName)
	_tCategoryWorkflow.ID = field.NewInt64(tableName, "id")
	_tCategoryWorkflow.CreatedAt = field.NewTime(tableName, "created_at")
	_tCategoryWorkflow.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tCategoryWorkflow.IsDelete = field.NewBool(tableName, "is_delete")
	_tCategoryWorkflow.ProjectID = field.NewInt64(tableName, "project_id")
	_tCategoryWorkflow.ParentID = field.NewInt64(tableName, "parent_id")
	_tCategoryWorkflow.Name = field.NewString(tableName, "name")
	_tCategoryWorkflow.Type = field.NewString(tableName, "type")
	_tCategoryWorkflow.SourceID = field.NewInt64(tableName, "source_id")
	_tCategoryWorkflow.Sort = field.NewInt32(tableName, "sort")

	_tCategoryWorkflow.fillFieldMap()

	return _tCategoryWorkflow
}

// tCategoryWorkflow 工作流分类表
type tCategoryWorkflow struct {
	tCategoryWorkflowDo tCategoryWorkflowDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	IsDelete  field.Bool
	ProjectID field.Int64  // 项目ID
	ParentID  field.Int64  // 父分类ID，0表示根节点
	Name      field.String // 分类名称
	Type      field.String // 类型: folder/workflow
	SourceID  field.Int64  // 关联的工作流ID，type=workflow时有值
	Sort      field.Int32  // 排序

	fieldMap map[string]field.Expr
}

func (t tCategoryWorkflow) Table(newTableName string) *tCategoryWorkflow {
	t.tCategoryWorkflowDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tCategoryWorkflow) As(alias string) *tCategoryWorkflow {
	t.tCategoryWorkflowDo.DO = *(t.tCategoryWorkflowDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tCategoryWorkflow) updateTableName(table string) *tCategoryWorkflow {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.ParentID = field.NewInt64(table, "parent_id")
	t.Name = field.NewString(table, "name")
	t.Type = field.NewString(table, "type")
	t.SourceID = field.NewInt64(table, "source_id")
	t.Sort = field.NewInt32(table, "sort")

	t.fillFieldMap()

	return t
}

func (t *tCategoryWorkflow) WithContext(ctx context.Context) ITCategoryWorkflowDo {
	return t.tCategoryWorkflowDo.WithContext(ctx)
}

func (t tCategoryWorkflow) TableName() string { return t.tCategoryWorkflowDo.TableName() }

func (t tCategoryWorkflow) Alias() string { return t.tCategoryWorkflowDo.Alias() }

func (t tCategoryWorkflow) Columns(cols ...field.Expr) gen.Columns {
	return t.tCategoryWorkflowDo.Columns(cols...)
}

func (t *tCategoryWorkflow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tCategoryWorkflow) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["parent_id"] = t.ParentID
	t.fieldMap["name"] = t.Name
	t.fieldMap["type"] = t.Type
	t.fieldMap["source_id"] = t.SourceID
	t.fieldMap["sort"] = t.Sort
}

func (t tCategoryWorkflow) clone(db *gorm.DB) tCategoryWorkflow {
	t.tCategoryWorkflowDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tCategoryWorkflow) replaceDB(db *gorm.DB) tCategoryWorkflow {
	t.tCategoryWorkflowDo.ReplaceDB(db)
	return t
}

type tCategoryWorkflowDo struct{ gen.DO }

type ITCategoryWorkflowDo interface {
	gen.SubQuery
	Debug() ITCategoryWorkflowDo
	WithContext(ctx context.Context) ITCategoryWorkflowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITCategoryWorkflowDo
	WriteDB() ITCategoryWorkflowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITCategoryWorkflowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITCategoryWorkflowDo
	Not(conds ...gen.Condition) ITCategoryWorkflowDo
	Or(conds ...gen.Condition) ITCategoryWorkflowDo
	Select(conds ...field.Expr) ITCategoryWorkflowDo
	Where(conds ...gen.Condition) ITCategoryWorkflowDo
	Order(conds ...field.Expr) ITCategoryWorkflowDo
	Distinct(cols ...field.Expr) ITCategoryWorkflowDo
	Omit(cols ...field.Expr) ITCategoryWorkflowDo
	Join(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo
	Group(cols ...field.Expr) ITCategoryWorkflowDo
	Having(conds ...gen.Condition) ITCategoryWorkflowDo
	Limit(limit int) ITCategoryWorkflowDo
	Offset(offset int) ITCategoryWorkflowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITCategoryWorkflowDo
	Unscoped() ITCategoryWorkflowDo
	Create(values ...*model.TCategoryWorkflow) error
	CreateInBatches(values []*model.TCategoryWorkflow, batchSize int) error
	Save(values ...*model.TCategoryWorkflow) error
	First() (*model.TCategoryWorkflow, error)
	Take() (*model.TCategoryWorkflow, error)
	Last() (*model.TCategoryWorkflow, error)
	Find() ([]*model.TCategoryWorkflow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TCategoryWorkflow, err error)
	FindInBatches(result *[]*model.TCategoryWorkflow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TCategoryWorkflow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITCategoryWorkflowDo
	Assign(attrs ...field.AssignExpr) ITCategoryWorkflowDo
	Joins(fields ...field.RelationField) ITCategoryWorkflowDo
	Preload(fields ...field.RelationField) ITCategoryWorkflowDo
	FirstOrInit() (*model.TCategoryWorkflow, error)
	FirstOrCreate() (*model.TCategoryWorkflow, error)
	FindByPage(offset int, limit int) (result []*model.TCategoryWorkflow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITCategoryWorkflowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tCategoryWorkflowDo) Debug() ITCategoryWorkflowDo {
	return t.withDO(t.DO.Debug())
}

func (t tCategoryWorkflowDo) WithContext(ctx context.Context) ITCategoryWorkflowDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tCategoryWorkflowDo) ReadDB() ITCategoryWorkflowDo {
	return t.Clauses(dbresolver.Read)
}

func (t tCategoryWorkflowDo) WriteDB() ITCategoryWorkflowDo {
	return t.Clauses(dbresolver.Write)
}

func (t tCategoryWorkflowDo) Session(config *gorm.Session) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Session(config))
}

func (t tCategoryWorkflowDo) Clauses(conds ...clause.Expression) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tCategoryWorkflowDo) Returning(value interface{}, columns ...string) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tCategoryWorkflowDo) Not(conds ...gen.Condition) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tCategoryWorkflowDo) Or(conds ...gen.Condition) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tCategoryWorkflowDo) Select(conds ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tCategoryWorkflowDo) Where(conds ...gen.Condition) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tCategoryWorkflowDo) Order(conds ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tCategoryWorkflowDo) Distinct(cols ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tCategoryWorkflowDo) Omit(cols ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tCategoryWorkflowDo) Join(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tCategoryWorkflowDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tCategoryWorkflowDo) RightJoin(table schema.Tabler, on ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tCategoryWorkflowDo) Group(cols ...field.Expr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tCategoryWorkflowDo) Having(conds ...gen.Condition) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tCategoryWorkflowDo) Limit(limit int) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tCategoryWorkflowDo) Offset(offset int) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tCategoryWorkflowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tCategoryWorkflowDo) Unscoped() ITCategoryWorkflowDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tCategoryWorkflowDo) Create(values ...*model.TCategoryWorkflow) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tCategoryWorkflowDo) CreateInBatches(values []*model.TCategoryWorkflow, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tCategoryWorkflowDo) Save(values ...*model.TCategoryWorkflow) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tCategoryWorkflowDo) First() (*model.TCategoryWorkflow, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategoryWorkflow), nil
	}
}

func (t tCategoryWorkflowDo) Take() (*model.TCategoryWorkflow, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategoryWorkflow), nil
	}
}

func (t tCategoryWorkflowDo) Last() (*model.TCategoryWorkflow, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategoryWorkflow), nil
	}
}

func (t tCategoryWorkflowDo) Find() ([]*model.TCategoryWorkflow, error) {
	result, err := t.DO.Find()
	return result.([]*model.TCategoryWorkflow), err
}

func (t tCategoryWorkflowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TCategoryWorkflow, err error) {
	buf := make([]*model.TCategoryWorkflow, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tCategoryWorkflowDo) FindInBatches(result *[]*model.TCategoryWorkflow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tCategoryWorkflowDo) Attrs(attrs ...field.AssignExpr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tCategoryWorkflowDo) Assign(attrs ...field.AssignExpr) ITCategoryWorkflowDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tCategoryWorkflowDo) Joins(fields ...field.RelationField) ITCategoryWorkflowDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tCategoryWorkflowDo) Preload(fields ...field.RelationField) ITCategoryWorkflowDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tCategoryWorkflowDo) FirstOrInit() (*model.TCategoryWorkflow, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategoryWorkflow), nil
	}
}

func (t tCategoryWorkflowDo) FirstOrCreate() (*model.TCategoryWorkflow, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TCategoryWorkflow), nil
	}
}

func (t tCategoryWorkflowDo) FindByPage(offset int, limit int) (result []*model.TCategoryWorkflow, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tCategoryWorkflowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tCategoryWorkflowDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tCategoryWorkflowDo) Delete(models ...*model.TCategoryWorkflow) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tCategoryWorkflowDo) withDO(do gen.Dao) *tCategoryWorkflowDo {
	t.DO = *do.(*gen.DO)
	return t
}
