// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTConfigDefinition(db *gorm.DB, opts ...gen.DOOption) tConfigDefinition {
	_tConfigDefinition := tConfigDefinition{}

	_tConfigDefinition.tConfigDefinitionDo.UseDB(db, opts...)
	_tConfigDefinition.tConfigDefinitionDo.UseModel(&model.TConfigDefinition{})

	tableName := _tConfigDefinition.tConfigDefinitionDo.TableName()
	_tConfigDefinition.ALL = field.NewAsterisk(tableName)
	_tConfigDefinition.ID = field.NewInt64(tableName, "id")
	_tConfigDefinition.CreatedAt = field.NewTime(tableName, "created_at")
	_tConfigDefinition.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tConfigDefinition.IsDelete = field.NewBool(tableName, "is_delete")
	_tConfigDefinition.ProjectID = field.NewInt64(tableName, "project_id")
	_tConfigDefinition.Type = field.NewString(tableName, "type")
	_tConfigDefinition.Code = field.NewString(tableName, "code")
	_tConfigDefinition.Name = field.NewString(tableName, "name")
	_tConfigDefinition.Description = field.NewString(tableName, "description")
	_tConfigDefinition.Extra = field.NewString(tableName, "extra")
	_tConfigDefinition.Sort = field.NewInt32(tableName, "sort")
	_tConfigDefinition.Status = field.NewInt32(tableName, "status")

	_tConfigDefinition.fillFieldMap()

	return _tConfigDefinition
}

// tConfigDefinition 配置定义表
type tConfigDefinition struct {
	tConfigDefinitionDo tConfigDefinitionDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	ProjectID   field.Int64  // 项目ID
	Type        field.String // 配置类型: domain/variable/database/mq
	Code        field.String // 系统生成的唯一ID
	Name        field.String // 显示名称
	Description field.String // 描述
	Extra       field.String // 类型特有属性
	Sort        field.Int32  // 排序
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tConfigDefinition) Table(newTableName string) *tConfigDefinition {
	t.tConfigDefinitionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tConfigDefinition) As(alias string) *tConfigDefinition {
	t.tConfigDefinitionDo.DO = *(t.tConfigDefinitionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tConfigDefinition) updateTableName(table string) *tConfigDefinition {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.Type = field.NewString(table, "type")
	t.Code = field.NewString(table, "code")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Extra = field.NewString(table, "extra")
	t.Sort = field.NewInt32(table, "sort")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tConfigDefinition) WithContext(ctx context.Context) ITConfigDefinitionDo {
	return t.tConfigDefinitionDo.WithContext(ctx)
}

func (t tConfigDefinition) TableName() string { return t.tConfigDefinitionDo.TableName() }

func (t tConfigDefinition) Alias() string { return t.tConfigDefinitionDo.Alias() }

func (t tConfigDefinition) Columns(cols ...field.Expr) gen.Columns {
	return t.tConfigDefinitionDo.Columns(cols...)
}

func (t *tConfigDefinition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tConfigDefinition) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["type"] = t.Type
	t.fieldMap["code"] = t.Code
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["extra"] = t.Extra
	t.fieldMap["sort"] = t.Sort
	t.fieldMap["status"] = t.Status
}

func (t tConfigDefinition) clone(db *gorm.DB) tConfigDefinition {
	t.tConfigDefinitionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tConfigDefinition) replaceDB(db *gorm.DB) tConfigDefinition {
	t.tConfigDefinitionDo.ReplaceDB(db)
	return t
}

type tConfigDefinitionDo struct{ gen.DO }

type ITConfigDefinitionDo interface {
	gen.SubQuery
	Debug() ITConfigDefinitionDo
	WithContext(ctx context.Context) ITConfigDefinitionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITConfigDefinitionDo
	WriteDB() ITConfigDefinitionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITConfigDefinitionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITConfigDefinitionDo
	Not(conds ...gen.Condition) ITConfigDefinitionDo
	Or(conds ...gen.Condition) ITConfigDefinitionDo
	Select(conds ...field.Expr) ITConfigDefinitionDo
	Where(conds ...gen.Condition) ITConfigDefinitionDo
	Order(conds ...field.Expr) ITConfigDefinitionDo
	Distinct(cols ...field.Expr) ITConfigDefinitionDo
	Omit(cols ...field.Expr) ITConfigDefinitionDo
	Join(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo
	Group(cols ...field.Expr) ITConfigDefinitionDo
	Having(conds ...gen.Condition) ITConfigDefinitionDo
	Limit(limit int) ITConfigDefinitionDo
	Offset(offset int) ITConfigDefinitionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITConfigDefinitionDo
	Unscoped() ITConfigDefinitionDo
	Create(values ...*model.TConfigDefinition) error
	CreateInBatches(values []*model.TConfigDefinition, batchSize int) error
	Save(values ...*model.TConfigDefinition) error
	First() (*model.TConfigDefinition, error)
	Take() (*model.TConfigDefinition, error)
	Last() (*model.TConfigDefinition, error)
	Find() ([]*model.TConfigDefinition, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TConfigDefinition, err error)
	FindInBatches(result *[]*model.TConfigDefinition, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TConfigDefinition) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITConfigDefinitionDo
	Assign(attrs ...field.AssignExpr) ITConfigDefinitionDo
	Joins(fields ...field.RelationField) ITConfigDefinitionDo
	Preload(fields ...field.RelationField) ITConfigDefinitionDo
	FirstOrInit() (*model.TConfigDefinition, error)
	FirstOrCreate() (*model.TConfigDefinition, error)
	FindByPage(offset int, limit int) (result []*model.TConfigDefinition, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITConfigDefinitionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tConfigDefinitionDo) Debug() ITConfigDefinitionDo {
	return t.withDO(t.DO.Debug())
}

func (t tConfigDefinitionDo) WithContext(ctx context.Context) ITConfigDefinitionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tConfigDefinitionDo) ReadDB() ITConfigDefinitionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tConfigDefinitionDo) WriteDB() ITConfigDefinitionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tConfigDefinitionDo) Session(config *gorm.Session) ITConfigDefinitionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tConfigDefinitionDo) Clauses(conds ...clause.Expression) ITConfigDefinitionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tConfigDefinitionDo) Returning(value interface{}, columns ...string) ITConfigDefinitionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tConfigDefinitionDo) Not(conds ...gen.Condition) ITConfigDefinitionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tConfigDefinitionDo) Or(conds ...gen.Condition) ITConfigDefinitionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tConfigDefinitionDo) Select(conds ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tConfigDefinitionDo) Where(conds ...gen.Condition) ITConfigDefinitionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tConfigDefinitionDo) Order(conds ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tConfigDefinitionDo) Distinct(cols ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tConfigDefinitionDo) Omit(cols ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tConfigDefinitionDo) Join(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tConfigDefinitionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tConfigDefinitionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tConfigDefinitionDo) Group(cols ...field.Expr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tConfigDefinitionDo) Having(conds ...gen.Condition) ITConfigDefinitionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tConfigDefinitionDo) Limit(limit int) ITConfigDefinitionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tConfigDefinitionDo) Offset(offset int) ITConfigDefinitionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tConfigDefinitionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITConfigDefinitionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tConfigDefinitionDo) Unscoped() ITConfigDefinitionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tConfigDefinitionDo) Create(values ...*model.TConfigDefinition) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tConfigDefinitionDo) CreateInBatches(values []*model.TConfigDefinition, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tConfigDefinitionDo) Save(values ...*model.TConfigDefinition) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tConfigDefinitionDo) First() (*model.TConfigDefinition, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TConfigDefinition), nil
	}
}

func (t tConfigDefinitionDo) Take() (*model.TConfigDefinition, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TConfigDefinition), nil
	}
}

func (t tConfigDefinitionDo) Last() (*model.TConfigDefinition, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TConfigDefinition), nil
	}
}

func (t tConfigDefinitionDo) Find() ([]*model.TConfigDefinition, error) {
	result, err := t.DO.Find()
	return result.([]*model.TConfigDefinition), err
}

func (t tConfigDefinitionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TConfigDefinition, err error) {
	buf := make([]*model.TConfigDefinition, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tConfigDefinitionDo) FindInBatches(result *[]*model.TConfigDefinition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tConfigDefinitionDo) Attrs(attrs ...field.AssignExpr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tConfigDefinitionDo) Assign(attrs ...field.AssignExpr) ITConfigDefinitionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tConfigDefinitionDo) Joins(fields ...field.RelationField) ITConfigDefinitionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tConfigDefinitionDo) Preload(fields ...field.RelationField) ITConfigDefinitionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tConfigDefinitionDo) FirstOrInit() (*model.TConfigDefinition, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TConfigDefinition), nil
	}
}

func (t tConfigDefinitionDo) FirstOrCreate() (*model.TConfigDefinition, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TConfigDefinition), nil
	}
}

func (t tConfigDefinitionDo) FindByPage(offset int, limit int) (result []*model.TConfigDefinition, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tConfigDefinitionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tConfigDefinitionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tConfigDefinitionDo) Delete(models ...*model.TConfigDefinition) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tConfigDefinitionDo) withDO(do gen.Dao) *tConfigDefinitionDo {
	t.DO = *do.(*gen.DO)
	return t
}
