// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTDomain(db *gorm.DB, opts ...gen.DOOption) tDomain {
	_tDomain := tDomain{}

	_tDomain.tDomainDo.UseDB(db, opts...)
	_tDomain.tDomainDo.UseModel(&model.TDomain{})

	tableName := _tDomain.tDomainDo.TableName()
	_tDomain.ALL = field.NewAsterisk(tableName)
	_tDomain.ID = field.NewInt64(tableName, "id")
	_tDomain.CreatedAt = field.NewTime(tableName, "created_at")
	_tDomain.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tDomain.IsDelete = field.NewBool(tableName, "is_delete")
	_tDomain.ProjectID = field.NewInt64(tableName, "project_id")
	_tDomain.EnvID = field.NewInt64(tableName, "env_id")
	_tDomain.Name = field.NewString(tableName, "name")
	_tDomain.Code = field.NewString(tableName, "code")
	_tDomain.BaseURL = field.NewString(tableName, "base_url")
	_tDomain.Headers = field.NewString(tableName, "headers")
	_tDomain.Description = field.NewString(tableName, "description")
	_tDomain.Sort = field.NewInt64(tableName, "sort")
	_tDomain.Status = field.NewInt32(tableName, "status")

	_tDomain.fillFieldMap()

	return _tDomain
}

// tDomain 域名表
type tDomain struct {
	tDomainDo tDomainDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	ProjectID   field.Int64  // 所属项目ID
	EnvID       field.Int64  // 所属环境ID
	Name        field.String // 域名名称
	Code        field.String // 域名代码，用于工作流中引用
	BaseURL     field.String // 基础URL
	Headers     field.String // 公共请求头 [{"key":"xxx","value":"xxx"}]
	Description field.String // 描述
	Sort        field.Int64  // 排序
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tDomain) Table(newTableName string) *tDomain {
	t.tDomainDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tDomain) As(alias string) *tDomain {
	t.tDomainDo.DO = *(t.tDomainDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tDomain) updateTableName(table string) *tDomain {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.EnvID = field.NewInt64(table, "env_id")
	t.Name = field.NewString(table, "name")
	t.Code = field.NewString(table, "code")
	t.BaseURL = field.NewString(table, "base_url")
	t.Headers = field.NewString(table, "headers")
	t.Description = field.NewString(table, "description")
	t.Sort = field.NewInt64(table, "sort")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tDomain) WithContext(ctx context.Context) ITDomainDo { return t.tDomainDo.WithContext(ctx) }

func (t tDomain) TableName() string { return t.tDomainDo.TableName() }

func (t tDomain) Alias() string { return t.tDomainDo.Alias() }

func (t tDomain) Columns(cols ...field.Expr) gen.Columns { return t.tDomainDo.Columns(cols...) }

func (t *tDomain) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tDomain) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["env_id"] = t.EnvID
	t.fieldMap["name"] = t.Name
	t.fieldMap["code"] = t.Code
	t.fieldMap["base_url"] = t.BaseURL
	t.fieldMap["headers"] = t.Headers
	t.fieldMap["description"] = t.Description
	t.fieldMap["sort"] = t.Sort
	t.fieldMap["status"] = t.Status
}

func (t tDomain) clone(db *gorm.DB) tDomain {
	t.tDomainDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tDomain) replaceDB(db *gorm.DB) tDomain {
	t.tDomainDo.ReplaceDB(db)
	return t
}

type tDomainDo struct{ gen.DO }

type ITDomainDo interface {
	gen.SubQuery
	Debug() ITDomainDo
	WithContext(ctx context.Context) ITDomainDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITDomainDo
	WriteDB() ITDomainDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITDomainDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITDomainDo
	Not(conds ...gen.Condition) ITDomainDo
	Or(conds ...gen.Condition) ITDomainDo
	Select(conds ...field.Expr) ITDomainDo
	Where(conds ...gen.Condition) ITDomainDo
	Order(conds ...field.Expr) ITDomainDo
	Distinct(cols ...field.Expr) ITDomainDo
	Omit(cols ...field.Expr) ITDomainDo
	Join(table schema.Tabler, on ...field.Expr) ITDomainDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITDomainDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITDomainDo
	Group(cols ...field.Expr) ITDomainDo
	Having(conds ...gen.Condition) ITDomainDo
	Limit(limit int) ITDomainDo
	Offset(offset int) ITDomainDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITDomainDo
	Unscoped() ITDomainDo
	Create(values ...*model.TDomain) error
	CreateInBatches(values []*model.TDomain, batchSize int) error
	Save(values ...*model.TDomain) error
	First() (*model.TDomain, error)
	Take() (*model.TDomain, error)
	Last() (*model.TDomain, error)
	Find() ([]*model.TDomain, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDomain, err error)
	FindInBatches(result *[]*model.TDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TDomain) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITDomainDo
	Assign(attrs ...field.AssignExpr) ITDomainDo
	Joins(fields ...field.RelationField) ITDomainDo
	Preload(fields ...field.RelationField) ITDomainDo
	FirstOrInit() (*model.TDomain, error)
	FirstOrCreate() (*model.TDomain, error)
	FindByPage(offset int, limit int) (result []*model.TDomain, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITDomainDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tDomainDo) Debug() ITDomainDo {
	return t.withDO(t.DO.Debug())
}

func (t tDomainDo) WithContext(ctx context.Context) ITDomainDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tDomainDo) ReadDB() ITDomainDo {
	return t.Clauses(dbresolver.Read)
}

func (t tDomainDo) WriteDB() ITDomainDo {
	return t.Clauses(dbresolver.Write)
}

func (t tDomainDo) Session(config *gorm.Session) ITDomainDo {
	return t.withDO(t.DO.Session(config))
}

func (t tDomainDo) Clauses(conds ...clause.Expression) ITDomainDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tDomainDo) Returning(value interface{}, columns ...string) ITDomainDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tDomainDo) Not(conds ...gen.Condition) ITDomainDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tDomainDo) Or(conds ...gen.Condition) ITDomainDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tDomainDo) Select(conds ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tDomainDo) Where(conds ...gen.Condition) ITDomainDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tDomainDo) Order(conds ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tDomainDo) Distinct(cols ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tDomainDo) Omit(cols ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tDomainDo) Join(table schema.Tabler, on ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tDomainDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tDomainDo) RightJoin(table schema.Tabler, on ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tDomainDo) Group(cols ...field.Expr) ITDomainDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tDomainDo) Having(conds ...gen.Condition) ITDomainDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tDomainDo) Limit(limit int) ITDomainDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tDomainDo) Offset(offset int) ITDomainDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tDomainDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITDomainDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tDomainDo) Unscoped() ITDomainDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tDomainDo) Create(values ...*model.TDomain) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tDomainDo) CreateInBatches(values []*model.TDomain, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tDomainDo) Save(values ...*model.TDomain) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tDomainDo) First() (*model.TDomain, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDomain), nil
	}
}

func (t tDomainDo) Take() (*model.TDomain, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDomain), nil
	}
}

func (t tDomainDo) Last() (*model.TDomain, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDomain), nil
	}
}

func (t tDomainDo) Find() ([]*model.TDomain, error) {
	result, err := t.DO.Find()
	return result.([]*model.TDomain), err
}

func (t tDomainDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TDomain, err error) {
	buf := make([]*model.TDomain, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tDomainDo) FindInBatches(result *[]*model.TDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tDomainDo) Attrs(attrs ...field.AssignExpr) ITDomainDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tDomainDo) Assign(attrs ...field.AssignExpr) ITDomainDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tDomainDo) Joins(fields ...field.RelationField) ITDomainDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tDomainDo) Preload(fields ...field.RelationField) ITDomainDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tDomainDo) FirstOrInit() (*model.TDomain, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDomain), nil
	}
}

func (t tDomainDo) FirstOrCreate() (*model.TDomain, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TDomain), nil
	}
}

func (t tDomainDo) FindByPage(offset int, limit int) (result []*model.TDomain, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tDomainDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tDomainDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tDomainDo) Delete(models ...*model.TDomain) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tDomainDo) withDO(do gen.Dao) *tDomainDo {
	t.DO = *do.(*gen.DO)
	return t
}
