// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTEnv(db *gorm.DB, opts ...gen.DOOption) tEnv {
	_tEnv := tEnv{}

	_tEnv.tEnvDo.UseDB(db, opts...)
	_tEnv.tEnvDo.UseModel(&model.TEnv{})

	tableName := _tEnv.tEnvDo.TableName()
	_tEnv.ALL = field.NewAsterisk(tableName)
	_tEnv.ID = field.NewInt64(tableName, "id")
	_tEnv.CreatedAt = field.NewTime(tableName, "created_at")
	_tEnv.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tEnv.IsDelete = field.NewBool(tableName, "is_delete")
	_tEnv.CreatedBy = field.NewInt64(tableName, "created_by")
	_tEnv.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_tEnv.ProjectID = field.NewInt64(tableName, "project_id")
	_tEnv.Name = field.NewString(tableName, "name")
	_tEnv.Description = field.NewString(tableName, "description")
	_tEnv.Sort = field.NewInt64(tableName, "sort")
	_tEnv.Status = field.NewInt32(tableName, "status")

	_tEnv.fillFieldMap()

	return _tEnv
}

// tEnv 环境表
type tEnv struct {
	tEnvDo tEnvDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	CreatedBy   field.Int64  // 创建人ID
	UpdatedBy   field.Int64  // 更新人ID
	ProjectID   field.Int64  // 所属项目ID
	Name        field.String // 环境名称
	Description field.String // 环境描述
	Sort        field.Int64  // 排序
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tEnv) Table(newTableName string) *tEnv {
	t.tEnvDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tEnv) As(alias string) *tEnv {
	t.tEnvDo.DO = *(t.tEnvDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tEnv) updateTableName(table string) *tEnv {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.CreatedBy = field.NewInt64(table, "created_by")
	t.UpdatedBy = field.NewInt64(table, "updated_by")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Sort = field.NewInt64(table, "sort")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tEnv) WithContext(ctx context.Context) ITEnvDo { return t.tEnvDo.WithContext(ctx) }

func (t tEnv) TableName() string { return t.tEnvDo.TableName() }

func (t tEnv) Alias() string { return t.tEnvDo.Alias() }

func (t tEnv) Columns(cols ...field.Expr) gen.Columns { return t.tEnvDo.Columns(cols...) }

func (t *tEnv) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tEnv) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["updated_by"] = t.UpdatedBy
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["sort"] = t.Sort
	t.fieldMap["status"] = t.Status
}

func (t tEnv) clone(db *gorm.DB) tEnv {
	t.tEnvDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tEnv) replaceDB(db *gorm.DB) tEnv {
	t.tEnvDo.ReplaceDB(db)
	return t
}

type tEnvDo struct{ gen.DO }

type ITEnvDo interface {
	gen.SubQuery
	Debug() ITEnvDo
	WithContext(ctx context.Context) ITEnvDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITEnvDo
	WriteDB() ITEnvDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITEnvDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITEnvDo
	Not(conds ...gen.Condition) ITEnvDo
	Or(conds ...gen.Condition) ITEnvDo
	Select(conds ...field.Expr) ITEnvDo
	Where(conds ...gen.Condition) ITEnvDo
	Order(conds ...field.Expr) ITEnvDo
	Distinct(cols ...field.Expr) ITEnvDo
	Omit(cols ...field.Expr) ITEnvDo
	Join(table schema.Tabler, on ...field.Expr) ITEnvDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITEnvDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITEnvDo
	Group(cols ...field.Expr) ITEnvDo
	Having(conds ...gen.Condition) ITEnvDo
	Limit(limit int) ITEnvDo
	Offset(offset int) ITEnvDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITEnvDo
	Unscoped() ITEnvDo
	Create(values ...*model.TEnv) error
	CreateInBatches(values []*model.TEnv, batchSize int) error
	Save(values ...*model.TEnv) error
	First() (*model.TEnv, error)
	Take() (*model.TEnv, error)
	Last() (*model.TEnv, error)
	Find() ([]*model.TEnv, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TEnv, err error)
	FindInBatches(result *[]*model.TEnv, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TEnv) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITEnvDo
	Assign(attrs ...field.AssignExpr) ITEnvDo
	Joins(fields ...field.RelationField) ITEnvDo
	Preload(fields ...field.RelationField) ITEnvDo
	FirstOrInit() (*model.TEnv, error)
	FirstOrCreate() (*model.TEnv, error)
	FindByPage(offset int, limit int) (result []*model.TEnv, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITEnvDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tEnvDo) Debug() ITEnvDo {
	return t.withDO(t.DO.Debug())
}

func (t tEnvDo) WithContext(ctx context.Context) ITEnvDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tEnvDo) ReadDB() ITEnvDo {
	return t.Clauses(dbresolver.Read)
}

func (t tEnvDo) WriteDB() ITEnvDo {
	return t.Clauses(dbresolver.Write)
}

func (t tEnvDo) Session(config *gorm.Session) ITEnvDo {
	return t.withDO(t.DO.Session(config))
}

func (t tEnvDo) Clauses(conds ...clause.Expression) ITEnvDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tEnvDo) Returning(value interface{}, columns ...string) ITEnvDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tEnvDo) Not(conds ...gen.Condition) ITEnvDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tEnvDo) Or(conds ...gen.Condition) ITEnvDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tEnvDo) Select(conds ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tEnvDo) Where(conds ...gen.Condition) ITEnvDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tEnvDo) Order(conds ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tEnvDo) Distinct(cols ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tEnvDo) Omit(cols ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tEnvDo) Join(table schema.Tabler, on ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tEnvDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tEnvDo) RightJoin(table schema.Tabler, on ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tEnvDo) Group(cols ...field.Expr) ITEnvDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tEnvDo) Having(conds ...gen.Condition) ITEnvDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tEnvDo) Limit(limit int) ITEnvDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tEnvDo) Offset(offset int) ITEnvDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tEnvDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITEnvDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tEnvDo) Unscoped() ITEnvDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tEnvDo) Create(values ...*model.TEnv) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tEnvDo) CreateInBatches(values []*model.TEnv, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tEnvDo) Save(values ...*model.TEnv) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tEnvDo) First() (*model.TEnv, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TEnv), nil
	}
}

func (t tEnvDo) Take() (*model.TEnv, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TEnv), nil
	}
}

func (t tEnvDo) Last() (*model.TEnv, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TEnv), nil
	}
}

func (t tEnvDo) Find() ([]*model.TEnv, error) {
	result, err := t.DO.Find()
	return result.([]*model.TEnv), err
}

func (t tEnvDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TEnv, err error) {
	buf := make([]*model.TEnv, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tEnvDo) FindInBatches(result *[]*model.TEnv, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tEnvDo) Attrs(attrs ...field.AssignExpr) ITEnvDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tEnvDo) Assign(attrs ...field.AssignExpr) ITEnvDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tEnvDo) Joins(fields ...field.RelationField) ITEnvDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tEnvDo) Preload(fields ...field.RelationField) ITEnvDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tEnvDo) FirstOrInit() (*model.TEnv, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TEnv), nil
	}
}

func (t tEnvDo) FirstOrCreate() (*model.TEnv, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TEnv), nil
	}
}

func (t tEnvDo) FindByPage(offset int, limit int) (result []*model.TEnv, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tEnvDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tEnvDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tEnvDo) Delete(models ...*model.TEnv) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tEnvDo) withDO(do gen.Dao) *tEnvDo {
	t.DO = *do.(*gen.DO)
	return t
}
