// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTExecution(db *gorm.DB, opts ...gen.DOOption) tExecution {
	_tExecution := tExecution{}

	_tExecution.tExecutionDo.UseDB(db, opts...)
	_tExecution.tExecutionDo.UseModel(&model.TExecution{})

	tableName := _tExecution.tExecutionDo.TableName()
	_tExecution.ALL = field.NewAsterisk(tableName)
	_tExecution.ID = field.NewInt64(tableName, "id")
	_tExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_tExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tExecution.ProjectID = field.NewInt64(tableName, "project_id")
	_tExecution.WorkflowID = field.NewInt64(tableName, "workflow_id")
	_tExecution.EnvID = field.NewInt64(tableName, "env_id")
	_tExecution.ExecutorID = field.NewString(tableName, "executor_id")
	_tExecution.ExecutionID = field.NewString(tableName, "execution_id")
	_tExecution.Status = field.NewString(tableName, "status")
	_tExecution.StartTime = field.NewTime(tableName, "start_time")
	_tExecution.EndTime = field.NewTime(tableName, "end_time")
	_tExecution.Duration = field.NewInt64(tableName, "duration")
	_tExecution.Result = field.NewString(tableName, "result")
	_tExecution.Logs = field.NewString(tableName, "logs")
	_tExecution.CreatedBy = field.NewInt64(tableName, "created_by")

	_tExecution.fillFieldMap()

	return _tExecution
}

// tExecution 执行记录表
type tExecution struct {
	tExecutionDo tExecutionDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	ProjectID   field.Int64  // 所属项目ID
	WorkflowID  field.Int64  // 工作流ID
	EnvID       field.Int64  // 执行环境ID
	ExecutorID  field.String // 执行机ID(来自workflow-engine)
	ExecutionID field.String // workflow-engine返回的执行ID
	Status      field.String // 执行状态: pending, running, completed, failed, stopped
	StartTime   field.Time   // 开始时间
	EndTime     field.Time   // 结束时间
	Duration    field.Int64  // 执行时长(毫秒)
	Result      field.String // 执行结果(JSON格式)
	Logs        field.String // 执行日志
	CreatedBy   field.Int64  // 创建人ID

	fieldMap map[string]field.Expr
}

func (t tExecution) Table(newTableName string) *tExecution {
	t.tExecutionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tExecution) As(alias string) *tExecution {
	t.tExecutionDo.DO = *(t.tExecutionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tExecution) updateTableName(table string) *tExecution {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.WorkflowID = field.NewInt64(table, "workflow_id")
	t.EnvID = field.NewInt64(table, "env_id")
	t.ExecutorID = field.NewString(table, "executor_id")
	t.ExecutionID = field.NewString(table, "execution_id")
	t.Status = field.NewString(table, "status")
	t.StartTime = field.NewTime(table, "start_time")
	t.EndTime = field.NewTime(table, "end_time")
	t.Duration = field.NewInt64(table, "duration")
	t.Result = field.NewString(table, "result")
	t.Logs = field.NewString(table, "logs")
	t.CreatedBy = field.NewInt64(table, "created_by")

	t.fillFieldMap()

	return t
}

func (t *tExecution) WithContext(ctx context.Context) ITExecutionDo {
	return t.tExecutionDo.WithContext(ctx)
}

func (t tExecution) TableName() string { return t.tExecutionDo.TableName() }

func (t tExecution) Alias() string { return t.tExecutionDo.Alias() }

func (t tExecution) Columns(cols ...field.Expr) gen.Columns { return t.tExecutionDo.Columns(cols...) }

func (t *tExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tExecution) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 15)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["workflow_id"] = t.WorkflowID
	t.fieldMap["env_id"] = t.EnvID
	t.fieldMap["executor_id"] = t.ExecutorID
	t.fieldMap["execution_id"] = t.ExecutionID
	t.fieldMap["status"] = t.Status
	t.fieldMap["start_time"] = t.StartTime
	t.fieldMap["end_time"] = t.EndTime
	t.fieldMap["duration"] = t.Duration
	t.fieldMap["result"] = t.Result
	t.fieldMap["logs"] = t.Logs
	t.fieldMap["created_by"] = t.CreatedBy
}

func (t tExecution) clone(db *gorm.DB) tExecution {
	t.tExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tExecution) replaceDB(db *gorm.DB) tExecution {
	t.tExecutionDo.ReplaceDB(db)
	return t
}

type tExecutionDo struct{ gen.DO }

type ITExecutionDo interface {
	gen.SubQuery
	Debug() ITExecutionDo
	WithContext(ctx context.Context) ITExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITExecutionDo
	WriteDB() ITExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITExecutionDo
	Not(conds ...gen.Condition) ITExecutionDo
	Or(conds ...gen.Condition) ITExecutionDo
	Select(conds ...field.Expr) ITExecutionDo
	Where(conds ...gen.Condition) ITExecutionDo
	Order(conds ...field.Expr) ITExecutionDo
	Distinct(cols ...field.Expr) ITExecutionDo
	Omit(cols ...field.Expr) ITExecutionDo
	Join(table schema.Tabler, on ...field.Expr) ITExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITExecutionDo
	Group(cols ...field.Expr) ITExecutionDo
	Having(conds ...gen.Condition) ITExecutionDo
	Limit(limit int) ITExecutionDo
	Offset(offset int) ITExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITExecutionDo
	Unscoped() ITExecutionDo
	Create(values ...*model.TExecution) error
	CreateInBatches(values []*model.TExecution, batchSize int) error
	Save(values ...*model.TExecution) error
	First() (*model.TExecution, error)
	Take() (*model.TExecution, error)
	Last() (*model.TExecution, error)
	Find() ([]*model.TExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TExecution, err error)
	FindInBatches(result *[]*model.TExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITExecutionDo
	Assign(attrs ...field.AssignExpr) ITExecutionDo
	Joins(fields ...field.RelationField) ITExecutionDo
	Preload(fields ...field.RelationField) ITExecutionDo
	FirstOrInit() (*model.TExecution, error)
	FirstOrCreate() (*model.TExecution, error)
	FindByPage(offset int, limit int) (result []*model.TExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tExecutionDo) Debug() ITExecutionDo {
	return t.withDO(t.DO.Debug())
}

func (t tExecutionDo) WithContext(ctx context.Context) ITExecutionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tExecutionDo) ReadDB() ITExecutionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tExecutionDo) WriteDB() ITExecutionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tExecutionDo) Session(config *gorm.Session) ITExecutionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tExecutionDo) Clauses(conds ...clause.Expression) ITExecutionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tExecutionDo) Returning(value interface{}, columns ...string) ITExecutionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tExecutionDo) Not(conds ...gen.Condition) ITExecutionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tExecutionDo) Or(conds ...gen.Condition) ITExecutionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tExecutionDo) Select(conds ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tExecutionDo) Where(conds ...gen.Condition) ITExecutionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tExecutionDo) Order(conds ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tExecutionDo) Distinct(cols ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tExecutionDo) Omit(cols ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tExecutionDo) Join(table schema.Tabler, on ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tExecutionDo) Group(cols ...field.Expr) ITExecutionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tExecutionDo) Having(conds ...gen.Condition) ITExecutionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tExecutionDo) Limit(limit int) ITExecutionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tExecutionDo) Offset(offset int) ITExecutionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITExecutionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tExecutionDo) Unscoped() ITExecutionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tExecutionDo) Create(values ...*model.TExecution) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tExecutionDo) CreateInBatches(values []*model.TExecution, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tExecutionDo) Save(values ...*model.TExecution) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tExecutionDo) First() (*model.TExecution, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecution), nil
	}
}

func (t tExecutionDo) Take() (*model.TExecution, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecution), nil
	}
}

func (t tExecutionDo) Last() (*model.TExecution, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecution), nil
	}
}

func (t tExecutionDo) Find() ([]*model.TExecution, error) {
	result, err := t.DO.Find()
	return result.([]*model.TExecution), err
}

func (t tExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TExecution, err error) {
	buf := make([]*model.TExecution, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tExecutionDo) FindInBatches(result *[]*model.TExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tExecutionDo) Attrs(attrs ...field.AssignExpr) ITExecutionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tExecutionDo) Assign(attrs ...field.AssignExpr) ITExecutionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tExecutionDo) Joins(fields ...field.RelationField) ITExecutionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tExecutionDo) Preload(fields ...field.RelationField) ITExecutionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tExecutionDo) FirstOrInit() (*model.TExecution, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecution), nil
	}
}

func (t tExecutionDo) FirstOrCreate() (*model.TExecution, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecution), nil
	}
}

func (t tExecutionDo) FindByPage(offset int, limit int) (result []*model.TExecution, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tExecutionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tExecutionDo) Delete(models ...*model.TExecution) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tExecutionDo) withDO(do gen.Dao) *tExecutionDo {
	t.DO = *do.(*gen.DO)
	return t
}
