// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTExecutor(db *gorm.DB, opts ...gen.DOOption) tExecutor {
	_tExecutor := tExecutor{}

	_tExecutor.tExecutorDo.UseDB(db, opts...)
	_tExecutor.tExecutorDo.UseModel(&model.TExecutor{})

	tableName := _tExecutor.tExecutorDo.TableName()
	_tExecutor.ALL = field.NewAsterisk(tableName)
	_tExecutor.ID = field.NewInt64(tableName, "id")
	_tExecutor.CreatedAt = field.NewTime(tableName, "created_at")
	_tExecutor.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tExecutor.IsDelete = field.NewBool(tableName, "is_delete")
	_tExecutor.SlaveID = field.NewString(tableName, "slave_id")
	_tExecutor.Name = field.NewString(tableName, "name")
	_tExecutor.Type = field.NewString(tableName, "type")
	_tExecutor.Description = field.NewString(tableName, "description")
	_tExecutor.Labels = field.NewString(tableName, "labels")
	_tExecutor.MaxVus = field.NewInt32(tableName, "max_vus")
	_tExecutor.Priority = field.NewInt32(tableName, "priority")
	_tExecutor.Status = field.NewInt32(tableName, "status")

	_tExecutor.fillFieldMap()

	return _tExecutor
}

// tExecutor 执行机表
type tExecutor struct {
	tExecutorDo tExecutorDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	SlaveID     field.String // workflow-engine的Slave ID
	Name        field.String // 执行机名称
	Type        field.String // 执行机类型: performance(压测专用), normal(普通), debug(调试专用)
	Description field.String // 描述
	Labels      field.String // 标签 {"env":"prod","region":"cn-east"}
	MaxVus      field.Int32  // 最大虚拟用户数限制
	Priority    field.Int32  // 优先级，数值越大优先级越高
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tExecutor) Table(newTableName string) *tExecutor {
	t.tExecutorDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tExecutor) As(alias string) *tExecutor {
	t.tExecutorDo.DO = *(t.tExecutorDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tExecutor) updateTableName(table string) *tExecutor {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.SlaveID = field.NewString(table, "slave_id")
	t.Name = field.NewString(table, "name")
	t.Type = field.NewString(table, "type")
	t.Description = field.NewString(table, "description")
	t.Labels = field.NewString(table, "labels")
	t.MaxVus = field.NewInt32(table, "max_vus")
	t.Priority = field.NewInt32(table, "priority")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tExecutor) WithContext(ctx context.Context) ITExecutorDo {
	return t.tExecutorDo.WithContext(ctx)
}

func (t tExecutor) TableName() string { return t.tExecutorDo.TableName() }

func (t tExecutor) Alias() string { return t.tExecutorDo.Alias() }

func (t tExecutor) Columns(cols ...field.Expr) gen.Columns { return t.tExecutorDo.Columns(cols...) }

func (t *tExecutor) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tExecutor) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["slave_id"] = t.SlaveID
	t.fieldMap["name"] = t.Name
	t.fieldMap["type"] = t.Type
	t.fieldMap["description"] = t.Description
	t.fieldMap["labels"] = t.Labels
	t.fieldMap["max_vus"] = t.MaxVus
	t.fieldMap["priority"] = t.Priority
	t.fieldMap["status"] = t.Status
}

func (t tExecutor) clone(db *gorm.DB) tExecutor {
	t.tExecutorDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tExecutor) replaceDB(db *gorm.DB) tExecutor {
	t.tExecutorDo.ReplaceDB(db)
	return t
}

type tExecutorDo struct{ gen.DO }

type ITExecutorDo interface {
	gen.SubQuery
	Debug() ITExecutorDo
	WithContext(ctx context.Context) ITExecutorDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITExecutorDo
	WriteDB() ITExecutorDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITExecutorDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITExecutorDo
	Not(conds ...gen.Condition) ITExecutorDo
	Or(conds ...gen.Condition) ITExecutorDo
	Select(conds ...field.Expr) ITExecutorDo
	Where(conds ...gen.Condition) ITExecutorDo
	Order(conds ...field.Expr) ITExecutorDo
	Distinct(cols ...field.Expr) ITExecutorDo
	Omit(cols ...field.Expr) ITExecutorDo
	Join(table schema.Tabler, on ...field.Expr) ITExecutorDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITExecutorDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITExecutorDo
	Group(cols ...field.Expr) ITExecutorDo
	Having(conds ...gen.Condition) ITExecutorDo
	Limit(limit int) ITExecutorDo
	Offset(offset int) ITExecutorDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITExecutorDo
	Unscoped() ITExecutorDo
	Create(values ...*model.TExecutor) error
	CreateInBatches(values []*model.TExecutor, batchSize int) error
	Save(values ...*model.TExecutor) error
	First() (*model.TExecutor, error)
	Take() (*model.TExecutor, error)
	Last() (*model.TExecutor, error)
	Find() ([]*model.TExecutor, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TExecutor, err error)
	FindInBatches(result *[]*model.TExecutor, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TExecutor) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITExecutorDo
	Assign(attrs ...field.AssignExpr) ITExecutorDo
	Joins(fields ...field.RelationField) ITExecutorDo
	Preload(fields ...field.RelationField) ITExecutorDo
	FirstOrInit() (*model.TExecutor, error)
	FirstOrCreate() (*model.TExecutor, error)
	FindByPage(offset int, limit int) (result []*model.TExecutor, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITExecutorDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tExecutorDo) Debug() ITExecutorDo {
	return t.withDO(t.DO.Debug())
}

func (t tExecutorDo) WithContext(ctx context.Context) ITExecutorDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tExecutorDo) ReadDB() ITExecutorDo {
	return t.Clauses(dbresolver.Read)
}

func (t tExecutorDo) WriteDB() ITExecutorDo {
	return t.Clauses(dbresolver.Write)
}

func (t tExecutorDo) Session(config *gorm.Session) ITExecutorDo {
	return t.withDO(t.DO.Session(config))
}

func (t tExecutorDo) Clauses(conds ...clause.Expression) ITExecutorDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tExecutorDo) Returning(value interface{}, columns ...string) ITExecutorDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tExecutorDo) Not(conds ...gen.Condition) ITExecutorDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tExecutorDo) Or(conds ...gen.Condition) ITExecutorDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tExecutorDo) Select(conds ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tExecutorDo) Where(conds ...gen.Condition) ITExecutorDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tExecutorDo) Order(conds ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tExecutorDo) Distinct(cols ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tExecutorDo) Omit(cols ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tExecutorDo) Join(table schema.Tabler, on ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tExecutorDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tExecutorDo) RightJoin(table schema.Tabler, on ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tExecutorDo) Group(cols ...field.Expr) ITExecutorDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tExecutorDo) Having(conds ...gen.Condition) ITExecutorDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tExecutorDo) Limit(limit int) ITExecutorDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tExecutorDo) Offset(offset int) ITExecutorDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tExecutorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITExecutorDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tExecutorDo) Unscoped() ITExecutorDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tExecutorDo) Create(values ...*model.TExecutor) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tExecutorDo) CreateInBatches(values []*model.TExecutor, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tExecutorDo) Save(values ...*model.TExecutor) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tExecutorDo) First() (*model.TExecutor, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecutor), nil
	}
}

func (t tExecutorDo) Take() (*model.TExecutor, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecutor), nil
	}
}

func (t tExecutorDo) Last() (*model.TExecutor, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecutor), nil
	}
}

func (t tExecutorDo) Find() ([]*model.TExecutor, error) {
	result, err := t.DO.Find()
	return result.([]*model.TExecutor), err
}

func (t tExecutorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TExecutor, err error) {
	buf := make([]*model.TExecutor, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tExecutorDo) FindInBatches(result *[]*model.TExecutor, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tExecutorDo) Attrs(attrs ...field.AssignExpr) ITExecutorDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tExecutorDo) Assign(attrs ...field.AssignExpr) ITExecutorDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tExecutorDo) Joins(fields ...field.RelationField) ITExecutorDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tExecutorDo) Preload(fields ...field.RelationField) ITExecutorDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tExecutorDo) FirstOrInit() (*model.TExecutor, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecutor), nil
	}
}

func (t tExecutorDo) FirstOrCreate() (*model.TExecutor, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TExecutor), nil
	}
}

func (t tExecutorDo) FindByPage(offset int, limit int) (result []*model.TExecutor, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tExecutorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tExecutorDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tExecutorDo) Delete(models ...*model.TExecutor) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tExecutorDo) withDO(do gen.Dao) *tExecutorDo {
	t.DO = *do.(*gen.DO)
	return t
}
