// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/plugin/dbresolver"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"yqhp/gulu/internal/model"
)

func newTKnowledgeBase(db *gorm.DB, opts ...gen.DOOption) tKnowledgeBase {
	_tKnowledgeBase := tKnowledgeBase{}

	_tKnowledgeBase.tKnowledgeBaseDo.UseDB(db, opts...)
	_tKnowledgeBase.tKnowledgeBaseDo.UseModel(&model.TKnowledgeBase{})

	tableName := _tKnowledgeBase.tKnowledgeBaseDo.TableName()
	_tKnowledgeBase.ALL = field.NewAsterisk(tableName)
	_tKnowledgeBase.ID = field.NewInt64(tableName, "id")
	_tKnowledgeBase.CreatedAt = field.NewTime(tableName, "created_at")
	_tKnowledgeBase.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tKnowledgeBase.IsDelete = field.NewBool(tableName, "is_delete")
	_tKnowledgeBase.CreatedBy = field.NewInt64(tableName, "created_by")
	_tKnowledgeBase.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_tKnowledgeBase.ProjectID = field.NewInt64(tableName, "project_id")
	_tKnowledgeBase.Name = field.NewString(tableName, "name")
	_tKnowledgeBase.Description = field.NewString(tableName, "description")
	_tKnowledgeBase.Type = field.NewString(tableName, "type")
	_tKnowledgeBase.Status = field.NewInt32(tableName, "status")
	_tKnowledgeBase.EmbeddingModelID = field.NewInt64(tableName, "embedding_model_id")
	_tKnowledgeBase.EmbeddingModelName = field.NewString(tableName, "embedding_model_name")
	_tKnowledgeBase.EmbeddingDimension = field.NewInt32(tableName, "embedding_dimension")
	_tKnowledgeBase.ChunkSize = field.NewInt32(tableName, "chunk_size")
	_tKnowledgeBase.ChunkOverlap = field.NewInt32(tableName, "chunk_overlap")
	_tKnowledgeBase.SimilarityThreshold = field.NewFloat64(tableName, "similarity_threshold")
	_tKnowledgeBase.TopK = field.NewInt32(tableName, "top_k")
	_tKnowledgeBase.QdrantCollection = field.NewString(tableName, "qdrant_collection")
	_tKnowledgeBase.Neo4jDatabase = field.NewString(tableName, "neo4j_database")
	_tKnowledgeBase.Metadata = field.NewString(tableName, "metadata")

	_tKnowledgeBase.fillFieldMap()

	return _tKnowledgeBase
}

// tKnowledgeBase 知识库主表
type tKnowledgeBase struct {
	tKnowledgeBaseDo tKnowledgeBaseDo

	ALL                 field.Asterisk
	ID                  field.Int64
	CreatedAt           field.Time
	UpdatedAt           field.Time
	IsDelete            field.Bool
	CreatedBy           field.Int64
	UpdatedBy           field.Int64
	ProjectID           field.Int64
	Name                field.String
	Description         field.String
	Type                field.String
	Status              field.Int32
	EmbeddingModelID    field.Int64
	EmbeddingModelName  field.String
	EmbeddingDimension  field.Int32
	ChunkSize           field.Int32
	ChunkOverlap        field.Int32
	SimilarityThreshold field.Float64
	TopK                field.Int32
	QdrantCollection    field.String
	Neo4jDatabase       field.String
	Metadata            field.String

	fieldMap map[string]field.Expr
}

func (t tKnowledgeBase) Table(newTableName string) *tKnowledgeBase {
	t.tKnowledgeBaseDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tKnowledgeBase) As(alias string) *tKnowledgeBase {
	t.tKnowledgeBaseDo.DO = *(t.tKnowledgeBaseDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tKnowledgeBase) updateTableName(table string) *tKnowledgeBase {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.CreatedBy = field.NewInt64(table, "created_by")
	t.UpdatedBy = field.NewInt64(table, "updated_by")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Type = field.NewString(table, "type")
	t.Status = field.NewInt32(table, "status")
	t.EmbeddingModelID = field.NewInt64(table, "embedding_model_id")
	t.EmbeddingModelName = field.NewString(table, "embedding_model_name")
	t.EmbeddingDimension = field.NewInt32(table, "embedding_dimension")
	t.ChunkSize = field.NewInt32(table, "chunk_size")
	t.ChunkOverlap = field.NewInt32(table, "chunk_overlap")
	t.SimilarityThreshold = field.NewFloat64(table, "similarity_threshold")
	t.TopK = field.NewInt32(table, "top_k")
	t.QdrantCollection = field.NewString(table, "qdrant_collection")
	t.Neo4jDatabase = field.NewString(table, "neo4j_database")
	t.Metadata = field.NewString(table, "metadata")

	t.fillFieldMap()

	return t
}

func (t *tKnowledgeBase) WithContext(ctx context.Context) ITKnowledgeBaseDo {
	return t.tKnowledgeBaseDo.WithContext(ctx)
}

func (t tKnowledgeBase) TableName() string { return t.tKnowledgeBaseDo.TableName() }

func (t tKnowledgeBase) Alias() string { return t.tKnowledgeBaseDo.Alias() }

func (t tKnowledgeBase) Columns(cols ...field.Expr) gen.Columns { return t.tKnowledgeBaseDo.Columns(cols...) }

func (t *tKnowledgeBase) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tKnowledgeBase) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 23)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["updated_by"] = t.UpdatedBy
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["type"] = t.Type
	t.fieldMap["status"] = t.Status
	t.fieldMap["embedding_model_id"] = t.EmbeddingModelID
	t.fieldMap["embedding_model_name"] = t.EmbeddingModelName
	t.fieldMap["embedding_dimension"] = t.EmbeddingDimension
	t.fieldMap["chunk_size"] = t.ChunkSize
	t.fieldMap["chunk_overlap"] = t.ChunkOverlap
	t.fieldMap["similarity_threshold"] = t.SimilarityThreshold
	t.fieldMap["top_k"] = t.TopK
	t.fieldMap["qdrant_collection"] = t.QdrantCollection
	t.fieldMap["neo4j_database"] = t.Neo4jDatabase
	t.fieldMap["metadata"] = t.Metadata
}

func (t tKnowledgeBase) clone(db *gorm.DB) tKnowledgeBase {
	t.tKnowledgeBaseDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tKnowledgeBase) replaceDB(db *gorm.DB) tKnowledgeBase {
	t.tKnowledgeBaseDo.ReplaceDB(db)
	return t
}

type tKnowledgeBaseDo struct{ gen.DO }

type ITKnowledgeBaseDo interface {
	gen.SubQuery
	Debug() ITKnowledgeBaseDo
	WithContext(ctx context.Context) ITKnowledgeBaseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITKnowledgeBaseDo
	WriteDB() ITKnowledgeBaseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITKnowledgeBaseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITKnowledgeBaseDo
	Not(conds ...gen.Condition) ITKnowledgeBaseDo
	Or(conds ...gen.Condition) ITKnowledgeBaseDo
	Select(conds ...field.Expr) ITKnowledgeBaseDo
	Where(conds ...gen.Condition) ITKnowledgeBaseDo
	Order(conds ...field.Expr) ITKnowledgeBaseDo
	Distinct(cols ...field.Expr) ITKnowledgeBaseDo
	Omit(cols ...field.Expr) ITKnowledgeBaseDo
	Join(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo
	Group(cols ...field.Expr) ITKnowledgeBaseDo
	Having(conds ...gen.Condition) ITKnowledgeBaseDo
	Limit(limit int) ITKnowledgeBaseDo
	Offset(offset int) ITKnowledgeBaseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITKnowledgeBaseDo
	Unscoped() ITKnowledgeBaseDo
	Create(values ...*model.TKnowledgeBase) error
	CreateInBatches(values []*model.TKnowledgeBase, batchSize int) error
	Save(values ...*model.TKnowledgeBase) error
	First() (*model.TKnowledgeBase, error)
	Take() (*model.TKnowledgeBase, error)
	Last() (*model.TKnowledgeBase, error)
	Find() ([]*model.TKnowledgeBase, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TKnowledgeBase, err error)
	FindInBatches(result *[]*model.TKnowledgeBase, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TKnowledgeBase) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITKnowledgeBaseDo
	Assign(attrs ...field.AssignExpr) ITKnowledgeBaseDo
	Joins(fields ...field.RelationField) ITKnowledgeBaseDo
	Preload(fields ...field.RelationField) ITKnowledgeBaseDo
	FirstOrInit() (*model.TKnowledgeBase, error)
	FirstOrCreate() (*model.TKnowledgeBase, error)
	FindByPage(offset int, limit int) (result []*model.TKnowledgeBase, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITKnowledgeBaseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tKnowledgeBaseDo) Debug() ITKnowledgeBaseDo {
	return t.withDO(t.DO.Debug())
}

func (t tKnowledgeBaseDo) WithContext(ctx context.Context) ITKnowledgeBaseDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tKnowledgeBaseDo) ReadDB() ITKnowledgeBaseDo {
	return t.Clauses(dbresolver.Read)
}

func (t tKnowledgeBaseDo) WriteDB() ITKnowledgeBaseDo {
	return t.Clauses(dbresolver.Write)
}

func (t tKnowledgeBaseDo) Session(config *gorm.Session) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Session(config))
}

func (t tKnowledgeBaseDo) Clauses(conds ...clause.Expression) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tKnowledgeBaseDo) Returning(value interface{}, columns ...string) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tKnowledgeBaseDo) Not(conds ...gen.Condition) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tKnowledgeBaseDo) Or(conds ...gen.Condition) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tKnowledgeBaseDo) Select(conds ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tKnowledgeBaseDo) Where(conds ...gen.Condition) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tKnowledgeBaseDo) Order(conds ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tKnowledgeBaseDo) Distinct(cols ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tKnowledgeBaseDo) Omit(cols ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tKnowledgeBaseDo) Join(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tKnowledgeBaseDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tKnowledgeBaseDo) RightJoin(table schema.Tabler, on ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tKnowledgeBaseDo) Group(cols ...field.Expr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tKnowledgeBaseDo) Having(conds ...gen.Condition) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tKnowledgeBaseDo) Limit(limit int) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tKnowledgeBaseDo) Offset(offset int) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tKnowledgeBaseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tKnowledgeBaseDo) Unscoped() ITKnowledgeBaseDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tKnowledgeBaseDo) Create(values ...*model.TKnowledgeBase) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tKnowledgeBaseDo) CreateInBatches(values []*model.TKnowledgeBase, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tKnowledgeBaseDo) Save(values ...*model.TKnowledgeBase) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tKnowledgeBaseDo) First() (*model.TKnowledgeBase, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgeBase), nil
	}
}

func (t tKnowledgeBaseDo) Take() (*model.TKnowledgeBase, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgeBase), nil
	}
}

func (t tKnowledgeBaseDo) Last() (*model.TKnowledgeBase, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgeBase), nil
	}
}

func (t tKnowledgeBaseDo) Find() ([]*model.TKnowledgeBase, error) {
	result, err := t.DO.Find()
	return result.([]*model.TKnowledgeBase), err
}

func (t tKnowledgeBaseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TKnowledgeBase, err error) {
	buf := make([]*model.TKnowledgeBase, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tKnowledgeBaseDo) FindInBatches(result *[]*model.TKnowledgeBase, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tKnowledgeBaseDo) Attrs(attrs ...field.AssignExpr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tKnowledgeBaseDo) Assign(attrs ...field.AssignExpr) ITKnowledgeBaseDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tKnowledgeBaseDo) Joins(fields ...field.RelationField) ITKnowledgeBaseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tKnowledgeBaseDo) Preload(fields ...field.RelationField) ITKnowledgeBaseDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tKnowledgeBaseDo) FirstOrInit() (*model.TKnowledgeBase, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgeBase), nil
	}
}

func (t tKnowledgeBaseDo) FirstOrCreate() (*model.TKnowledgeBase, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TKnowledgeBase), nil
	}
}

func (t tKnowledgeBaseDo) FindByPage(offset int, limit int) (result []*model.TKnowledgeBase, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tKnowledgeBaseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tKnowledgeBaseDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tKnowledgeBaseDo) Delete(models ...*model.TKnowledgeBase) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tKnowledgeBaseDo) withDO(do gen.Dao) *tKnowledgeBaseDo {
	t.DO = *do.(*gen.DO)
	return t
}
