// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/plugin/dbresolver"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"yqhp/gulu/internal/model"
)

func newTMcpServer(db *gorm.DB, opts ...gen.DOOption) tMcpServer {
	_tMcpServer := tMcpServer{}

	_tMcpServer.tMcpServerDo.UseDB(db, opts...)
	_tMcpServer.tMcpServerDo.UseModel(&model.TMcpServer{})

	tableName := _tMcpServer.tMcpServerDo.TableName()
	_tMcpServer.ALL = field.NewAsterisk(tableName)
	_tMcpServer.ID = field.NewInt64(tableName, "id")
	_tMcpServer.CreatedAt = field.NewTime(tableName, "created_at")
	_tMcpServer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tMcpServer.IsDelete = field.NewBool(tableName, "is_delete")
	_tMcpServer.CreatedBy = field.NewInt64(tableName, "created_by")
	_tMcpServer.Name = field.NewString(tableName, "name")
	_tMcpServer.Description = field.NewString(tableName, "description")
	_tMcpServer.Transport = field.NewString(tableName, "transport")
	_tMcpServer.Command = field.NewString(tableName, "command")
	_tMcpServer.Args = field.NewString(tableName, "args")
	_tMcpServer.URL = field.NewString(tableName, "url")
	_tMcpServer.Env = field.NewString(tableName, "env")
	_tMcpServer.Timeout = field.NewInt32(tableName, "timeout")
	_tMcpServer.Sort = field.NewInt32(tableName, "sort")
	_tMcpServer.Status = field.NewInt32(tableName, "status")

	_tMcpServer.fillFieldMap()

	return _tMcpServer
}

// tMcpServer MCP服务器配置表
type tMcpServer struct {
	tMcpServerDo tMcpServerDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	CreatedBy   field.Int64  // 创建人ID
	Name        field.String // 服务器名称
	Description field.String // 描述
	Transport   field.String // 传输方式: stdio/sse
	Command     field.String // stdio模式命令
	Args        field.String // stdio模式参数
	URL         field.String // sse模式URL
	Env         field.String // 环境变量
	Timeout     field.Int32  // 超时秒数
	Sort        field.Int32  // 排序
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tMcpServer) Table(newTableName string) *tMcpServer {
	t.tMcpServerDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tMcpServer) As(alias string) *tMcpServer {
	t.tMcpServerDo.DO = *(t.tMcpServerDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tMcpServer) updateTableName(table string) *tMcpServer {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.CreatedBy = field.NewInt64(table, "created_by")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Transport = field.NewString(table, "transport")
	t.Command = field.NewString(table, "command")
	t.Args = field.NewString(table, "args")
	t.URL = field.NewString(table, "url")
	t.Env = field.NewString(table, "env")
	t.Timeout = field.NewInt32(table, "timeout")
	t.Sort = field.NewInt32(table, "sort")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tMcpServer) WithContext(ctx context.Context) ITMcpServerDo {
	return t.tMcpServerDo.WithContext(ctx)
}

func (t tMcpServer) TableName() string { return t.tMcpServerDo.TableName() }

func (t tMcpServer) Alias() string { return t.tMcpServerDo.Alias() }

func (t tMcpServer) Columns(cols ...field.Expr) gen.Columns { return t.tMcpServerDo.Columns(cols...) }

func (t *tMcpServer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tMcpServer) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 15)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["transport"] = t.Transport
	t.fieldMap["command"] = t.Command
	t.fieldMap["args"] = t.Args
	t.fieldMap["url"] = t.URL
	t.fieldMap["env"] = t.Env
	t.fieldMap["timeout"] = t.Timeout
	t.fieldMap["sort"] = t.Sort
	t.fieldMap["status"] = t.Status
}

func (t tMcpServer) clone(db *gorm.DB) tMcpServer {
	t.tMcpServerDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tMcpServer) replaceDB(db *gorm.DB) tMcpServer {
	t.tMcpServerDo.ReplaceDB(db)
	return t
}

type tMcpServerDo struct{ gen.DO }

type ITMcpServerDo interface {
	gen.SubQuery
	Debug() ITMcpServerDo
	WithContext(ctx context.Context) ITMcpServerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITMcpServerDo
	WriteDB() ITMcpServerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITMcpServerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITMcpServerDo
	Not(conds ...gen.Condition) ITMcpServerDo
	Or(conds ...gen.Condition) ITMcpServerDo
	Select(conds ...field.Expr) ITMcpServerDo
	Where(conds ...gen.Condition) ITMcpServerDo
	Order(conds ...field.Expr) ITMcpServerDo
	Distinct(cols ...field.Expr) ITMcpServerDo
	Omit(cols ...field.Expr) ITMcpServerDo
	Join(table schema.Tabler, on ...field.Expr) ITMcpServerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITMcpServerDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITMcpServerDo
	Group(cols ...field.Expr) ITMcpServerDo
	Having(conds ...gen.Condition) ITMcpServerDo
	Limit(limit int) ITMcpServerDo
	Offset(offset int) ITMcpServerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITMcpServerDo
	Unscoped() ITMcpServerDo
	Create(values ...*model.TMcpServer) error
	CreateInBatches(values []*model.TMcpServer, batchSize int) error
	Save(values ...*model.TMcpServer) error
	First() (*model.TMcpServer, error)
	Take() (*model.TMcpServer, error)
	Last() (*model.TMcpServer, error)
	Find() ([]*model.TMcpServer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TMcpServer, err error)
	FindInBatches(result *[]*model.TMcpServer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TMcpServer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITMcpServerDo
	Assign(attrs ...field.AssignExpr) ITMcpServerDo
	Joins(fields ...field.RelationField) ITMcpServerDo
	Preload(fields ...field.RelationField) ITMcpServerDo
	FirstOrInit() (*model.TMcpServer, error)
	FirstOrCreate() (*model.TMcpServer, error)
	FindByPage(offset int, limit int) (result []*model.TMcpServer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITMcpServerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tMcpServerDo) Debug() ITMcpServerDo {
	return t.withDO(t.DO.Debug())
}

func (t tMcpServerDo) WithContext(ctx context.Context) ITMcpServerDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tMcpServerDo) ReadDB() ITMcpServerDo {
	return t.Clauses(dbresolver.Read)
}

func (t tMcpServerDo) WriteDB() ITMcpServerDo {
	return t.Clauses(dbresolver.Write)
}

func (t tMcpServerDo) Session(config *gorm.Session) ITMcpServerDo {
	return t.withDO(t.DO.Session(config))
}

func (t tMcpServerDo) Clauses(conds ...clause.Expression) ITMcpServerDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tMcpServerDo) Returning(value interface{}, columns ...string) ITMcpServerDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tMcpServerDo) Not(conds ...gen.Condition) ITMcpServerDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tMcpServerDo) Or(conds ...gen.Condition) ITMcpServerDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tMcpServerDo) Select(conds ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tMcpServerDo) Where(conds ...gen.Condition) ITMcpServerDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tMcpServerDo) Order(conds ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tMcpServerDo) Distinct(cols ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tMcpServerDo) Omit(cols ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tMcpServerDo) Join(table schema.Tabler, on ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tMcpServerDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tMcpServerDo) RightJoin(table schema.Tabler, on ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tMcpServerDo) Group(cols ...field.Expr) ITMcpServerDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tMcpServerDo) Having(conds ...gen.Condition) ITMcpServerDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tMcpServerDo) Limit(limit int) ITMcpServerDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tMcpServerDo) Offset(offset int) ITMcpServerDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tMcpServerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITMcpServerDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tMcpServerDo) Unscoped() ITMcpServerDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tMcpServerDo) Create(values ...*model.TMcpServer) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tMcpServerDo) CreateInBatches(values []*model.TMcpServer, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tMcpServerDo) Save(values ...*model.TMcpServer) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tMcpServerDo) First() (*model.TMcpServer, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMcpServer), nil
	}
}

func (t tMcpServerDo) Take() (*model.TMcpServer, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMcpServer), nil
	}
}

func (t tMcpServerDo) Last() (*model.TMcpServer, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMcpServer), nil
	}
}

func (t tMcpServerDo) Find() ([]*model.TMcpServer, error) {
	result, err := t.DO.Find()
	return result.([]*model.TMcpServer), err
}

func (t tMcpServerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TMcpServer, err error) {
	buf := make([]*model.TMcpServer, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tMcpServerDo) FindInBatches(result *[]*model.TMcpServer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tMcpServerDo) Attrs(attrs ...field.AssignExpr) ITMcpServerDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tMcpServerDo) Assign(attrs ...field.AssignExpr) ITMcpServerDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tMcpServerDo) Joins(fields ...field.RelationField) ITMcpServerDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tMcpServerDo) Preload(fields ...field.RelationField) ITMcpServerDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tMcpServerDo) FirstOrInit() (*model.TMcpServer, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMcpServer), nil
	}
}

func (t tMcpServerDo) FirstOrCreate() (*model.TMcpServer, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMcpServer), nil
	}
}

func (t tMcpServerDo) FindByPage(offset int, limit int) (result []*model.TMcpServer, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tMcpServerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tMcpServerDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tMcpServerDo) Delete(models ...*model.TMcpServer) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tMcpServerDo) withDO(do gen.Dao) *tMcpServerDo {
	t.DO = *do.(*gen.DO)
	return t
}
