// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTMqConfig(db *gorm.DB, opts ...gen.DOOption) tMqConfig {
	_tMqConfig := tMqConfig{}

	_tMqConfig.tMqConfigDo.UseDB(db, opts...)
	_tMqConfig.tMqConfigDo.UseModel(&model.TMqConfig{})

	tableName := _tMqConfig.tMqConfigDo.TableName()
	_tMqConfig.ALL = field.NewAsterisk(tableName)
	_tMqConfig.ID = field.NewInt64(tableName, "id")
	_tMqConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_tMqConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tMqConfig.IsDelete = field.NewBool(tableName, "is_delete")
	_tMqConfig.ProjectID = field.NewInt64(tableName, "project_id")
	_tMqConfig.EnvID = field.NewInt64(tableName, "env_id")
	_tMqConfig.Name = field.NewString(tableName, "name")
	_tMqConfig.Code = field.NewString(tableName, "code")
	_tMqConfig.Type = field.NewString(tableName, "type")
	_tMqConfig.Host = field.NewString(tableName, "host")
	_tMqConfig.Port = field.NewInt32(tableName, "port")
	_tMqConfig.Username = field.NewString(tableName, "username")
	_tMqConfig.Password = field.NewString(tableName, "password")
	_tMqConfig.Vhost = field.NewString(tableName, "vhost")
	_tMqConfig.Options = field.NewString(tableName, "options")
	_tMqConfig.Description = field.NewString(tableName, "description")
	_tMqConfig.Status = field.NewInt32(tableName, "status")

	_tMqConfig.fillFieldMap()

	return _tMqConfig
}

// tMqConfig MQ配置表
type tMqConfig struct {
	tMqConfigDo tMqConfigDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	ProjectID   field.Int64  // 所属项目ID
	EnvID       field.Int64  // 所属环境ID
	Name        field.String // 配置名称
	Code        field.String // 配置代码
	Type        field.String // MQ类型: rabbitmq, kafka, rocketmq
	Host        field.String // 主机地址
	Port        field.Int32  // 端口
	Username    field.String // 用户名
	Password    field.String // 密码(加密存储)
	Vhost       field.String // RabbitMQ vhost
	Options     field.String // 额外配置(JSON格式)
	Description field.String // 描述
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tMqConfig) Table(newTableName string) *tMqConfig {
	t.tMqConfigDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tMqConfig) As(alias string) *tMqConfig {
	t.tMqConfigDo.DO = *(t.tMqConfigDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tMqConfig) updateTableName(table string) *tMqConfig {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.EnvID = field.NewInt64(table, "env_id")
	t.Name = field.NewString(table, "name")
	t.Code = field.NewString(table, "code")
	t.Type = field.NewString(table, "type")
	t.Host = field.NewString(table, "host")
	t.Port = field.NewInt32(table, "port")
	t.Username = field.NewString(table, "username")
	t.Password = field.NewString(table, "password")
	t.Vhost = field.NewString(table, "vhost")
	t.Options = field.NewString(table, "options")
	t.Description = field.NewString(table, "description")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tMqConfig) WithContext(ctx context.Context) ITMqConfigDo {
	return t.tMqConfigDo.WithContext(ctx)
}

func (t tMqConfig) TableName() string { return t.tMqConfigDo.TableName() }

func (t tMqConfig) Alias() string { return t.tMqConfigDo.Alias() }

func (t tMqConfig) Columns(cols ...field.Expr) gen.Columns { return t.tMqConfigDo.Columns(cols...) }

func (t *tMqConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tMqConfig) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 17)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["env_id"] = t.EnvID
	t.fieldMap["name"] = t.Name
	t.fieldMap["code"] = t.Code
	t.fieldMap["type"] = t.Type
	t.fieldMap["host"] = t.Host
	t.fieldMap["port"] = t.Port
	t.fieldMap["username"] = t.Username
	t.fieldMap["password"] = t.Password
	t.fieldMap["vhost"] = t.Vhost
	t.fieldMap["options"] = t.Options
	t.fieldMap["description"] = t.Description
	t.fieldMap["status"] = t.Status
}

func (t tMqConfig) clone(db *gorm.DB) tMqConfig {
	t.tMqConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tMqConfig) replaceDB(db *gorm.DB) tMqConfig {
	t.tMqConfigDo.ReplaceDB(db)
	return t
}

type tMqConfigDo struct{ gen.DO }

type ITMqConfigDo interface {
	gen.SubQuery
	Debug() ITMqConfigDo
	WithContext(ctx context.Context) ITMqConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITMqConfigDo
	WriteDB() ITMqConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITMqConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITMqConfigDo
	Not(conds ...gen.Condition) ITMqConfigDo
	Or(conds ...gen.Condition) ITMqConfigDo
	Select(conds ...field.Expr) ITMqConfigDo
	Where(conds ...gen.Condition) ITMqConfigDo
	Order(conds ...field.Expr) ITMqConfigDo
	Distinct(cols ...field.Expr) ITMqConfigDo
	Omit(cols ...field.Expr) ITMqConfigDo
	Join(table schema.Tabler, on ...field.Expr) ITMqConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITMqConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITMqConfigDo
	Group(cols ...field.Expr) ITMqConfigDo
	Having(conds ...gen.Condition) ITMqConfigDo
	Limit(limit int) ITMqConfigDo
	Offset(offset int) ITMqConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITMqConfigDo
	Unscoped() ITMqConfigDo
	Create(values ...*model.TMqConfig) error
	CreateInBatches(values []*model.TMqConfig, batchSize int) error
	Save(values ...*model.TMqConfig) error
	First() (*model.TMqConfig, error)
	Take() (*model.TMqConfig, error)
	Last() (*model.TMqConfig, error)
	Find() ([]*model.TMqConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TMqConfig, err error)
	FindInBatches(result *[]*model.TMqConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TMqConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITMqConfigDo
	Assign(attrs ...field.AssignExpr) ITMqConfigDo
	Joins(fields ...field.RelationField) ITMqConfigDo
	Preload(fields ...field.RelationField) ITMqConfigDo
	FirstOrInit() (*model.TMqConfig, error)
	FirstOrCreate() (*model.TMqConfig, error)
	FindByPage(offset int, limit int) (result []*model.TMqConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITMqConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tMqConfigDo) Debug() ITMqConfigDo {
	return t.withDO(t.DO.Debug())
}

func (t tMqConfigDo) WithContext(ctx context.Context) ITMqConfigDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tMqConfigDo) ReadDB() ITMqConfigDo {
	return t.Clauses(dbresolver.Read)
}

func (t tMqConfigDo) WriteDB() ITMqConfigDo {
	return t.Clauses(dbresolver.Write)
}

func (t tMqConfigDo) Session(config *gorm.Session) ITMqConfigDo {
	return t.withDO(t.DO.Session(config))
}

func (t tMqConfigDo) Clauses(conds ...clause.Expression) ITMqConfigDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tMqConfigDo) Returning(value interface{}, columns ...string) ITMqConfigDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tMqConfigDo) Not(conds ...gen.Condition) ITMqConfigDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tMqConfigDo) Or(conds ...gen.Condition) ITMqConfigDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tMqConfigDo) Select(conds ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tMqConfigDo) Where(conds ...gen.Condition) ITMqConfigDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tMqConfigDo) Order(conds ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tMqConfigDo) Distinct(cols ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tMqConfigDo) Omit(cols ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tMqConfigDo) Join(table schema.Tabler, on ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tMqConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tMqConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tMqConfigDo) Group(cols ...field.Expr) ITMqConfigDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tMqConfigDo) Having(conds ...gen.Condition) ITMqConfigDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tMqConfigDo) Limit(limit int) ITMqConfigDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tMqConfigDo) Offset(offset int) ITMqConfigDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tMqConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITMqConfigDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tMqConfigDo) Unscoped() ITMqConfigDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tMqConfigDo) Create(values ...*model.TMqConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tMqConfigDo) CreateInBatches(values []*model.TMqConfig, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tMqConfigDo) Save(values ...*model.TMqConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tMqConfigDo) First() (*model.TMqConfig, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMqConfig), nil
	}
}

func (t tMqConfigDo) Take() (*model.TMqConfig, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMqConfig), nil
	}
}

func (t tMqConfigDo) Last() (*model.TMqConfig, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMqConfig), nil
	}
}

func (t tMqConfigDo) Find() ([]*model.TMqConfig, error) {
	result, err := t.DO.Find()
	return result.([]*model.TMqConfig), err
}

func (t tMqConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TMqConfig, err error) {
	buf := make([]*model.TMqConfig, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tMqConfigDo) FindInBatches(result *[]*model.TMqConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tMqConfigDo) Attrs(attrs ...field.AssignExpr) ITMqConfigDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tMqConfigDo) Assign(attrs ...field.AssignExpr) ITMqConfigDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tMqConfigDo) Joins(fields ...field.RelationField) ITMqConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tMqConfigDo) Preload(fields ...field.RelationField) ITMqConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tMqConfigDo) FirstOrInit() (*model.TMqConfig, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMqConfig), nil
	}
}

func (t tMqConfigDo) FirstOrCreate() (*model.TMqConfig, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TMqConfig), nil
	}
}

func (t tMqConfigDo) FindByPage(offset int, limit int) (result []*model.TMqConfig, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tMqConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tMqConfigDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tMqConfigDo) Delete(models ...*model.TMqConfig) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tMqConfigDo) withDO(do gen.Dao) *tMqConfigDo {
	t.DO = *do.(*gen.DO)
	return t
}
