// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTProjectPermission(db *gorm.DB, opts ...gen.DOOption) tProjectPermission {
	_tProjectPermission := tProjectPermission{}

	_tProjectPermission.tProjectPermissionDo.UseDB(db, opts...)
	_tProjectPermission.tProjectPermissionDo.UseModel(&model.TProjectPermission{})

	tableName := _tProjectPermission.tProjectPermissionDo.TableName()
	_tProjectPermission.ALL = field.NewAsterisk(tableName)
	_tProjectPermission.ID = field.NewInt64(tableName, "id")
	_tProjectPermission.CreatedAt = field.NewTime(tableName, "created_at")
	_tProjectPermission.ProjectID = field.NewInt64(tableName, "project_id")
	_tProjectPermission.UserID = field.NewInt64(tableName, "user_id")
	_tProjectPermission.PermissionCode = field.NewString(tableName, "permission_code")

	_tProjectPermission.fillFieldMap()

	return _tProjectPermission
}

// tProjectPermission 项目权限表
type tProjectPermission struct {
	tProjectPermissionDo tProjectPermissionDo

	ALL            field.Asterisk
	ID             field.Int64
	CreatedAt      field.Time
	ProjectID      field.Int64  // 项目ID
	UserID         field.Int64  // 用户ID
	PermissionCode field.String // 权限代码

	fieldMap map[string]field.Expr
}

func (t tProjectPermission) Table(newTableName string) *tProjectPermission {
	t.tProjectPermissionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tProjectPermission) As(alias string) *tProjectPermission {
	t.tProjectPermissionDo.DO = *(t.tProjectPermissionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tProjectPermission) updateTableName(table string) *tProjectPermission {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.PermissionCode = field.NewString(table, "permission_code")

	t.fillFieldMap()

	return t
}

func (t *tProjectPermission) WithContext(ctx context.Context) ITProjectPermissionDo {
	return t.tProjectPermissionDo.WithContext(ctx)
}

func (t tProjectPermission) TableName() string { return t.tProjectPermissionDo.TableName() }

func (t tProjectPermission) Alias() string { return t.tProjectPermissionDo.Alias() }

func (t tProjectPermission) Columns(cols ...field.Expr) gen.Columns {
	return t.tProjectPermissionDo.Columns(cols...)
}

func (t *tProjectPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tProjectPermission) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["permission_code"] = t.PermissionCode
}

func (t tProjectPermission) clone(db *gorm.DB) tProjectPermission {
	t.tProjectPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tProjectPermission) replaceDB(db *gorm.DB) tProjectPermission {
	t.tProjectPermissionDo.ReplaceDB(db)
	return t
}

type tProjectPermissionDo struct{ gen.DO }

type ITProjectPermissionDo interface {
	gen.SubQuery
	Debug() ITProjectPermissionDo
	WithContext(ctx context.Context) ITProjectPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITProjectPermissionDo
	WriteDB() ITProjectPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITProjectPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITProjectPermissionDo
	Not(conds ...gen.Condition) ITProjectPermissionDo
	Or(conds ...gen.Condition) ITProjectPermissionDo
	Select(conds ...field.Expr) ITProjectPermissionDo
	Where(conds ...gen.Condition) ITProjectPermissionDo
	Order(conds ...field.Expr) ITProjectPermissionDo
	Distinct(cols ...field.Expr) ITProjectPermissionDo
	Omit(cols ...field.Expr) ITProjectPermissionDo
	Join(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo
	Group(cols ...field.Expr) ITProjectPermissionDo
	Having(conds ...gen.Condition) ITProjectPermissionDo
	Limit(limit int) ITProjectPermissionDo
	Offset(offset int) ITProjectPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectPermissionDo
	Unscoped() ITProjectPermissionDo
	Create(values ...*model.TProjectPermission) error
	CreateInBatches(values []*model.TProjectPermission, batchSize int) error
	Save(values ...*model.TProjectPermission) error
	First() (*model.TProjectPermission, error)
	Take() (*model.TProjectPermission, error)
	Last() (*model.TProjectPermission, error)
	Find() ([]*model.TProjectPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectPermission, err error)
	FindInBatches(result *[]*model.TProjectPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TProjectPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITProjectPermissionDo
	Assign(attrs ...field.AssignExpr) ITProjectPermissionDo
	Joins(fields ...field.RelationField) ITProjectPermissionDo
	Preload(fields ...field.RelationField) ITProjectPermissionDo
	FirstOrInit() (*model.TProjectPermission, error)
	FirstOrCreate() (*model.TProjectPermission, error)
	FindByPage(offset int, limit int) (result []*model.TProjectPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITProjectPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tProjectPermissionDo) Debug() ITProjectPermissionDo {
	return t.withDO(t.DO.Debug())
}

func (t tProjectPermissionDo) WithContext(ctx context.Context) ITProjectPermissionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tProjectPermissionDo) ReadDB() ITProjectPermissionDo {
	return t.Clauses(dbresolver.Read)
}

func (t tProjectPermissionDo) WriteDB() ITProjectPermissionDo {
	return t.Clauses(dbresolver.Write)
}

func (t tProjectPermissionDo) Session(config *gorm.Session) ITProjectPermissionDo {
	return t.withDO(t.DO.Session(config))
}

func (t tProjectPermissionDo) Clauses(conds ...clause.Expression) ITProjectPermissionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tProjectPermissionDo) Returning(value interface{}, columns ...string) ITProjectPermissionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tProjectPermissionDo) Not(conds ...gen.Condition) ITProjectPermissionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tProjectPermissionDo) Or(conds ...gen.Condition) ITProjectPermissionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tProjectPermissionDo) Select(conds ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tProjectPermissionDo) Where(conds ...gen.Condition) ITProjectPermissionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tProjectPermissionDo) Order(conds ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tProjectPermissionDo) Distinct(cols ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tProjectPermissionDo) Omit(cols ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tProjectPermissionDo) Join(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tProjectPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tProjectPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tProjectPermissionDo) Group(cols ...field.Expr) ITProjectPermissionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tProjectPermissionDo) Having(conds ...gen.Condition) ITProjectPermissionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tProjectPermissionDo) Limit(limit int) ITProjectPermissionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tProjectPermissionDo) Offset(offset int) ITProjectPermissionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tProjectPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectPermissionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tProjectPermissionDo) Unscoped() ITProjectPermissionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tProjectPermissionDo) Create(values ...*model.TProjectPermission) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tProjectPermissionDo) CreateInBatches(values []*model.TProjectPermission, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tProjectPermissionDo) Save(values ...*model.TProjectPermission) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tProjectPermissionDo) First() (*model.TProjectPermission, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectPermission), nil
	}
}

func (t tProjectPermissionDo) Take() (*model.TProjectPermission, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectPermission), nil
	}
}

func (t tProjectPermissionDo) Last() (*model.TProjectPermission, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectPermission), nil
	}
}

func (t tProjectPermissionDo) Find() ([]*model.TProjectPermission, error) {
	result, err := t.DO.Find()
	return result.([]*model.TProjectPermission), err
}

func (t tProjectPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectPermission, err error) {
	buf := make([]*model.TProjectPermission, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tProjectPermissionDo) FindInBatches(result *[]*model.TProjectPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tProjectPermissionDo) Attrs(attrs ...field.AssignExpr) ITProjectPermissionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tProjectPermissionDo) Assign(attrs ...field.AssignExpr) ITProjectPermissionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tProjectPermissionDo) Joins(fields ...field.RelationField) ITProjectPermissionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tProjectPermissionDo) Preload(fields ...field.RelationField) ITProjectPermissionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tProjectPermissionDo) FirstOrInit() (*model.TProjectPermission, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectPermission), nil
	}
}

func (t tProjectPermissionDo) FirstOrCreate() (*model.TProjectPermission, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectPermission), nil
	}
}

func (t tProjectPermissionDo) FindByPage(offset int, limit int) (result []*model.TProjectPermission, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tProjectPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tProjectPermissionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tProjectPermissionDo) Delete(models ...*model.TProjectPermission) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tProjectPermissionDo) withDO(do gen.Dao) *tProjectPermissionDo {
	t.DO = *do.(*gen.DO)
	return t
}
