// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTProjectMember(db *gorm.DB, opts ...gen.DOOption) tProjectMember {
	_tProjectMember := tProjectMember{}

	_tProjectMember.tProjectMemberDo.UseDB(db, opts...)
	_tProjectMember.tProjectMemberDo.UseModel(&model.TProjectMember{})

	tableName := _tProjectMember.tProjectMemberDo.TableName()
	_tProjectMember.ALL = field.NewAsterisk(tableName)
	_tProjectMember.ID = field.NewInt64(tableName, "id")
	_tProjectMember.CreatedAt = field.NewTime(tableName, "created_at")
	_tProjectMember.ProjectID = field.NewInt64(tableName, "project_id")
	_tProjectMember.UserID = field.NewInt64(tableName, "user_id")

	_tProjectMember.fillFieldMap()

	return _tProjectMember
}

// tProjectMember 项目成员表
type tProjectMember struct {
	tProjectMemberDo tProjectMemberDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	ProjectID field.Int64 // 项目ID
	UserID    field.Int64 // 用户ID

	fieldMap map[string]field.Expr
}

func (t tProjectMember) Table(newTableName string) *tProjectMember {
	t.tProjectMemberDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tProjectMember) As(alias string) *tProjectMember {
	t.tProjectMemberDo.DO = *(t.tProjectMemberDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tProjectMember) updateTableName(table string) *tProjectMember {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.UserID = field.NewInt64(table, "user_id")

	t.fillFieldMap()

	return t
}

func (t *tProjectMember) WithContext(ctx context.Context) ITProjectMemberDo {
	return t.tProjectMemberDo.WithContext(ctx)
}

func (t tProjectMember) TableName() string { return t.tProjectMemberDo.TableName() }

func (t tProjectMember) Alias() string { return t.tProjectMemberDo.Alias() }

func (t tProjectMember) Columns(cols ...field.Expr) gen.Columns {
	return t.tProjectMemberDo.Columns(cols...)
}

func (t *tProjectMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tProjectMember) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["user_id"] = t.UserID
}

func (t tProjectMember) clone(db *gorm.DB) tProjectMember {
	t.tProjectMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tProjectMember) replaceDB(db *gorm.DB) tProjectMember {
	t.tProjectMemberDo.ReplaceDB(db)
	return t
}

type tProjectMemberDo struct{ gen.DO }

type ITProjectMemberDo interface {
	gen.SubQuery
	Debug() ITProjectMemberDo
	WithContext(ctx context.Context) ITProjectMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITProjectMemberDo
	WriteDB() ITProjectMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITProjectMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITProjectMemberDo
	Not(conds ...gen.Condition) ITProjectMemberDo
	Or(conds ...gen.Condition) ITProjectMemberDo
	Select(conds ...field.Expr) ITProjectMemberDo
	Where(conds ...gen.Condition) ITProjectMemberDo
	Order(conds ...field.Expr) ITProjectMemberDo
	Distinct(cols ...field.Expr) ITProjectMemberDo
	Omit(cols ...field.Expr) ITProjectMemberDo
	Join(table schema.Tabler, on ...field.Expr) ITProjectMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITProjectMemberDo
	Group(cols ...field.Expr) ITProjectMemberDo
	Having(conds ...gen.Condition) ITProjectMemberDo
	Limit(limit int) ITProjectMemberDo
	Offset(offset int) ITProjectMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectMemberDo
	Unscoped() ITProjectMemberDo
	Create(values ...*model.TProjectMember) error
	CreateInBatches(values []*model.TProjectMember, batchSize int) error
	Save(values ...*model.TProjectMember) error
	First() (*model.TProjectMember, error)
	Take() (*model.TProjectMember, error)
	Last() (*model.TProjectMember, error)
	Find() ([]*model.TProjectMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectMember, err error)
	FindInBatches(result *[]*model.TProjectMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TProjectMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITProjectMemberDo
	Assign(attrs ...field.AssignExpr) ITProjectMemberDo
	Joins(fields ...field.RelationField) ITProjectMemberDo
	Preload(fields ...field.RelationField) ITProjectMemberDo
	FirstOrInit() (*model.TProjectMember, error)
	FirstOrCreate() (*model.TProjectMember, error)
	FindByPage(offset int, limit int) (result []*model.TProjectMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITProjectMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tProjectMemberDo) Debug() ITProjectMemberDo {
	return t.withDO(t.DO.Debug())
}

func (t tProjectMemberDo) WithContext(ctx context.Context) ITProjectMemberDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tProjectMemberDo) ReadDB() ITProjectMemberDo {
	return t.Clauses(dbresolver.Read)
}

func (t tProjectMemberDo) WriteDB() ITProjectMemberDo {
	return t.Clauses(dbresolver.Write)
}

func (t tProjectMemberDo) Session(config *gorm.Session) ITProjectMemberDo {
	return t.withDO(t.DO.Session(config))
}

func (t tProjectMemberDo) Clauses(conds ...clause.Expression) ITProjectMemberDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tProjectMemberDo) Returning(value interface{}, columns ...string) ITProjectMemberDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tProjectMemberDo) Not(conds ...gen.Condition) ITProjectMemberDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tProjectMemberDo) Or(conds ...gen.Condition) ITProjectMemberDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tProjectMemberDo) Select(conds ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tProjectMemberDo) Where(conds ...gen.Condition) ITProjectMemberDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tProjectMemberDo) Order(conds ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tProjectMemberDo) Distinct(cols ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tProjectMemberDo) Omit(cols ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tProjectMemberDo) Join(table schema.Tabler, on ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tProjectMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tProjectMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tProjectMemberDo) Group(cols ...field.Expr) ITProjectMemberDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tProjectMemberDo) Having(conds ...gen.Condition) ITProjectMemberDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tProjectMemberDo) Limit(limit int) ITProjectMemberDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tProjectMemberDo) Offset(offset int) ITProjectMemberDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tProjectMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITProjectMemberDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tProjectMemberDo) Unscoped() ITProjectMemberDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tProjectMemberDo) Create(values ...*model.TProjectMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tProjectMemberDo) CreateInBatches(values []*model.TProjectMember, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tProjectMemberDo) Save(values ...*model.TProjectMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tProjectMemberDo) First() (*model.TProjectMember, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectMember), nil
	}
}

func (t tProjectMemberDo) Take() (*model.TProjectMember, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectMember), nil
	}
}

func (t tProjectMemberDo) Last() (*model.TProjectMember, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectMember), nil
	}
}

func (t tProjectMemberDo) Find() ([]*model.TProjectMember, error) {
	result, err := t.DO.Find()
	return result.([]*model.TProjectMember), err
}

func (t tProjectMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TProjectMember, err error) {
	buf := make([]*model.TProjectMember, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tProjectMemberDo) FindInBatches(result *[]*model.TProjectMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tProjectMemberDo) Attrs(attrs ...field.AssignExpr) ITProjectMemberDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tProjectMemberDo) Assign(attrs ...field.AssignExpr) ITProjectMemberDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tProjectMemberDo) Joins(fields ...field.RelationField) ITProjectMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tProjectMemberDo) Preload(fields ...field.RelationField) ITProjectMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tProjectMemberDo) FirstOrInit() (*model.TProjectMember, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectMember), nil
	}
}

func (t tProjectMemberDo) FirstOrCreate() (*model.TProjectMember, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TProjectMember), nil
	}
}

func (t tProjectMemberDo) FindByPage(offset int, limit int) (result []*model.TProjectMember, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tProjectMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tProjectMemberDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tProjectMemberDo) Delete(models ...*model.TProjectMember) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tProjectMemberDo) withDO(do gen.Dao) *tProjectMemberDo {
	t.DO = *do.(*gen.DO)
	return t
}
