// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/plugin/dbresolver"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"yqhp/gulu/internal/model"
)

func newTSkillResource(db *gorm.DB, opts ...gen.DOOption) tSkillResource {
	_tSkillResource := tSkillResource{}

	_tSkillResource.tSkillResourceDo.UseDB(db, opts...)
	_tSkillResource.tSkillResourceDo.UseModel(&model.TSkillResource{})

	tableName := _tSkillResource.tSkillResourceDo.TableName()
	_tSkillResource.ALL = field.NewAsterisk(tableName)
	_tSkillResource.ID = field.NewInt64(tableName, "id")
	_tSkillResource.CreatedAt = field.NewTime(tableName, "created_at")
	_tSkillResource.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tSkillResource.SkillID = field.NewInt64(tableName, "skill_id")
	_tSkillResource.Category = field.NewString(tableName, "category")
	_tSkillResource.Filename = field.NewString(tableName, "filename")
	_tSkillResource.Content = field.NewString(tableName, "content")
	_tSkillResource.ContentType = field.NewString(tableName, "content_type")
	_tSkillResource.Size = field.NewInt32(tableName, "size")

	_tSkillResource.fillFieldMap()

	return _tSkillResource
}

// tSkillResource Skill 资源文件表
type tSkillResource struct {
	tSkillResourceDo tSkillResourceDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	SkillID     field.Int64  // 所属Skill ID
	Category    field.String // 资源类别: scripts/references/assets
	Filename    field.String // 文件名
	Content     field.String // 文件内容
	ContentType field.String // MIME类型
	Size        field.Int32  // 文件大小

	fieldMap map[string]field.Expr
}

func (t tSkillResource) Table(newTableName string) *tSkillResource {
	t.tSkillResourceDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tSkillResource) As(alias string) *tSkillResource {
	t.tSkillResourceDo.DO = *(t.tSkillResourceDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tSkillResource) updateTableName(table string) *tSkillResource {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.SkillID = field.NewInt64(table, "skill_id")
	t.Category = field.NewString(table, "category")
	t.Filename = field.NewString(table, "filename")
	t.Content = field.NewString(table, "content")
	t.ContentType = field.NewString(table, "content_type")
	t.Size = field.NewInt32(table, "size")

	t.fillFieldMap()

	return t
}

func (t *tSkillResource) WithContext(ctx context.Context) ITSkillResourceDo {
	return t.tSkillResourceDo.WithContext(ctx)
}

func (t tSkillResource) TableName() string { return t.tSkillResourceDo.TableName() }

func (t tSkillResource) Alias() string { return t.tSkillResourceDo.Alias() }

func (t tSkillResource) Columns(cols ...field.Expr) gen.Columns { return t.tSkillResourceDo.Columns(cols...) }

func (t *tSkillResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tSkillResource) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["skill_id"] = t.SkillID
	t.fieldMap["category"] = t.Category
	t.fieldMap["filename"] = t.Filename
	t.fieldMap["content"] = t.Content
	t.fieldMap["content_type"] = t.ContentType
	t.fieldMap["size"] = t.Size
}

func (t tSkillResource) clone(db *gorm.DB) tSkillResource {
	t.tSkillResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tSkillResource) replaceDB(db *gorm.DB) tSkillResource {
	t.tSkillResourceDo.ReplaceDB(db)
	return t
}

type tSkillResourceDo struct{ gen.DO }

type ITSkillResourceDo interface {
	gen.SubQuery
	Debug() ITSkillResourceDo
	WithContext(ctx context.Context) ITSkillResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITSkillResourceDo
	WriteDB() ITSkillResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITSkillResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITSkillResourceDo
	Not(conds ...gen.Condition) ITSkillResourceDo
	Or(conds ...gen.Condition) ITSkillResourceDo
	Select(conds ...field.Expr) ITSkillResourceDo
	Where(conds ...gen.Condition) ITSkillResourceDo
	Order(conds ...field.Expr) ITSkillResourceDo
	Distinct(cols ...field.Expr) ITSkillResourceDo
	Omit(cols ...field.Expr) ITSkillResourceDo
	Join(table schema.Tabler, on ...field.Expr) ITSkillResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITSkillResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITSkillResourceDo
	Group(cols ...field.Expr) ITSkillResourceDo
	Having(conds ...gen.Condition) ITSkillResourceDo
	Limit(limit int) ITSkillResourceDo
	Offset(offset int) ITSkillResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITSkillResourceDo
	Unscoped() ITSkillResourceDo
	Create(values ...*model.TSkillResource) error
	CreateInBatches(values []*model.TSkillResource, batchSize int) error
	Save(values ...*model.TSkillResource) error
	First() (*model.TSkillResource, error)
	Take() (*model.TSkillResource, error)
	Last() (*model.TSkillResource, error)
	Find() ([]*model.TSkillResource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSkillResource, err error)
	FindInBatches(result *[]*model.TSkillResource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TSkillResource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITSkillResourceDo
	Assign(attrs ...field.AssignExpr) ITSkillResourceDo
	Joins(fields ...field.RelationField) ITSkillResourceDo
	Preload(fields ...field.RelationField) ITSkillResourceDo
	FirstOrInit() (*model.TSkillResource, error)
	FirstOrCreate() (*model.TSkillResource, error)
	FindByPage(offset int, limit int) (result []*model.TSkillResource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITSkillResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tSkillResourceDo) Debug() ITSkillResourceDo {
	return t.withDO(t.DO.Debug())
}

func (t tSkillResourceDo) WithContext(ctx context.Context) ITSkillResourceDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tSkillResourceDo) ReadDB() ITSkillResourceDo {
	return t.Clauses(dbresolver.Read)
}

func (t tSkillResourceDo) WriteDB() ITSkillResourceDo {
	return t.Clauses(dbresolver.Write)
}

func (t tSkillResourceDo) Session(config *gorm.Session) ITSkillResourceDo {
	return t.withDO(t.DO.Session(config))
}

func (t tSkillResourceDo) Clauses(conds ...clause.Expression) ITSkillResourceDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tSkillResourceDo) Returning(value interface{}, columns ...string) ITSkillResourceDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tSkillResourceDo) Not(conds ...gen.Condition) ITSkillResourceDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tSkillResourceDo) Or(conds ...gen.Condition) ITSkillResourceDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tSkillResourceDo) Select(conds ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tSkillResourceDo) Where(conds ...gen.Condition) ITSkillResourceDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tSkillResourceDo) Order(conds ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tSkillResourceDo) Distinct(cols ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tSkillResourceDo) Omit(cols ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tSkillResourceDo) Join(table schema.Tabler, on ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tSkillResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tSkillResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tSkillResourceDo) Group(cols ...field.Expr) ITSkillResourceDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tSkillResourceDo) Having(conds ...gen.Condition) ITSkillResourceDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tSkillResourceDo) Limit(limit int) ITSkillResourceDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tSkillResourceDo) Offset(offset int) ITSkillResourceDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tSkillResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITSkillResourceDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tSkillResourceDo) Unscoped() ITSkillResourceDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tSkillResourceDo) Create(values ...*model.TSkillResource) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tSkillResourceDo) CreateInBatches(values []*model.TSkillResource, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tSkillResourceDo) Save(values ...*model.TSkillResource) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tSkillResourceDo) First() (*model.TSkillResource, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillResource), nil
	}
}

func (t tSkillResourceDo) Take() (*model.TSkillResource, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillResource), nil
	}
}

func (t tSkillResourceDo) Last() (*model.TSkillResource, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillResource), nil
	}
}

func (t tSkillResourceDo) Find() ([]*model.TSkillResource, error) {
	result, err := t.DO.Find()
	return result.([]*model.TSkillResource), err
}

func (t tSkillResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSkillResource, err error) {
	buf := make([]*model.TSkillResource, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tSkillResourceDo) FindInBatches(result *[]*model.TSkillResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tSkillResourceDo) Attrs(attrs ...field.AssignExpr) ITSkillResourceDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tSkillResourceDo) Assign(attrs ...field.AssignExpr) ITSkillResourceDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tSkillResourceDo) Joins(fields ...field.RelationField) ITSkillResourceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tSkillResourceDo) Preload(fields ...field.RelationField) ITSkillResourceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tSkillResourceDo) FirstOrInit() (*model.TSkillResource, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillResource), nil
	}
}

func (t tSkillResourceDo) FirstOrCreate() (*model.TSkillResource, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSkillResource), nil
	}
}

func (t tSkillResourceDo) FindByPage(offset int, limit int) (result []*model.TSkillResource, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tSkillResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tSkillResourceDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tSkillResourceDo) Delete(models ...*model.TSkillResource) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tSkillResourceDo) withDO(do gen.Dao) *tSkillResourceDo {
	t.DO = *do.(*gen.DO)
	return t
}
