// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTTeam(db *gorm.DB, opts ...gen.DOOption) tTeam {
	_tTeam := tTeam{}

	_tTeam.tTeamDo.UseDB(db, opts...)
	_tTeam.tTeamDo.UseModel(&model.TTeam{})

	tableName := _tTeam.tTeamDo.TableName()
	_tTeam.ALL = field.NewAsterisk(tableName)
	_tTeam.ID = field.NewInt64(tableName, "id")
	_tTeam.CreatedAt = field.NewTime(tableName, "created_at")
	_tTeam.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tTeam.IsDelete = field.NewBool(tableName, "is_delete")
	_tTeam.CreatedBy = field.NewInt64(tableName, "created_by")
	_tTeam.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_tTeam.Name = field.NewString(tableName, "name")
	_tTeam.Description = field.NewString(tableName, "description")
	_tTeam.Status = field.NewInt32(tableName, "status")

	_tTeam.fillFieldMap()

	return _tTeam
}

// tTeam 团队表
type tTeam struct {
	tTeamDo tTeamDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	CreatedBy   field.Int64  // 创建人ID
	UpdatedBy   field.Int64  // 更新人ID
	Name        field.String // 团队名称
	Description field.String // 团队描述
	Status      field.Int32  // 状态: 1-启用 0-禁用

	fieldMap map[string]field.Expr
}

func (t tTeam) Table(newTableName string) *tTeam {
	t.tTeamDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTeam) As(alias string) *tTeam {
	t.tTeamDo.DO = *(t.tTeamDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTeam) updateTableName(table string) *tTeam {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.CreatedBy = field.NewInt64(table, "created_by")
	t.UpdatedBy = field.NewInt64(table, "updated_by")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *tTeam) WithContext(ctx context.Context) ITTeamDo { return t.tTeamDo.WithContext(ctx) }

func (t tTeam) TableName() string { return t.tTeamDo.TableName() }

func (t tTeam) Alias() string { return t.tTeamDo.Alias() }

func (t tTeam) Columns(cols ...field.Expr) gen.Columns { return t.tTeamDo.Columns(cols...) }

func (t *tTeam) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTeam) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["updated_by"] = t.UpdatedBy
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["status"] = t.Status
}

func (t tTeam) clone(db *gorm.DB) tTeam {
	t.tTeamDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTeam) replaceDB(db *gorm.DB) tTeam {
	t.tTeamDo.ReplaceDB(db)
	return t
}

type tTeamDo struct{ gen.DO }

type ITTeamDo interface {
	gen.SubQuery
	Debug() ITTeamDo
	WithContext(ctx context.Context) ITTeamDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTeamDo
	WriteDB() ITTeamDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTeamDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTeamDo
	Not(conds ...gen.Condition) ITTeamDo
	Or(conds ...gen.Condition) ITTeamDo
	Select(conds ...field.Expr) ITTeamDo
	Where(conds ...gen.Condition) ITTeamDo
	Order(conds ...field.Expr) ITTeamDo
	Distinct(cols ...field.Expr) ITTeamDo
	Omit(cols ...field.Expr) ITTeamDo
	Join(table schema.Tabler, on ...field.Expr) ITTeamDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTeamDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTeamDo
	Group(cols ...field.Expr) ITTeamDo
	Having(conds ...gen.Condition) ITTeamDo
	Limit(limit int) ITTeamDo
	Offset(offset int) ITTeamDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTeamDo
	Unscoped() ITTeamDo
	Create(values ...*model.TTeam) error
	CreateInBatches(values []*model.TTeam, batchSize int) error
	Save(values ...*model.TTeam) error
	First() (*model.TTeam, error)
	Take() (*model.TTeam, error)
	Last() (*model.TTeam, error)
	Find() ([]*model.TTeam, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTeam, err error)
	FindInBatches(result *[]*model.TTeam, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTeam) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTeamDo
	Assign(attrs ...field.AssignExpr) ITTeamDo
	Joins(fields ...field.RelationField) ITTeamDo
	Preload(fields ...field.RelationField) ITTeamDo
	FirstOrInit() (*model.TTeam, error)
	FirstOrCreate() (*model.TTeam, error)
	FindByPage(offset int, limit int) (result []*model.TTeam, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTeamDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTeamDo) Debug() ITTeamDo {
	return t.withDO(t.DO.Debug())
}

func (t tTeamDo) WithContext(ctx context.Context) ITTeamDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTeamDo) ReadDB() ITTeamDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTeamDo) WriteDB() ITTeamDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTeamDo) Session(config *gorm.Session) ITTeamDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTeamDo) Clauses(conds ...clause.Expression) ITTeamDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTeamDo) Returning(value interface{}, columns ...string) ITTeamDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTeamDo) Not(conds ...gen.Condition) ITTeamDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTeamDo) Or(conds ...gen.Condition) ITTeamDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTeamDo) Select(conds ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTeamDo) Where(conds ...gen.Condition) ITTeamDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTeamDo) Order(conds ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTeamDo) Distinct(cols ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTeamDo) Omit(cols ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTeamDo) Join(table schema.Tabler, on ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTeamDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTeamDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTeamDo) Group(cols ...field.Expr) ITTeamDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTeamDo) Having(conds ...gen.Condition) ITTeamDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTeamDo) Limit(limit int) ITTeamDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTeamDo) Offset(offset int) ITTeamDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTeamDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTeamDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTeamDo) Unscoped() ITTeamDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTeamDo) Create(values ...*model.TTeam) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTeamDo) CreateInBatches(values []*model.TTeam, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTeamDo) Save(values ...*model.TTeam) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTeamDo) First() (*model.TTeam, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeam), nil
	}
}

func (t tTeamDo) Take() (*model.TTeam, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeam), nil
	}
}

func (t tTeamDo) Last() (*model.TTeam, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeam), nil
	}
}

func (t tTeamDo) Find() ([]*model.TTeam, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTeam), err
}

func (t tTeamDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTeam, err error) {
	buf := make([]*model.TTeam, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTeamDo) FindInBatches(result *[]*model.TTeam, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTeamDo) Attrs(attrs ...field.AssignExpr) ITTeamDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTeamDo) Assign(attrs ...field.AssignExpr) ITTeamDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTeamDo) Joins(fields ...field.RelationField) ITTeamDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTeamDo) Preload(fields ...field.RelationField) ITTeamDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTeamDo) FirstOrInit() (*model.TTeam, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeam), nil
	}
}

func (t tTeamDo) FirstOrCreate() (*model.TTeam, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeam), nil
	}
}

func (t tTeamDo) FindByPage(offset int, limit int) (result []*model.TTeam, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTeamDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTeamDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTeamDo) Delete(models ...*model.TTeam) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTeamDo) withDO(do gen.Dao) *tTeamDo {
	t.DO = *do.(*gen.DO)
	return t
}
