// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTTeamMember(db *gorm.DB, opts ...gen.DOOption) tTeamMember {
	_tTeamMember := tTeamMember{}

	_tTeamMember.tTeamMemberDo.UseDB(db, opts...)
	_tTeamMember.tTeamMemberDo.UseModel(&model.TTeamMember{})

	tableName := _tTeamMember.tTeamMemberDo.TableName()
	_tTeamMember.ALL = field.NewAsterisk(tableName)
	_tTeamMember.ID = field.NewInt64(tableName, "id")
	_tTeamMember.CreatedAt = field.NewTime(tableName, "created_at")
	_tTeamMember.TeamID = field.NewInt64(tableName, "team_id")
	_tTeamMember.UserID = field.NewInt64(tableName, "user_id")
	_tTeamMember.Role = field.NewString(tableName, "role")

	_tTeamMember.fillFieldMap()

	return _tTeamMember
}

// tTeamMember 团队成员表
type tTeamMember struct {
	tTeamMemberDo tTeamMemberDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	TeamID    field.Int64  // 团队ID
	UserID    field.Int64  // 用户ID
	Role      field.String // 角色: owner/admin/member

	fieldMap map[string]field.Expr
}

func (t tTeamMember) Table(newTableName string) *tTeamMember {
	t.tTeamMemberDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tTeamMember) As(alias string) *tTeamMember {
	t.tTeamMemberDo.DO = *(t.tTeamMemberDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tTeamMember) updateTableName(table string) *tTeamMember {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.TeamID = field.NewInt64(table, "team_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.Role = field.NewString(table, "role")

	t.fillFieldMap()

	return t
}

func (t *tTeamMember) WithContext(ctx context.Context) ITTeamMemberDo {
	return t.tTeamMemberDo.WithContext(ctx)
}

func (t tTeamMember) TableName() string { return t.tTeamMemberDo.TableName() }

func (t tTeamMember) Alias() string { return t.tTeamMemberDo.Alias() }

func (t tTeamMember) Columns(cols ...field.Expr) gen.Columns { return t.tTeamMemberDo.Columns(cols...) }

func (t *tTeamMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tTeamMember) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["team_id"] = t.TeamID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["role"] = t.Role
}

func (t tTeamMember) clone(db *gorm.DB) tTeamMember {
	t.tTeamMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tTeamMember) replaceDB(db *gorm.DB) tTeamMember {
	t.tTeamMemberDo.ReplaceDB(db)
	return t
}

type tTeamMemberDo struct{ gen.DO }

type ITTeamMemberDo interface {
	gen.SubQuery
	Debug() ITTeamMemberDo
	WithContext(ctx context.Context) ITTeamMemberDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITTeamMemberDo
	WriteDB() ITTeamMemberDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITTeamMemberDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITTeamMemberDo
	Not(conds ...gen.Condition) ITTeamMemberDo
	Or(conds ...gen.Condition) ITTeamMemberDo
	Select(conds ...field.Expr) ITTeamMemberDo
	Where(conds ...gen.Condition) ITTeamMemberDo
	Order(conds ...field.Expr) ITTeamMemberDo
	Distinct(cols ...field.Expr) ITTeamMemberDo
	Omit(cols ...field.Expr) ITTeamMemberDo
	Join(table schema.Tabler, on ...field.Expr) ITTeamMemberDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITTeamMemberDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITTeamMemberDo
	Group(cols ...field.Expr) ITTeamMemberDo
	Having(conds ...gen.Condition) ITTeamMemberDo
	Limit(limit int) ITTeamMemberDo
	Offset(offset int) ITTeamMemberDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITTeamMemberDo
	Unscoped() ITTeamMemberDo
	Create(values ...*model.TTeamMember) error
	CreateInBatches(values []*model.TTeamMember, batchSize int) error
	Save(values ...*model.TTeamMember) error
	First() (*model.TTeamMember, error)
	Take() (*model.TTeamMember, error)
	Last() (*model.TTeamMember, error)
	Find() ([]*model.TTeamMember, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTeamMember, err error)
	FindInBatches(result *[]*model.TTeamMember, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TTeamMember) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITTeamMemberDo
	Assign(attrs ...field.AssignExpr) ITTeamMemberDo
	Joins(fields ...field.RelationField) ITTeamMemberDo
	Preload(fields ...field.RelationField) ITTeamMemberDo
	FirstOrInit() (*model.TTeamMember, error)
	FirstOrCreate() (*model.TTeamMember, error)
	FindByPage(offset int, limit int) (result []*model.TTeamMember, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITTeamMemberDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tTeamMemberDo) Debug() ITTeamMemberDo {
	return t.withDO(t.DO.Debug())
}

func (t tTeamMemberDo) WithContext(ctx context.Context) ITTeamMemberDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tTeamMemberDo) ReadDB() ITTeamMemberDo {
	return t.Clauses(dbresolver.Read)
}

func (t tTeamMemberDo) WriteDB() ITTeamMemberDo {
	return t.Clauses(dbresolver.Write)
}

func (t tTeamMemberDo) Session(config *gorm.Session) ITTeamMemberDo {
	return t.withDO(t.DO.Session(config))
}

func (t tTeamMemberDo) Clauses(conds ...clause.Expression) ITTeamMemberDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tTeamMemberDo) Returning(value interface{}, columns ...string) ITTeamMemberDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tTeamMemberDo) Not(conds ...gen.Condition) ITTeamMemberDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tTeamMemberDo) Or(conds ...gen.Condition) ITTeamMemberDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tTeamMemberDo) Select(conds ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tTeamMemberDo) Where(conds ...gen.Condition) ITTeamMemberDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tTeamMemberDo) Order(conds ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tTeamMemberDo) Distinct(cols ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tTeamMemberDo) Omit(cols ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tTeamMemberDo) Join(table schema.Tabler, on ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tTeamMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tTeamMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tTeamMemberDo) Group(cols ...field.Expr) ITTeamMemberDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tTeamMemberDo) Having(conds ...gen.Condition) ITTeamMemberDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tTeamMemberDo) Limit(limit int) ITTeamMemberDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tTeamMemberDo) Offset(offset int) ITTeamMemberDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tTeamMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITTeamMemberDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tTeamMemberDo) Unscoped() ITTeamMemberDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tTeamMemberDo) Create(values ...*model.TTeamMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tTeamMemberDo) CreateInBatches(values []*model.TTeamMember, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tTeamMemberDo) Save(values ...*model.TTeamMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tTeamMemberDo) First() (*model.TTeamMember, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeamMember), nil
	}
}

func (t tTeamMemberDo) Take() (*model.TTeamMember, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeamMember), nil
	}
}

func (t tTeamMemberDo) Last() (*model.TTeamMember, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeamMember), nil
	}
}

func (t tTeamMemberDo) Find() ([]*model.TTeamMember, error) {
	result, err := t.DO.Find()
	return result.([]*model.TTeamMember), err
}

func (t tTeamMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TTeamMember, err error) {
	buf := make([]*model.TTeamMember, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tTeamMemberDo) FindInBatches(result *[]*model.TTeamMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tTeamMemberDo) Attrs(attrs ...field.AssignExpr) ITTeamMemberDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tTeamMemberDo) Assign(attrs ...field.AssignExpr) ITTeamMemberDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tTeamMemberDo) Joins(fields ...field.RelationField) ITTeamMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tTeamMemberDo) Preload(fields ...field.RelationField) ITTeamMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tTeamMemberDo) FirstOrInit() (*model.TTeamMember, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeamMember), nil
	}
}

func (t tTeamMemberDo) FirstOrCreate() (*model.TTeamMember, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TTeamMember), nil
	}
}

func (t tTeamMemberDo) FindByPage(offset int, limit int) (result []*model.TTeamMember, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tTeamMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tTeamMemberDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tTeamMemberDo) Delete(models ...*model.TTeamMember) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tTeamMemberDo) withDO(do gen.Dao) *tTeamMemberDo {
	t.DO = *do.(*gen.DO)
	return t
}
