// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"yqhp/gulu/internal/model"
)

func newTVar(db *gorm.DB, opts ...gen.DOOption) tVar {
	_tVar := tVar{}

	_tVar.tVarDo.UseDB(db, opts...)
	_tVar.tVarDo.UseModel(&model.TVar{})

	tableName := _tVar.tVarDo.TableName()
	_tVar.ALL = field.NewAsterisk(tableName)
	_tVar.ID = field.NewInt64(tableName, "id")
	_tVar.CreatedAt = field.NewTime(tableName, "created_at")
	_tVar.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tVar.IsDelete = field.NewBool(tableName, "is_delete")
	_tVar.ProjectID = field.NewInt64(tableName, "project_id")
	_tVar.EnvID = field.NewInt64(tableName, "env_id")
	_tVar.Name = field.NewString(tableName, "name")
	_tVar.Key = field.NewString(tableName, "key")
	_tVar.Value = field.NewString(tableName, "value")
	_tVar.Type = field.NewString(tableName, "type")
	_tVar.IsSensitive = field.NewBool(tableName, "is_sensitive")
	_tVar.Description = field.NewString(tableName, "description")

	_tVar.fillFieldMap()

	return _tVar
}

// tVar 变量表
type tVar struct {
	tVarDo tVarDo

	ALL         field.Asterisk
	ID          field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	IsDelete    field.Bool
	ProjectID   field.Int64  // 所属项目ID
	EnvID       field.Int64  // 所属环境ID
	Name        field.String // 变量名称
	Key         field.String // 变量键
	Value       field.String // 变量值
	Type        field.String // 变量类型: string, number, boolean, json
	IsSensitive field.Bool   // 是否敏感数据
	Description field.String // 描述

	fieldMap map[string]field.Expr
}

func (t tVar) Table(newTableName string) *tVar {
	t.tVarDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tVar) As(alias string) *tVar {
	t.tVarDo.DO = *(t.tVarDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tVar) updateTableName(table string) *tVar {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.IsDelete = field.NewBool(table, "is_delete")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.EnvID = field.NewInt64(table, "env_id")
	t.Name = field.NewString(table, "name")
	t.Key = field.NewString(table, "key")
	t.Value = field.NewString(table, "value")
	t.Type = field.NewString(table, "type")
	t.IsSensitive = field.NewBool(table, "is_sensitive")
	t.Description = field.NewString(table, "description")

	t.fillFieldMap()

	return t
}

func (t *tVar) WithContext(ctx context.Context) ITVarDo { return t.tVarDo.WithContext(ctx) }

func (t tVar) TableName() string { return t.tVarDo.TableName() }

func (t tVar) Alias() string { return t.tVarDo.Alias() }

func (t tVar) Columns(cols ...field.Expr) gen.Columns { return t.tVarDo.Columns(cols...) }

func (t *tVar) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tVar) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_delete"] = t.IsDelete
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["env_id"] = t.EnvID
	t.fieldMap["name"] = t.Name
	t.fieldMap["key"] = t.Key
	t.fieldMap["value"] = t.Value
	t.fieldMap["type"] = t.Type
	t.fieldMap["is_sensitive"] = t.IsSensitive
	t.fieldMap["description"] = t.Description
}

func (t tVar) clone(db *gorm.DB) tVar {
	t.tVarDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tVar) replaceDB(db *gorm.DB) tVar {
	t.tVarDo.ReplaceDB(db)
	return t
}

type tVarDo struct{ gen.DO }

type ITVarDo interface {
	gen.SubQuery
	Debug() ITVarDo
	WithContext(ctx context.Context) ITVarDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITVarDo
	WriteDB() ITVarDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITVarDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITVarDo
	Not(conds ...gen.Condition) ITVarDo
	Or(conds ...gen.Condition) ITVarDo
	Select(conds ...field.Expr) ITVarDo
	Where(conds ...gen.Condition) ITVarDo
	Order(conds ...field.Expr) ITVarDo
	Distinct(cols ...field.Expr) ITVarDo
	Omit(cols ...field.Expr) ITVarDo
	Join(table schema.Tabler, on ...field.Expr) ITVarDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITVarDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITVarDo
	Group(cols ...field.Expr) ITVarDo
	Having(conds ...gen.Condition) ITVarDo
	Limit(limit int) ITVarDo
	Offset(offset int) ITVarDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITVarDo
	Unscoped() ITVarDo
	Create(values ...*model.TVar) error
	CreateInBatches(values []*model.TVar, batchSize int) error
	Save(values ...*model.TVar) error
	First() (*model.TVar, error)
	Take() (*model.TVar, error)
	Last() (*model.TVar, error)
	Find() ([]*model.TVar, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TVar, err error)
	FindInBatches(result *[]*model.TVar, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TVar) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITVarDo
	Assign(attrs ...field.AssignExpr) ITVarDo
	Joins(fields ...field.RelationField) ITVarDo
	Preload(fields ...field.RelationField) ITVarDo
	FirstOrInit() (*model.TVar, error)
	FirstOrCreate() (*model.TVar, error)
	FindByPage(offset int, limit int) (result []*model.TVar, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITVarDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tVarDo) Debug() ITVarDo {
	return t.withDO(t.DO.Debug())
}

func (t tVarDo) WithContext(ctx context.Context) ITVarDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tVarDo) ReadDB() ITVarDo {
	return t.Clauses(dbresolver.Read)
}

func (t tVarDo) WriteDB() ITVarDo {
	return t.Clauses(dbresolver.Write)
}

func (t tVarDo) Session(config *gorm.Session) ITVarDo {
	return t.withDO(t.DO.Session(config))
}

func (t tVarDo) Clauses(conds ...clause.Expression) ITVarDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tVarDo) Returning(value interface{}, columns ...string) ITVarDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tVarDo) Not(conds ...gen.Condition) ITVarDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tVarDo) Or(conds ...gen.Condition) ITVarDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tVarDo) Select(conds ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tVarDo) Where(conds ...gen.Condition) ITVarDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tVarDo) Order(conds ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tVarDo) Distinct(cols ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tVarDo) Omit(cols ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tVarDo) Join(table schema.Tabler, on ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tVarDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITVarDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tVarDo) RightJoin(table schema.Tabler, on ...field.Expr) ITVarDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tVarDo) Group(cols ...field.Expr) ITVarDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tVarDo) Having(conds ...gen.Condition) ITVarDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tVarDo) Limit(limit int) ITVarDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tVarDo) Offset(offset int) ITVarDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tVarDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITVarDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tVarDo) Unscoped() ITVarDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tVarDo) Create(values ...*model.TVar) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tVarDo) CreateInBatches(values []*model.TVar, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tVarDo) Save(values ...*model.TVar) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tVarDo) First() (*model.TVar, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TVar), nil
	}
}

func (t tVarDo) Take() (*model.TVar, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TVar), nil
	}
}

func (t tVarDo) Last() (*model.TVar, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TVar), nil
	}
}

func (t tVarDo) Find() ([]*model.TVar, error) {
	result, err := t.DO.Find()
	return result.([]*model.TVar), err
}

func (t tVarDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TVar, err error) {
	buf := make([]*model.TVar, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tVarDo) FindInBatches(result *[]*model.TVar, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tVarDo) Attrs(attrs ...field.AssignExpr) ITVarDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tVarDo) Assign(attrs ...field.AssignExpr) ITVarDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tVarDo) Joins(fields ...field.RelationField) ITVarDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tVarDo) Preload(fields ...field.RelationField) ITVarDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tVarDo) FirstOrInit() (*model.TVar, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TVar), nil
	}
}

func (t tVarDo) FirstOrCreate() (*model.TVar, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TVar), nil
	}
}

func (t tVarDo) FindByPage(offset int, limit int) (result []*model.TVar, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tVarDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tVarDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tVarDo) Delete(models ...*model.TVar) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tVarDo) withDO(do gen.Dao) *tVarDo {
	t.DO = *do.(*gen.DO)
	return t
}
