// Copyright 2024 Grafana Labs
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: workflow.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MasterService_Register_FullMethodName      = "/workflow.v1.MasterService/Register"
	MasterService_Heartbeat_FullMethodName     = "/workflow.v1.MasterService/Heartbeat"
	MasterService_StreamTasks_FullMethodName   = "/workflow.v1.MasterService/StreamTasks"
	MasterService_StreamMetrics_FullMethodName = "/workflow.v1.MasterService/StreamMetrics"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterServiceClient interface {
	// Register registers a slave with the master.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat maintains connection and reports status.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (MasterService_HeartbeatClient, error)
	// StreamTasks streams task assignments and updates.
	StreamTasks(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamTasksClient, error)
	// StreamMetrics streams metrics from slave to master.
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamMetricsClient, error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, MasterService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (MasterService_HeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &MasterService_ServiceDesc.Streams[0], MasterService_Heartbeat_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &masterServiceHeartbeatClient{stream}
	return x, nil
}

type MasterService_HeartbeatClient interface {
	Send(*HeartbeatRequest) error
	Recv() (*HeartbeatResponse, error)
	grpc.ClientStream
}

type masterServiceHeartbeatClient struct {
	grpc.ClientStream
}

func (x *masterServiceHeartbeatClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *masterServiceHeartbeatClient) Recv() (*HeartbeatResponse, error) {
	m := new(HeartbeatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *masterServiceClient) StreamTasks(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &MasterService_ServiceDesc.Streams[1], MasterService_StreamTasks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &masterServiceStreamTasksClient{stream}
	return x, nil
}

type MasterService_StreamTasksClient interface {
	Send(*TaskUpdate) error
	Recv() (*TaskAssignment, error)
	grpc.ClientStream
}

type masterServiceStreamTasksClient struct {
	grpc.ClientStream
}

func (x *masterServiceStreamTasksClient) Send(m *TaskUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *masterServiceStreamTasksClient) Recv() (*TaskAssignment, error) {
	m := new(TaskAssignment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *masterServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MasterService_ServiceDesc.Streams[2], MasterService_StreamMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &masterServiceStreamMetricsClient{stream}
	return x, nil
}

type MasterService_StreamMetricsClient interface {
	Send(*MetricsReport) error
	Recv() (*MetricsAck, error)
	grpc.ClientStream
}

type masterServiceStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *masterServiceStreamMetricsClient) Send(m *MetricsReport) error {
	return x.ClientStream.SendMsg(m)
}

func (x *masterServiceStreamMetricsClient) Recv() (*MetricsAck, error) {
	m := new(MetricsAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MasterServiceServer is the server API for MasterService service.
// All implementations must embed UnimplementedMasterServiceServer
// for forward compatibility
type MasterServiceServer interface {
	// Register registers a slave with the master.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat maintains connection and reports status.
	Heartbeat(MasterService_HeartbeatServer) error
	// StreamTasks streams task assignments and updates.
	StreamTasks(MasterService_StreamTasksServer) error
	// StreamMetrics streams metrics from slave to master.
	StreamMetrics(MasterService_StreamMetricsServer) error
	mustEmbedUnimplementedMasterServiceServer()
}

// UnimplementedMasterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServiceServer struct {
}

func (UnimplementedMasterServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedMasterServiceServer) Heartbeat(MasterService_HeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMasterServiceServer) StreamTasks(MasterService_StreamTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTasks not implemented")
}
func (UnimplementedMasterServiceServer) StreamMetrics(MasterService_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedMasterServiceServer) mustEmbedUnimplementedMasterServiceServer() {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).Heartbeat(&masterServiceHeartbeatServer{stream})
}

type MasterService_HeartbeatServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

type masterServiceHeartbeatServer struct {
	grpc.ServerStream
}

func (x *masterServiceHeartbeatServer) Send(m *HeartbeatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *masterServiceHeartbeatServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MasterService_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).StreamTasks(&masterServiceStreamTasksServer{stream})
}

type MasterService_StreamTasksServer interface {
	Send(*TaskAssignment) error
	Recv() (*TaskUpdate, error)
	grpc.ServerStream
}

type masterServiceStreamTasksServer struct {
	grpc.ServerStream
}

func (x *masterServiceStreamTasksServer) Send(m *TaskAssignment) error {
	return x.ServerStream.SendMsg(m)
}

func (x *masterServiceStreamTasksServer) Recv() (*TaskUpdate, error) {
	m := new(TaskUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MasterService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).StreamMetrics(&masterServiceStreamMetricsServer{stream})
}

type MasterService_StreamMetricsServer interface {
	Send(*MetricsAck) error
	Recv() (*MetricsReport, error)
	grpc.ServerStream
}

type masterServiceStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *masterServiceStreamMetricsServer) Send(m *MetricsAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *masterServiceStreamMetricsServer) Recv() (*MetricsReport, error) {
	m := new(MetricsReport)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.v1.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _MasterService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _MasterService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamTasks",
			Handler:       _MasterService_StreamTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _MasterService_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "workflow.proto",
}
