// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictType = "sys_dict_type"

// SysDictType mapped from table <sys_dict_type>
type SysDictType struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_dict_type_is_delete,priority:1" json:"is_delete"`
	Name      string     `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Code      string     `gorm:"column:code;type:varchar(100);not null;uniqueIndex:idx_sys_dict_type_code,priority:1" json:"code"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
