// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysJob = "sys_job"

// SysJob mapped from table <sys_job>
type SysJob struct {
	ID             int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete       *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_job_is_delete,priority:1" json:"is_delete"`
	CreatedBy      *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"`
	UpdatedBy      *int64     `gorm:"column:updated_by;type:bigint unsigned;comment:更新人ID" json:"updated_by"`
	Name           string     `gorm:"column:name;type:varchar(100);not null;comment:任务名称" json:"name"`
	JobGroup       *string    `gorm:"column:job_group;type:varchar(100);comment:任务分组" json:"job_group"`
	HandlerName    string     `gorm:"column:handler_name;type:varchar(200);not null;index:idx_sys_job_handler_name,priority:1;comment:处理器名称" json:"handler_name"`
	CronExpression string     `gorm:"column:cron_expression;type:varchar(100);not null;comment:cron表达式" json:"cron_expression"`
	Params         *string    `gorm:"column:params;type:text;comment:任务参数(JSON)" json:"params"`
	Status         *int32     `gorm:"column:status;type:tinyint;not null;index:idx_sys_job_status,priority:1;comment:状态: 0-暂停 1-运行中" json:"status"`
	Source         *string    `gorm:"column:source;type:varchar(50);comment:来源: system-系统任务 agent-Agent创建" json:"source"`
	SourceID       *int64     `gorm:"column:source_id;type:bigint unsigned;comment:来源ID" json:"source_id"`
	MisfirePolicy  *int32     `gorm:"column:misfire_policy;type:tinyint;comment:错过策略: 0-忽略 1-立即执行" json:"misfire_policy"`
	Concurrent     *int32     `gorm:"column:concurrent;type:tinyint;comment:是否允许并发: 0-禁止 1-允许" json:"concurrent"`
	RetryCount     *int32     `gorm:"column:retry_count;type:int;comment:失败重试次数" json:"retry_count"`
	RetryInterval  *int32     `gorm:"column:retry_interval;type:int;comment:重试间隔(秒)" json:"retry_interval"`
	Remark         *string    `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`
}

// TableName SysJob's table name
func (*SysJob) TableName() string {
	return TableNameSysJob
}
