// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleResource = "sys_role_resource"

// SysRoleResource mapped from table <sys_role_resource>
type SysRoleResource struct {
	RoleID     int64 `gorm:"column:role_id;type:bigint unsigned;primaryKey" json:"role_id"`
	ResourceID int64 `gorm:"column:resource_id;type:bigint unsigned;primaryKey" json:"resource_id"`
	IsDelete   *bool `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_role_resource_is_delete,priority:1" json:"is_delete"`
}

// TableName SysRoleResource's table name
func (*SysRoleResource) TableName() string {
	return TableNameSysRoleResource
}
