// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOauthUser = "sys_oauth_user"

// SysOauthUser mapped from table <sys_oauth_user>
type SysOauthUser struct {
	ID           int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete     *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_oauth_user_is_delete,priority:1" json:"is_delete"`
	UserID       *int64     `gorm:"column:user_id;type:bigint unsigned;index:idx_sys_oauth_user_user_id,priority:1" json:"user_id"`
	ProviderCode *string    `gorm:"column:provider_code;type:varchar(50);index:idx_sys_oauth_user_provider_code,priority:1" json:"provider_code"`
	OpenID       *string    `gorm:"column:open_id;type:varchar(255);index:idx_sys_oauth_user_open_id,priority:1" json:"open_id"`
	UnionID      *string    `gorm:"column:union_id;type:varchar(255)" json:"union_id"`
	Nickname     *string    `gorm:"column:nickname;type:varchar(100)" json:"nickname"`
	Avatar       *string    `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	AccessToken  *string    `gorm:"column:access_token;type:varchar(500)" json:"access_token"`
	RefreshToken *string    `gorm:"column:refresh_token;type:varchar(500)" json:"refresh_token"`
	ExpiresAt    *int64     `gorm:"column:expires_at;type:bigint" json:"expires_at"`
	RawData      *string    `gorm:"column:raw_data;type:text" json:"raw_data"`
}

// TableName SysOauthUser's table name
func (*SysOauthUser) TableName() string {
	return TableNameSysOauthUser
}
