// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOauthProvider = "sys_oauth_provider"

// SysOauthProvider mapped from table <sys_oauth_provider>
type SysOauthProvider struct {
	ID           int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete     *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_oauth_provider_is_delete,priority:1" json:"is_delete"`
	Name         string     `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Code         string     `gorm:"column:code;type:varchar(50);not null;uniqueIndex:idx_sys_oauth_provider_code,priority:1" json:"code"`
	ClientID     *string    `gorm:"column:client_id;type:varchar(255)" json:"client_id"`
	ClientSecret *string    `gorm:"column:client_secret;type:varchar(255)" json:"client_secret"`
	RedirectURI  *string    `gorm:"column:redirect_uri;type:varchar(255)" json:"redirect_uri"`
	AuthURL      *string    `gorm:"column:auth_url;type:varchar(255)" json:"auth_url"`
	TokenURL     *string    `gorm:"column:token_url;type:varchar(255)" json:"token_url"`
	UserInfoURL  *string    `gorm:"column:user_info_url;type:varchar(255)" json:"user_info_url"`
	Scope        *string    `gorm:"column:scope;type:varchar(255)" json:"scope"`
	Status       *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Sort         *int64     `gorm:"column:sort;type:bigint" json:"sort"`
	Icon         *string    `gorm:"column:icon;type:varchar(100)" json:"icon"`
	Remark       *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysOauthProvider's table name
func (*SysOauthProvider) TableName() string {
	return TableNameSysOauthProvider
}
