// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysConfig = "sys_config"

// SysConfig mapped from table <sys_config>
type SysConfig struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_config_is_delete,priority:1" json:"is_delete"`
	Name      string     `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Key       string     `gorm:"column:key;type:varchar(100);not null;uniqueIndex:idx_sys_config_key,priority:1" json:"key"`
	Value     *string    `gorm:"column:value;type:text" json:"value"`
	Type      *string    `gorm:"column:type;type:varchar(50)" json:"type"`
	IsBuilt   *bool      `gorm:"column:is_built;type:tinyint(1)" json:"is_built"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysConfig's table name
func (*SysConfig) TableName() string {
	return TableNameSysConfig
}
