// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDept = "sys_dept"

// SysDept mapped from table <sys_dept>
type SysDept struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_dept_is_delete,priority:1" json:"is_delete"`
	ParentID  *int64     `gorm:"column:parent_id;type:bigint unsigned" json:"parent_id"`
	Name      string     `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Code      *string    `gorm:"column:code;type:varchar(50)" json:"code"`
	Leader    *string    `gorm:"column:leader;type:varchar(50)" json:"leader"`
	Phone     *string    `gorm:"column:phone;type:varchar(20)" json:"phone"`
	Email     *string    `gorm:"column:email;type:varchar(100)" json:"email"`
	Sort      *int64     `gorm:"column:sort;type:bigint" json:"sort"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysDept's table name
func (*SysDept) TableName() string {
	return TableNameSysDept
}
