// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysLoginLog = "sys_login_log"

// SysLoginLog mapped from table <sys_login_log>
type SysLoginLog struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_login_log_is_delete,priority:1" json:"is_delete"`
	UserID    *int64     `gorm:"column:user_id;type:bigint unsigned;index:idx_sys_login_log_user_id,priority:1" json:"user_id"`
	Username  *string    `gorm:"column:username;type:varchar(50)" json:"username"`
	IP        *string    `gorm:"column:ip;type:varchar(50)" json:"ip"`
	Location  *string    `gorm:"column:location;type:varchar(100)" json:"location"`
	Browser   *string    `gorm:"column:browser;type:varchar(100)" json:"browser"`
	Os        *string    `gorm:"column:os;type:varchar(100)" json:"os"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Message   *string    `gorm:"column:message;type:varchar(255)" json:"message"`
	LoginType *string    `gorm:"column:login_type;type:varchar(50)" json:"login_type"`
}

// TableName SysLoginLog's table name
func (*SysLoginLog) TableName() string {
	return TableNameSysLoginLog
}
