// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "sys_user_role"

// SysUserRole mapped from table <sys_user_role>
type SysUserRole struct {
	UserID   int64 `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`
	RoleID   int64 `gorm:"column:role_id;type:bigint unsigned;primaryKey" json:"role_id"`
	IsDelete *bool `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_user_role_is_delete,priority:1" json:"is_delete"`
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
