// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_role_is_delete,priority:1" json:"is_delete"`
	AppID     int64      `gorm:"column:app_id;type:bigint unsigned;not null;index:idx_sys_role_app_id,priority:1" json:"app_id"`
	Name      string     `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Code      string     `gorm:"column:code;type:varchar(50);not null;index:idx_sys_role_code,priority:1" json:"code"`
	Sort      *int64     `gorm:"column:sort;type:bigint" json:"sort"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
