// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum mapped from table <sys_dict_data>
type SysDictDatum struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_dict_data_is_delete,priority:1" json:"is_delete"`
	CreatedBy *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"` // 创建人ID
	UpdatedBy *int64     `gorm:"column:updated_by;type:bigint unsigned;comment:更新人ID" json:"updated_by"` // 更新人ID
	TypeCode  string     `gorm:"column:type_code;type:varchar(100);not null;index:idx_sys_dict_data_type_code,priority:1" json:"type_code"`
	Label     string     `gorm:"column:label;type:varchar(100);not null" json:"label"`
	Value     string     `gorm:"column:value;type:varchar(100);not null" json:"value"`
	Sort      *int64     `gorm:"column:sort;type:bigint" json:"sort"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	IsDefault *bool      `gorm:"column:is_default;type:tinyint(1)" json:"is_default"`
	CSSClass  *string    `gorm:"column:css_class;type:varchar(100)" json:"css_class"`
	ListClass *string    `gorm:"column:list_class;type:varchar(100)" json:"list_class"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
