// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUserApp = "sys_user_app"

// SysUserApp 用户-应用关联表
type SysUserApp struct {
	ID           int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete     *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_user_app_is_delete,priority:1" json:"is_delete"`
	UserID       int64      `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:uk_user_app,priority:1;index:idx_sys_user_app_user_id,priority:1;comment:用户ID" json:"user_id"` // 用户ID
	AppID        int64      `gorm:"column:app_id;type:bigint unsigned;not null;uniqueIndex:uk_user_app,priority:2;index:idx_sys_user_app_app_id,priority:1;comment:应用ID" json:"app_id"`    // 应用ID
	Source       *string    `gorm:"column:source;type:varchar(50);default:system;comment:注册来源: system-系统创建, oauth-第三方登录, register-自主注册, invite-邀请注册" json:"source"`                        // 注册来源: system-系统创建, oauth-第三方登录, register-自主注册, invite-邀请注册
	FirstLoginAt *time.Time `gorm:"column:first_login_at;type:datetime;comment:首次登录时间" json:"first_login_at"`                                                                              // 首次登录时间
	LastLoginAt  *time.Time `gorm:"column:last_login_at;type:datetime;comment:最后登录时间" json:"last_login_at"`                                                                                // 最后登录时间
	LoginCount   *int32     `gorm:"column:login_count;type:int;comment:登录次数" json:"login_count"`                                                                                           // 登录次数
	Status       *int32     `gorm:"column:status;type:tinyint;default:1;comment:状态: 1-正常, 0-禁用" json:"status"`                                                                             // 状态: 1-正常, 0-禁用
	Remark       *string    `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                                                                                              // 备注
}

// TableName SysUserApp's table name
func (*SysUserApp) TableName() string {
	return TableNameSysUserApp
}
