// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysResource = "sys_resource"

// SysResource mapped from table <sys_resource>
type SysResource struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_resource_is_delete,priority:1" json:"is_delete"`
	CreatedBy *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"` // 创建人ID
	UpdatedBy *int64     `gorm:"column:updated_by;type:bigint unsigned;comment:更新人ID" json:"updated_by"` // 更新人ID
	AppID     int64      `gorm:"column:app_id;type:bigint unsigned;not null;index:idx_sys_resource_app_id,priority:1" json:"app_id"`
	ParentID  *int64     `gorm:"column:parent_id;type:bigint unsigned" json:"parent_id"`
	Name      string     `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Code      *string    `gorm:"column:code;type:varchar(100);index:idx_sys_resource_code,priority:1" json:"code"`
	Type      int32      `gorm:"column:type;type:tinyint;not null" json:"type"`
	Path      *string    `gorm:"column:path;type:varchar(255)" json:"path"`
	Component *string    `gorm:"column:component;type:varchar(255)" json:"component"`
	Redirect  *string    `gorm:"column:redirect;type:varchar(255)" json:"redirect"`
	Icon      *string    `gorm:"column:icon;type:varchar(100)" json:"icon"`
	Sort      *int64     `gorm:"column:sort;type:bigint" json:"sort"`
	IsHidden  *bool      `gorm:"column:is_hidden;type:tinyint(1)" json:"is_hidden"`
	IsCache   *bool      `gorm:"column:is_cache;type:tinyint(1);default:1" json:"is_cache"`
	IsFrame   *bool      `gorm:"column:is_frame;type:tinyint(1)" json:"is_frame"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Remark    *string    `gorm:"column:remark;type:varchar(500)" json:"remark"`
}

// TableName SysResource's table name
func (*SysResource) TableName() string {
	return TableNameSysResource
}
