// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperationLog = "sys_operation_log"

// SysOperationLog mapped from table <sys_operation_log>
type SysOperationLog struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete  *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_sys_operation_log_is_delete,priority:1" json:"is_delete"`
	UserID    *int64     `gorm:"column:user_id;type:bigint unsigned;index:idx_sys_operation_log_user_id,priority:1" json:"user_id"`
	Username  *string    `gorm:"column:username;type:varchar(50)" json:"username"`
	Module    *string    `gorm:"column:module;type:varchar(50)" json:"module"`
	Action    *string    `gorm:"column:action;type:varchar(50)" json:"action"`
	Method    *string    `gorm:"column:method;type:varchar(10)" json:"method"`
	Path      *string    `gorm:"column:path;type:varchar(255)" json:"path"`
	IP        *string    `gorm:"column:ip;type:varchar(50)" json:"ip"`
	UserAgent *string    `gorm:"column:user_agent;type:varchar(500)" json:"user_agent"`
	Params    *string    `gorm:"column:params;type:text" json:"params"`
	Result    *string    `gorm:"column:result;type:text" json:"result"`
	Status    *int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	Duration  *int64     `gorm:"column:duration;type:bigint" json:"duration"`
	ErrorMsg  *string    `gorm:"column:error_msg;type:varchar(500)" json:"error_msg"`
}

// TableName SysOperationLog's table name
func (*SysOperationLog) TableName() string {
	return TableNameSysOperationLog
}
