// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTAiConversationMessage = "t_ai_conversation_message"

// TAiConversationMessage AI工作流会话消息表
type TAiConversationMessage struct {
	ID             int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	ConversationID int64      `gorm:"column:conversation_id;type:bigint unsigned;not null;index:idx_ai_conv_msg_conv_id,priority:1;comment:关联的会话ID" json:"conversation_id"`
	Role           string     `gorm:"column:role;type:varchar(20);not null;comment:消息角色: user/assistant/system" json:"role"`
	Content        string     `gorm:"column:content;type:longtext;not null;comment:消息内容" json:"content"`
	Metadata       *string    `gorm:"column:metadata;type:json;comment:元信息" json:"metadata"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
}

// TableName TAiConversationMessage's table name
func (*TAiConversationMessage) TableName() string {
	return TableNameTAiConversationMessage
}
