// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTAiConversation = "t_ai_conversation"

// TAiConversation AI工作流会话表
type TAiConversation struct {
	ID         int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	WorkflowID int64      `gorm:"column:workflow_id;type:bigint unsigned;not null;index:idx_ai_conv_workflow_id,priority:1;comment:关联的工作流ID" json:"workflow_id"`
	Title      string     `gorm:"column:title;type:varchar(200);default:新的对话;comment:会话标题" json:"title"`
	Variables  *string    `gorm:"column:variables;type:json;comment:会话级变量" json:"variables"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	CreatedBy  *int64     `gorm:"column:created_by;type:bigint unsigned;index:idx_ai_conv_created_by,priority:1;comment:创建人ID" json:"created_by"`
}

// TableName TAiConversation's table name
func (*TAiConversation) TableName() string {
	return TableNameTAiConversation
}
