// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTConfig = "t_config"

// TConfig 配置表
type TConfig struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	ProjectID int64      `gorm:"column:project_id;type:bigint unsigned;not null;index:idx_project_id,priority:1;comment:项目ID(冗余)" json:"project_id"`                      // 项目ID(冗余)
	EnvID     int64      `gorm:"column:env_id;type:bigint unsigned;not null;uniqueIndex:uk_env_code,priority:1;index:idx_env_type,priority:1;comment:环境ID" json:"env_id"` // 环境ID
	Type      string     `gorm:"column:type;type:varchar(32);not null;index:idx_env_type,priority:2;comment:配置类型(冗余，方便查询)" json:"type"`                                   // 配置类型(冗余，方便查询)
	Code      string     `gorm:"column:code;type:varchar(64);not null;uniqueIndex:uk_env_code,priority:2;index:idx_code,priority:1;comment:关联配置定义的code" json:"code"`      // 关联配置定义的code
	Value     string     `gorm:"column:value;type:json;not null;comment:配置值" json:"value"`                                                                                // 配置值
}

// TableName TConfig's table name
func (*TConfig) TableName() string {
	return TableNameTConfig
}
