// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTEnv = "t_env"

// TEnv 环境表
type TEnv struct {
	ID             int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete       *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_t_env_is_delete,priority:1" json:"is_delete"`
	CreatedBy      *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"`                                                 // 创建人ID
	UpdatedBy      *int64     `gorm:"column:updated_by;type:bigint unsigned;comment:更新人ID" json:"updated_by"`                                                 // 更新人ID
	ProjectID      int64      `gorm:"column:project_id;type:bigint unsigned;not null;index:idx_t_env_project_id,priority:1;comment:所属项目ID" json:"project_id"` // 所属项目ID
	Name           string     `gorm:"column:name;type:varchar(100);not null;comment:环境名称" json:"name"`                                                        // 环境名称
	Description    *string    `gorm:"column:description;type:varchar(500);comment:环境描述" json:"description"`                                                   // 环境描述
	Domains        *string    `gorm:"column:domains;type:json;comment:域名配置数组" json:"domains"`                                                                 // 域名配置数组
	Vars           *string    `gorm:"column:vars;type:json;comment:变量配置数组" json:"vars"`                                                                       // 变量配置数组
	DomainsVersion *int32     `gorm:"column:domains_version;type:int;comment:域名配置版本号(乐观锁)" json:"domains_version"`                                            // 域名配置版本号(乐观锁)
	VarsVersion    *int32     `gorm:"column:vars_version;type:int;comment:变量配置版本号(乐观锁)" json:"vars_version"`                                                  // 变量配置版本号(乐观锁)
	Sort           *int64     `gorm:"column:sort;type:bigint;comment:排序" json:"sort"`                                                                         // 排序
	Status         *int32     `gorm:"column:status;type:tinyint;default:1;comment:状态: 1-启用 0-禁用" json:"status"`                                               // 状态: 1-启用 0-禁用
}

// TableName TEnv's table name
func (*TEnv) TableName() string {
	return TableNameTEnv
}
