// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTExecution = "t_execution"

// TExecution 执行记录表
type TExecution struct {
	ID            int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	ProjectID     int64      `gorm:"column:project_id;type:bigint unsigned;not null;index:idx_t_execution_project_id,priority:1;comment:所属项目ID" json:"project_id"`
	SourceID      int64      `gorm:"column:source_id;type:bigint unsigned;not null;index:idx_t_execution_source_id,priority:1;comment:来源ID(工作流ID/测试计划ID等)" json:"source_id"`
	EnvID         int64      `gorm:"column:env_id;type:bigint unsigned;not null;index:idx_t_execution_env_id,priority:1;comment:执行环境ID" json:"env_id"`
	ExecutorID    *string    `gorm:"column:executor_id;type:varchar(100);comment:执行机ID(来自workflow-engine)" json:"executor_id"`
	ExecutionID   string     `gorm:"column:execution_id;type:varchar(100);not null;index:idx_t_execution_execution_id,priority:1;comment:workflow-engine返回的执行ID" json:"execution_id"`
	Mode          string     `gorm:"column:mode;type:varchar(20);not null;index:idx_t_execution_mode,priority:1;default:execute;comment:执行模式: debug, execute" json:"mode"`
	SourceType    string     `gorm:"column:source_type;type:varchar(30);not null;index:idx_t_execution_source_type,priority:1;default:performance;comment:来源类型: performance, test_plan, debug" json:"source_type"`
	Title         string     `gorm:"column:title;type:varchar(256);not null;default:'';comment:执行标题(如工作流名称)" json:"title"`
	Status        string     `gorm:"column:status;type:varchar(20);not null;comment:执行状态: pending, running, completed, failed, stopped, timeout" json:"status"`
	StartTime     *time.Time `gorm:"column:start_time;type:datetime;comment:开始时间" json:"start_time"`
	EndTime       *time.Time `gorm:"column:end_time;type:datetime;comment:结束时间" json:"end_time"`
	Duration      *int64     `gorm:"column:duration;type:bigint;comment:执行时长(毫秒)" json:"duration"`
	CreatedBy     *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"`
}

// TableName TExecution's table name
func (*TExecution) TableName() string {
	return TableNameTExecution
}
