// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTExecutor = "t_executor"

// TExecutor 执行机表
type TExecutor struct {
	ID          int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete    *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_t_executor_is_delete,priority:1" json:"is_delete"`
	SlaveID     string     `gorm:"column:slave_id;type:varchar(100);not null;uniqueIndex:idx_t_executor_slave_id,priority:1;comment:workflow-engine的Slave ID" json:"slave_id"` // workflow-engine的Slave ID
	Name        string     `gorm:"column:name;type:varchar(100);not null;comment:执行机名称" json:"name"`                                                                           // 执行机名称
	Type        string     `gorm:"column:type;type:varchar(50);not null;comment:执行机类型: performance(压测专用), normal(普通), debug(调试专用)" json:"type"`                                // 执行机类型: performance(压测专用), normal(普通), debug(调试专用)
	Description *string    `gorm:"column:description;type:varchar(500);comment:描述" json:"description"`                                                                         // 描述
	Labels      *string    `gorm:"column:labels;type:json;comment:标签 {"env":"prod","region":"cn-east"}" json:"labels"`                                                         // 标签 {"env":"prod","region":"cn-east"}
	MaxVus      *int32     `gorm:"column:max_vus;type:int;comment:最大虚拟用户数限制" json:"max_vus"`                                                                                   // 最大虚拟用户数限制
	Priority    *int32     `gorm:"column:priority;type:int;comment:优先级，数值越大优先级越高" json:"priority"`                                                                             // 优先级，数值越大优先级越高
	Status      *int32     `gorm:"column:status;type:tinyint;default:1;comment:状态: 1-启用 0-禁用" json:"status"`                                                                   // 状态: 1-启用 0-禁用
}

// TableName TExecutor's table name
func (*TExecutor) TableName() string {
	return TableNameTExecutor
}
