// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTMqConfig = "t_mq_config"

// TMqConfig MQ配置表
type TMqConfig struct {
	ID          int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete    *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_t_mq_config_is_delete,priority:1" json:"is_delete"`
	ProjectID   int64      `gorm:"column:project_id;type:bigint unsigned;not null;index:idx_t_mq_config_project_id,priority:1;comment:所属项目ID" json:"project_id"` // 所属项目ID
	EnvID       int64      `gorm:"column:env_id;type:bigint unsigned;not null;index:idx_t_mq_config_env_id,priority:1;comment:所属环境ID" json:"env_id"`             // 所属环境ID
	Name        string     `gorm:"column:name;type:varchar(100);not null;comment:配置名称" json:"name"`                                                              // 配置名称
	Code        string     `gorm:"column:code;type:varchar(50);not null;comment:配置代码" json:"code"`                                                               // 配置代码
	Type        string     `gorm:"column:type;type:varchar(20);not null;comment:MQ类型: rabbitmq, kafka, rocketmq" json:"type"`                                    // MQ类型: rabbitmq, kafka, rocketmq
	Host        string     `gorm:"column:host;type:varchar(255);not null;comment:主机地址" json:"host"`                                                              // 主机地址
	Port        int32      `gorm:"column:port;type:int;not null;comment:端口" json:"port"`                                                                         // 端口
	Username    *string    `gorm:"column:username;type:varchar(100);comment:用户名" json:"username"`                                                                // 用户名
	Password    *string    `gorm:"column:password;type:varchar(500);comment:密码(加密存储)" json:"password"`                                                           // 密码(加密存储)
	Vhost       *string    `gorm:"column:vhost;type:varchar(100);comment:RabbitMQ vhost" json:"vhost"`                                                           // RabbitMQ vhost
	Options     *string    `gorm:"column:options;type:text;comment:额外配置(JSON格式)" json:"options"`                                                                 // 额外配置(JSON格式)
	Description *string    `gorm:"column:description;type:varchar(500);comment:描述" json:"description"`                                                           // 描述
	Status      *int32     `gorm:"column:status;type:tinyint;default:1;comment:状态: 1-启用 0-禁用" json:"status"`                                                     // 状态: 1-启用 0-禁用
}

// TableName TMqConfig's table name
func (*TMqConfig) TableName() string {
	return TableNameTMqConfig
}
