// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTProject = "t_project"

// TProject 项目表
type TProject struct {
	ID          int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete    *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_t_project_is_delete,priority:1" json:"is_delete"`
	CreatedBy   *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"`   // 创建人ID
	UpdatedBy   *int64     `gorm:"column:updated_by;type:bigint unsigned;comment:更新人ID" json:"updated_by"`   // 更新人ID
	TeamID      int64      `gorm:"column:team_id;type:bigint;not null;comment:所属团队ID" json:"team_id"`        // 所属团队ID
	Name        string     `gorm:"column:name;type:varchar(100);not null;comment:项目名称" json:"name"`          // 项目名称
	Description *string    `gorm:"column:description;type:varchar(500);comment:项目描述" json:"description"`     // 项目描述
	Icon        *string    `gorm:"column:icon;type:varchar(255);comment:项目图标" json:"icon"`                   // 项目图标
	Sort        *int64     `gorm:"column:sort;type:bigint;comment:排序" json:"sort"`                           // 排序
	Status      *int32     `gorm:"column:status;type:tinyint;default:1;comment:状态: 1-启用 0-禁用" json:"status"` // 状态: 1-启用 0-禁用
}

// TableName TProject's table name
func (*TProject) TableName() string {
	return TableNameTProject
}
