// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTProjectPermission = "t_project_permission"

// TProjectPermission 项目权限表
type TProjectPermission struct {
	ID             int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	ProjectID      int64      `gorm:"column:project_id;type:bigint unsigned;not null;uniqueIndex:idx_project_user_permission,priority:1;index:idx_t_project_permission_project_id,priority:1;comment:项目ID" json:"project_id"` // 项目ID
	UserID         int64      `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:idx_project_user_permission,priority:2;index:idx_t_project_permission_user_id,priority:1;comment:用户ID" json:"user_id"`          // 用户ID
	PermissionCode string     `gorm:"column:permission_code;type:varchar(50);not null;uniqueIndex:idx_project_user_permission,priority:3;comment:权限代码" json:"permission_code"`                                                // 权限代码
}

// TableName TProjectPermission's table name
func (*TProjectPermission) TableName() string {
	return TableNameTProjectPermission
}
