// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTProjectMember = "t_project_member"

// TProjectMember 项目成员表
type TProjectMember struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	ProjectID int64      `gorm:"column:project_id;type:bigint unsigned;not null;uniqueIndex:idx_project_user,priority:1;index:idx_t_project_member_project_id,priority:1;comment:项目ID" json:"project_id"` // 项目ID
	UserID    int64      `gorm:"column:user_id;type:bigint unsigned;not null;uniqueIndex:idx_project_user,priority:2;index:idx_t_project_member_user_id,priority:1;comment:用户ID" json:"user_id"`          // 用户ID
}

// TableName TProjectMember's table name
func (*TProjectMember) TableName() string {
	return TableNameTProjectMember
}
