// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTSkill = "t_skill"

// TSkill AI Skill表（兼容 Agent Skills 开放标准）
type TSkill struct {
	ID                      int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt               *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt               *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete                *bool      `gorm:"column:is_delete;type:tinyint(1);default:0;index:idx_t_skill_is_delete,priority:1" json:"is_delete"`
	CreatedBy               *int64     `gorm:"column:created_by;type:bigint unsigned;comment:创建人ID" json:"created_by"`
	Name                    string     `gorm:"column:name;type:varchar(100);not null;comment:显示名称" json:"name"`
	Slug                    *string    `gorm:"column:slug;type:varchar(64);uniqueIndex:uk_t_skill_slug;comment:标准化名称kebab-case" json:"slug"`
	Description             *string    `gorm:"column:description;type:varchar(1024);comment:Skill描述" json:"description"`
	Icon                    *string    `gorm:"column:icon;type:varchar(100);comment:图标标识" json:"icon"`
	Category                *string    `gorm:"column:category;type:varchar(50);index:idx_t_skill_category,priority:1;comment:分类" json:"category"`
	Tags                    *string    `gorm:"column:tags;type:json;comment:标签" json:"tags"`
	SystemPrompt            string     `gorm:"column:system_prompt;type:text;not null;comment:系统提示词" json:"system_prompt"`
	Variables               *string    `gorm:"column:variables;type:json;comment:变量声明" json:"variables"`
	RecommendedModelParams  *string    `gorm:"column:recommended_model_params;type:json;comment:推荐模型参数" json:"recommended_model_params"`
	RecommendedTools        *string    `gorm:"column:recommended_tools;type:json;comment:推荐内置工具" json:"recommended_tools"`
	RecommendedMcpServerIDs *string    `gorm:"column:recommended_mcp_server_ids;type:json;comment:推荐MCP服务ID" json:"recommended_mcp_server_ids"`
	License                 *string    `gorm:"column:license;type:varchar(500);comment:许可证" json:"license"`
	Compatibility           *string    `gorm:"column:compatibility;type:varchar(500);comment:环境要求" json:"compatibility"`
	MetadataJSON            *string    `gorm:"column:metadata_json;type:json;comment:扩展元数据" json:"metadata_json"`
	AllowedTools            *string    `gorm:"column:allowed_tools;type:text;comment:预批准工具列表" json:"allowed_tools"`
	Type                    *int32     `gorm:"column:type;type:tinyint;default:0;index:idx_t_skill_type,priority:1;comment:类型: 0-用户自建 1-系统内置 2-导入" json:"type"`
	IsPublic                *int32     `gorm:"column:is_public;type:tinyint;default:0;comment:是否公开" json:"is_public"`
	Version                 *string    `gorm:"column:version;type:varchar(20);default:1.0.0;comment:版本号" json:"version"`
	Sort                    *int32     `gorm:"column:sort;type:int;default:0;comment:排序" json:"sort"`
	Status                  *int32     `gorm:"column:status;type:tinyint;default:1;index:idx_t_skill_status,priority:1;comment:状态: 1-启用 0-禁用" json:"status"`
}

// TableName TSkill's table name
func (*TSkill) TableName() string {
	return TableNameTSkill
}
