// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTVar = "t_var"

// TVar 变量表
type TVar struct {
	ID          int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDelete    *bool      `gorm:"column:is_delete;type:tinyint(1);index:idx_t_var_is_delete,priority:1" json:"is_delete"`
	ProjectID   int64      `gorm:"column:project_id;type:bigint unsigned;not null;index:idx_t_var_project_id,priority:1;comment:所属项目ID" json:"project_id"` // 所属项目ID
	EnvID       int64      `gorm:"column:env_id;type:bigint unsigned;not null;index:idx_t_var_env_id,priority:1;comment:所属环境ID" json:"env_id"`             // 所属环境ID
	Name        string     `gorm:"column:name;type:varchar(100);not null;comment:变量名称" json:"name"`                                                        // 变量名称
	Key         string     `gorm:"column:key;type:varchar(100);not null;comment:变量键" json:"key"`                                                           // 变量键
	Value       *string    `gorm:"column:value;type:text;comment:变量值" json:"value"`                                                                        // 变量值
	Type        *string    `gorm:"column:type;type:varchar(20);default:string;comment:变量类型: string, number, boolean, json" json:"type"`                    // 变量类型: string, number, boolean, json
	IsSensitive *bool      `gorm:"column:is_sensitive;type:tinyint(1);comment:是否敏感数据" json:"is_sensitive"`                                                 // 是否敏感数据
	Description *string    `gorm:"column:description;type:varchar(500);comment:描述" json:"description"`                                                     // 描述
}

// TableName TVar's table name
func (*TVar) TableName() string {
	return TableNameTVar
}
